### ISSUE TITLE
Is there a correct way to change the listening port for Uptime Kuma?

### ISSUE THREAD

**Issue by risharde** [louislam/uptime-kuma#1065]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi guys, is there an easy / correct way to change the listening port for Uptime Kuma? I'm seeing a few places in the code where 3001 seems to be hard coded so just want to make sure. Please let me know, thanks!

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

CENTOS 7

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

None

### 🟩 NodeJS Version

16.x

**Comment by louislam** [comment]
Yes, you can.

Environment Variable: `UPTIME_KUMA_PORT=12345`
Argument: `node server/server.js --port 12345`

**Comment by CanonCan** [comment]
Hi Louis

I am wondering as a fairly new Linux user how to accompish this using ubuntu 20.04 LTS and the NodeJS

**Comment by olivierIllogika** [comment]
After pulling a few hair, it appears that the correct syntax is actually: `node server/server.js --port=12345`

Using `--port 12345` sets the args object as follow:
`{ '12345': true, port: true }`

instead of the desired:
`{ port: 12345 }`

Also, the server looks at the `PORT` environment variable before defaulting to 3001. Running from [overmind](https://github.com/DarthSim/overmind) that specifies `PORT=5000` will affect the default.

**Comment by AnthraxBPLLC** [comment]
Or you can edit the server.js by nanow and doing CTRL+W type "3001" change it to your port number

**Comment by louislam** [comment]
> Or you can edit the server.js by nanow and doing CTRL+W type "3001" change it to your port number

Not recommended, it will be reset when update
