### ISSUE TITLE
Check for internal domain

### ISSUE THREAD

**Issue by dcardellino** [louislam/uptime-kuma#1112]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey guys,

I want to check an internal service domain for being up and running. I use my pihole as local dns server, where the record for my service is created.

For example this service is **vault.internal.domain.com** but uptime-kuma can't resolve this domain

Because this service is only running in LAN I do not have created an A record on cloudflare or similar.

Is there a possibility to tell kuma where my dns record lives?

```[Vault] [DOWN] getaddrinfo ENOTFOUND```

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04 amd64

### 🌐 Browser

Mozilla Firefox

### 🐋 Docker Version

K3s 1.21.5

**Comment by louislam** [comment]
Currently, Uptime Kuma relayed with system's DNS, which means you have to deal with k3s.

For Docker, it should be something like this:
https://www.deploycontainers.com/2021/10/27/set-custom-dns-server-on-a-docker-container/

**Comment by xpufx** [comment]
> Because this service is only running in LAN I do not have created an A record on cloudflare or similar.

If you add the domain to cloudflare etc, you can give it a private IP. RFC doesn't like it but it's supported. If your DNS resolver doesn't have a problem with it, it will work fine. You might need to whitelist this domain out of DNS Rebinding protection.

**Comment by dcardellino** [comment]
> Currently, Uptime Kuma relayed with system's DNS, which means you have to deal with k3s.
> 
> For Docker, it should be something like this: https://www.deploycontainers.com/2021/10/27/set-custom-dns-server-on-a-docker-container/

Got it fixed was an issue with systemd-resolved. Thanks for the hint ;)

**Comment by tchartron** [comment]
I ran into issues for this type of scenario,

Running coredns in a docker container, i want to add a monitor in uptime-kuma to do a HTTPS check for a service that is listed in the zonefile of the local containerized coredns.

First, i has to bind the host ip when running coredns container (instead of the port only) :
```
docker run -d --name coredns -p 53:53/tcp -p 192.168.200.11:53:53/udp registry.gitlab.com/XXXXX/XXXXX/coredns/coredns:0.0.1
```

Then i had to allow the docker network subnet uptime kuma is on in ufw : `sudo ufw allow from 172.18.0.0/24`

Then i also had to allow the docker network subnet in my traefik ip whitelist as the service i want to monitor is behind a traefik proxy.

Hope this helps someone !
