### ISSUE TITLE
Easier way to install on Plesk

### ISSUE THREAD

**Issue by EinfachKonrad** [louislam/uptime-kuma#1264]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I tried to install it on Plesk, buit without the docker addon did it not work. 

### ✔️ Solution

Just an final "ready-to-config"-website-directory, which i can put into the folder of the site and work with it!

**Comment by rezzorix** [comment]
Well you have 2 options.. install with or without docker.
And in Plesk it is actually easy to do with either options... 

In either case however, you need to install dependencies - Docker or NPM...

**Comment by papahausa** [comment]
> ### ⚠️ Please verify that this feature request has NOT been suggested before.
> * [x]  I checked and didn't find similar feature request
> 
> ### 🏷️ Feature Request Type
> Other
> 
> ### 🔖 Feature description
> I tried to install it on Plesk, buit without the docker addon did it not work.
> 
> ### ✔️ Solution
> Just an final "ready-to-config"-website-directory, which i can put into the folder of the site and work with it!
> 
> ### ❓ Alternatives
> _No response_
> 
> ### 📝 Additional Context
> _No response_

Can u help me install it on plesk?

**Comment by rezzorix** [comment]
What is your OS & version?
What is your Plesk version?

Do you have SSH-access to the server?

If no:
Do you have any of the following extensions installed in Plesk? 
- SSH Terminal (https://www.plesk.com/extensions/ssh-terminal/)
- Docker (https://www.plesk.com/extensions/docker/)

**Comment by louislam** [comment]
Close as current README.md is already the easier way. 

Plesk is mainly for PHP apps only, Uptime Kuma is a Node.js app.

**Comment by rezzorix** [comment]
> Plesk is mainly for PHP apps only, Uptime Kuma is a Node.js app

Sorry, thats not correct @louislam 

Plesk is a server / hosting management frontend.
You fully manage servers with that; it is equivalent to cpanel or similar and is standard with a lot vserver / ded. server providers.

So question could be relevant for some people.

**Comment by louislam** [comment]
> Just an final "ready-to-config"-website-directory, which i can put into the folder of the site and work with it

Since op was asking for drag-and-drop files into a folder like the PHP way, I think it is a impossible `feature-request`.

If @papahausa need help, I would suggest you should open a new thread with proper info.

**Comment by papahausa** [comment]
> What is your OS & version? What is your Plesk version?
> 
> Do you have SSH-access to the server?
> 
> If no: Do you have any of the following extensions installed in Plesk?
> 
> * SSH Terminal (https://www.plesk.com/extensions/ssh-terminal/)
> * Docker (https://www.plesk.com/extensions/docker/)

Plesk: 18.0.49
Docker extension installed. https://prnt.sc/FXIlOF7nLm1V
Do you have SSH-access to the server?  - yes, i have.

https://prnt.sc/kqDadb1zWld_
looks like work, but how assign it to subdomain with ssl?

**Comment by Dudebaker** [comment]
It took me some hours but now I have uptime-kuma running on Plesk without any SSH access or docker installation.

I'm not sure why I have to do the round-trip with the local machine, Plesk creates a own git-folder in a parent directory, but this folder does not work if I copy it into the newly created .git folder in the main folder of uptime-kuma.

Anyway...

### Here is the how to run uptime-kuma on Plesk v18.0.52 (or later), in my case on AlmaLinux 9.1:


**Preparations on your local machine:**
1. Install Git or your PC
2. Clone the uptime-kuma repository with the following command
`git clone https://github.com/louislam/uptime-kuma.git`
3. The .git folder in the newly created folder will be needed to be uploaded to the server (see below)

**Preparations on your Plesk Server:**
1. Install Git Extension
2. Install Node.js Extensions

**Installing uptime-kuma on your Plesk Server:**
1. Create a new webspace with Node.js enabled
2. Add SSL-Certificate via Let's Encrypt or your own certificate
3. Go to "Apache & nginx" Settings and change the following:
- [ ] Untick "Proxy Mode"
- [x] Add the following as additional nginx directives:
> location ~ /(node|socket.io) {
> 	proxy_set_header X-Real-IP $remote_addr;
> 	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 	proxy_set_header Host $host;
> 	proxy_http_version 1.1;
> 	proxy_set_header Upgrade $http_upgrade;
> 	proxy_set_header Connection "upgrade";
> }
4. Go to the Git Extensions and add the repository with the following settings:
- [x] Repository URL:		https://github.com/louislam/uptime-kuma.git
- [x] Repository Name:		uptime-kuma.git
- [x] Server path:		/httpdocs
5. Go to the files and open the httpdocs folder, now you should see the cloned repository
6. Upload the whole ".git"-folder from your local machine into the /httpdocs/ folder
7. Go to the Node.js settings and use the following settings:
- [x] Node.js Version:		18.16.0
- [x] Package Manager:		npm
- [x] Document Root:		/httpdocs/server
- [x] Application Mode:		production
- [x] Application Root:		/httpdocs
- [x] Application Startup File:	server/server.js
- [x] Custom env. variable:
`Variable: 	name`
`Value: 	uptime-kuma`

8. Click "Enable Node.js"
9. Open the "Run Node.js commands" Tab and enter the following commands one by one
`install`
`run setup`
10. Installation finished! 

You can now open the URL and start to create the first user.
If you're stuck on the "/dashboard" path you have to wait a little bit or restart the app in the Node.js settings.
Then you should be redirected to the "/setup" path.

**Comment by Thoomaastb** [comment]
@chrsdrdt Unfortunately I searched for a solution to install on plesk but I might help with your problem too: Try to replace "localhost" with your real IP address. Attempt to connect to 127.0.0.1:3001" refers to "Attempt to connect to localhost".

**Comment by vesvello** [comment]
I got this error when I tried npm install

npm ERR! code 127
npm ERR! path /var/www/vhosts/uptime-kuma/node_modules/ssh2
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! sh: 1: node: not found


Any ideas?

**Comment by CommanderStorm** [comment]
Please post full details with your environment and what you did to get there in a separate issue.
Necroposting like this is not maintainable.

My idea would be that node is not found.
=> you need to install that ^^

**Comment by vesvello** [comment]
I hope this helps
![WhatsApp Image 2024-03-11 at 15 28 18](https://github.com/louislam/uptime-kuma/assets/278606/ccc1dc39-448c-48af-b25c-6cfdd46d439e)
![WhatsApp Image 2024-03-11 at 15 31 07](https://github.com/louislam/uptime-kuma/assets/278606/cc829f12-2c9e-41a7-baac-51bf87f88657)

Process exited with non-zero exit code '127'

npm WARN deprecated event-to-promise@0.7.0: Use promise-toolbox/fromEvent instead
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated @azure/msal-node@1.18.4: A newer major version of this library is available. Please upgrade to the latest available version.
npm WARN deprecated @azure/msal-browser@2.38.3: A newer major version of this library is available. Please upgrade to the latest available version.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 127
npm ERR! path /var/www/vhosts/cl*********mx/uptime.cloudpos.mx/uptime-kuma/node_modules/ssh2
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! sh: 1: node: not found

npm ERR! A complete log of this run can be found in: /var/www/vhosts/cl********x/public_html/deliverapp/.npm/_logs/2024-03-11T21_28_48_209Z-debug-0.log

**Comment by vesvello** [comment]
> I asked for full context in a different issue for a reason.
> 
> Currently, you have posted the state you are in. You have omitted:
> 
> * what your concrete environment is


Plesk Obsidian Version 18.0.58 Update #2
Ubuntu 22.04.4 LTS
PHP version 8.1.27, run PHP as Dedicated FPM application served by nginx
Node.js Version 18.19.1

> * what happened before

Clean install  going step by step and the mesaget got when I run npm install
-> this step: Open the "Run Node.js commands" Tab and enter the following commands one by one
install
>   
>   * what guide did you follow?

I went throught this guide:

https://github.com/louislam/uptime-kuma/issues/1264#issuecomment-1531401026

>   * Have you gone back and made sure that no steps were skipped?

Yes

> * what you have tried already

I tried 3 or 4 tomes to star over, deleting de account and starting again to be sure no steps were skipped and everytimaI got this message

I tried to run npm install --force and npm install --legacy-peer-deps byut same results

**Comment by vesvello** [comment]
Apparently is installed ok
<img width="339" alt="Captura de pantalla 2024-03-12 a la(s) 09 59 30" src="https://github.com/louislam/uptime-kuma/assets/278606/5c31baf8-338b-4ba9-97cb-7a58ee018b2c">

**Comment by CommanderStorm** [comment]
> can run the `node -v` command by itself?

**Comment by vesvello** [comment]
no... in plesk node is an extension... i need to run plesk ext nodejs

**Comment by chrsdrdt** [comment]
> I got this error when I tried `npm install`
> 
> ```
> npm ERR! code 127
> npm ERR! path /var/www/vhosts/uptime-kuma/node_modules/ssh2
> npm ERR! command failed
> npm ERR! command sh -c node install.js
> npm ERR! sh: 1: node: not found
> ```
> 
> Any ideas?

Yes, same happened to me. Tried different things and what helped me was to (re-)set the node version in the Dashboard of your node.js application.
