### ISSUE TITLE
Add folder groupings for monitors

### ISSUE THREAD

**Issue by cruzanstx** [louislam/uptime-kuma#1296]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Add the ability to cluster various types of monitors together in the form of a folder. Potentially make that folder's color change depending on the aggregate color of the sub monitors. 

### ✔️ Solution

Either folders for grouping or maybe a tag system that you can tag monitors and filter based on the tags.

**Comment by thierrybla** [comment]
Big vouch!

**Comment by krejcar25** [comment]
> Would like to be able to add tags to the status page, so all new monitors with a tag are added to the status page. 
That would be #1726 fyi

**Comment by ka2er** [comment]
I Upvote this

**Comment by CommanderStorm** [comment]
@cruzanstx 
I think what you requested has been resolved by https://github.com/louislam/uptime-kuma/pull/2693 in the [`1.22`-release](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0).
If you agree, could you please close this Issue, as otherwise this would create immortal zombies which are really hard to issue-manage?
If not, could you better describe this issue unique enough to require an additional issue? (removing what has been resolved, explaining clearer if something is missing) ^^

**Comment by CommanderStorm** [comment]
Closing as resolved by https://github.com/louislam/uptime-kuma/pull/2693 in the [`1.22`-release](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0).
