### ISSUE TITLE
how to setup Discord Embed

### ISSUE THREAD

**Issue by Korrumz2PL** [louislam/uptime-kuma#1301]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The default embed value contains a link to an IP address that I don't want to share because anyone who is on my Discord server can see it, btw, I would like to write my own embed

Can this be changed somehow? 

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Debian 10, Linux

### 🌐 Browser

MSEdge

### 🟩 NodeJS Version

latest

**Comment by Korrumz2PL** [comment]
(this is about notifications)

**Comment by mindlesstux** [comment]
Looking at the code 
https://github.com/louislam/uptime-kuma/blob/da74391c3e6c315d2f317f7f34224a50a4431520/server/notification-providers/discord.js
And the apprise alternative to send a discord message
https://github.com/louislam/uptime-kuma/blob/da74391c3e6c315d2f317f7f34224a50a4431520/server/notification-providers/apprise.js

I dont see a way that you can modify the message that is sent.  It appears that choosing the "native" discord option sends a card.  If you use apprise and send to discord that way you get something like:

[6:27 PM] BOT KumaTuz: [TF2] [🔴 Down] Server not found on Steam
Which may be more to your liking.

Looking at https://github.com/caronc/apprise/wiki/Notify_discord tells you basically how to configure the apprise URL for DIscord.
discord://---webhookid---/---webhooktoken---/?option=value&option2=value

Not sure if the format tag would do anything for you but I'll try poking it later tonight to see what the outcome is.  If I don't report back assume no luck.

**Comment by orestiskarap** [comment]
I would like to comment that i was able to send a Discord Embed using the "Webhook" option instead of "Discord". 

1. Paste the Discord webhook URL in **POST URL**.

2. Select `Custom Body` in **Request Body** and in there enter your JSON, you can use something like this:
  
  ```json
  {
    "username": "Bot Name",
    "avatar_url": "urltoavatar.png",
    "content": "@everyone",
    "embeds": [{
      "title": "Attention! Backup Unsuccessful!",
      "description": "Backup was unsucessful",
      "color": "16711680",
      "footer": { "text": "Uptime Kuma" }
    }]
  }
  ```

3. Add this to **Additional Headers**, or else discord won't accept it:
  ```json
  {
     "Content-Type": "application/json"
  }
  ```

You could also use the `{{ msg }}`, `{{ heartbeatJSON }}` and ``{{ monitorJSON }}`` variables, although i couldn't find their exact contents through the documentation.

Hope someone out there finds it useful!
