### ISSUE TITLE
Monitor shows DOWN but website is UP

### ISSUE THREAD

**Issue by BalticSurfer** [louislam/uptime-kuma#1333]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, 

i have configuered 20 monitors with Uptime Kuma. But I have following problem.

The websites are regularly shown to me as down although they are definitely up.
Following DOWN messages I get:
- getaddrinfo ENOTFOUND
- timeout of 240000ms exceeded
- timeout of 480000ms exceeded
- Request failed with status code 503
- Request failed with status code 504

Does somebody has any idea?

Greetings
Jan

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chrome

**Comment by ontheair81** [comment]
Had the same issue since some days, sometimes monitors fail with "Request timeout", but the services are up, instead. This goes for different monitors (ping, https, dns). Using Uptime Kuma with 39 monitors right now.

I just changed the DNS from Quad9 to Google (8.8.8.8 instead of 9.9.9.9) in my compose file, the problem seems to be gone.
Of course, I have to monitor that over a longer period of time to be sure this was the reason.

**Comment by DunklerPhoenix** [comment]
I have the same problem for different services, but also for ipadresses in my vpn network. I don't use any domains inside of it.

**Comment by adog1314** [comment]
Hi All,

Do any of you happen to be using CloudFlare? 

Recently, we just started getting lots of 503 errors on any website running behind CF; after several weeks of troubleshooting, even setting up a remote monitor on a different ISP. The situation however seemingly resolved itself after I disabled the CF proxy.

It seem to start happening after updating to 1.11.4, but think the actual bug might be something on CF's side, because I have had "503 Service Temporarily Unavailable - cloudflare" happen when accessing the site site from my home connection twice, in addition to the relentless stream of Uptime Kuma 503 errors.

![WpE9MMxCNJ](https://user-images.githubusercontent.com/8061981/157596211-6323a480-8014-4df1-a363-ee0b2f803852.png)

**Comment by poqdavid** [comment]
I also have the same problem with the web pages that use CF but every time I visit those pages they are just fine
everything that is being monitored by direct IP is totally fine

**Comment by adog1314** [comment]
> I also have the same problem with the web pages that use CF but every time I visit those pages they are just fine But also happens if it's not proxied everything that is being monitored by direct IP is totally fine


Do you happen to connect to Cloudflare Toronto? 
I found someone on the Cloudflare discord having the same issue, and a common denominator seems to be the Cloudflare Toronto. 

https://community.cloudflare.com/t/503-errors-potentially-related-to-cf-toronto/369439

**Comment by poqdavid** [comment]
> > I also have the same problem with the web pages that use CF but every time I visit those pages they are just fine But also happens if it's not proxied everything that is being monitored by direct IP is totally fine
> 
> Do you happen to connect to Cloudflare Toronto? I found someone on the Cloudflare discord having the same issue, and a common denominator seems to be the Cloudflare Toronto.
> 
> https://community.cloudflare.com/t/503-errors-potentially-related-to-cf-toronto/369439

I am not 100% sure but the server that is hosting the uptime kuma is located in Canada so I think the CDN should connect using a connection in Canada

**Comment by johnfelipe** [comment]
And what about if kuma is installed locally but with DMZ?

**Comment by vutsalsinghal** [comment]
Had the same issue. Solved it by disabling "bot fight mode". When you disable it, make sure you compensate it by adding necessary firewall rule

**Comment by harshavmb** [comment]
I am also having the same problem, no cloudflare nothing in between, just an HTTP endpoint. 

I could access the same HTTP URL from the container where uptime runs, no DNS involved only IP. 

What's weird is when I changed that `http` port to `tcp`, it worked, so something is wrong with uptime kuma. I found no logs, internet says it's stored in sqllite database. 

I'll migrate this to Mysql database to find more information.

**Comment by harshavmb** [comment]
Okay, in my case the error message is `timeout by AbortSignal (48s)` & there is an open issue [#275 ](https://github.com/louislam/uptime-kuma/issues/275).

**Comment by harshavmb** [comment]
I encountered the same issue last week, further triage led me to MTU issues as I use Tailscale to route subnets & it complicates even more if Proxmox SDN is used as several bytes of headers were eaten.

If you run uptimekuma in a docker container, clamp the MSS size of the docker daemon to the maximum value the target service accepts (you get this value by pinging with -S argument). You don't need to make any change to the host. 

I hope this helps.
