### ISSUE TITLE
Locking russian translate

### ISSUE THREAD

**Issue by mcking230** [louislam/uptime-kuma#1340]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

You want me to call Putin or what? None of all presidents can stop him, so what you want developers/IT people to do?

### 👟 Reproduction steps

NaN

### 👀 Expected behavior

NaN

### 😓 Actual Behavior

NaN

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

fedora 35

### 🌐 Browser

Brave

### 🐋 Docker Version

20.10

**Comment by captainhook** [comment]
Honestly, this is harmful to Russian citizens who have nothing to do with/are against the current ongoings.

I understand the devs and contributers want to be on the right side of history, but this is not the right way about it. There are people suggestions Apple bans App store access, software companies block software updates, etc., and it harms innocent Russian citizens.

If you want to maintain this change, then we must ask why you haven't done the same for:
- Israel and it's crimes arsonist Palestine which has been under internationally illegal occupation since 1967, and more recently has been declared an Aparteid.
- China which has millions of people in concentration camps, kidnapping children, raping women in prisons, etc.

Please reconsider this action, it is not going to make any difference, you can raise awareness in a different non-destructive way. Innocent citizens and developers/IT nerds are not going to change Putin's mind.

**Comment by captainhook** [comment]
> > Honestly, this is harmful to Russian citizens who have nothing to do with/are against the current ongoings.
> > I understand the devs and contributers want to be on the right side of history, but this is not the right way about it. There are people suggesting Apple bans App store access, software companies block software updates, etc., and all these ideas harm innocent Russian citizens.
> > If you want to maintain this change, then we must ask why you haven't done the same for:
> > 
> > * Israel and it's crimes against Palestine which has been under internationally illegal occupation since 1967, and more recently has been declared an apartheid.
> > * China which has millions of Uighur people in concentration camps, brainwashing children, raping women in prisons, forcing Muslim Uighur women to marry Chinese men loyal to the secular state, etc.
> > 
> > Please reconsider this action, it is not going to make any difference, you can raise awareness in a different non-destructive way. Innocent citizens and developers/IT nerds are not going to change Putin's mind.
> 
> Thank you all, It is just so painful to read the recent news. I just want to use my little power to change it. Sorry for the inconvenience. Give me some time. I will reconsider this action.

Your intention is commendable and we appreciate it, thank you for rethinking this action.

**Comment by louislam** [comment]
> 75% of Ukrainians speak Russian

Ops, thank you for let me know this, I should revert this.

**Comment by louislam** [comment]
> upheaval

Thank you for understanding, 1.12.1 will be released soon. Stay safe everyone.

**Comment by mcking230** [comment]
> Too late, the moron already changed it, and he didn't even take 2 seconds to Google it in Russian so they can actually read it. In other words, he ruined an entire translation for nothing, Congrats.

Please, don't be so aggressive. He will unroll this changes.

(Для русских. Друзья, ну ошибся парень, думал что сможет повлиять на мир. Не ругайтесь и не оскорбляйте здесь никого. Я понимаю, он меня сам взбесил, но это площадка не для ненависти. Спасибо за внимание)

**Comment by mcking230** [comment]
@louislam close this issue or it will not end!
