### ISSUE TITLE
Update alert not working

### ISSUE THREAD

**Issue by mathiskir** [louislam/uptime-kuma#1469]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

<img width="644" alt="image" src="https://user-images.githubusercontent.com/65130981/162581725-ea8709e1-b60e-45e0-82ea-fe1cc0e74075.png">
The newest version is 1.13.2 but it doesn't show me that i can update but it should cause i activated that feature.

### 👟 Reproduction steps

1. Install uptime kuma 1.13.1
2. activate update alert
3. (restart)

### 👀 Expected behavior

It should show that there's a new version

### 😓 Actual Behavior

Just nothing, it isn't showing the alert.

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Newest Edge

### 🐋 Docker Version

-

### 🟩 NodeJS Version

14.19.1

### 📝 Relevant log output

```shell
No log output given
```

**Comment by louislam** [comment]
I would say it is by design, because I want to roll out slowly.

It check this endpoint periodically: https://uptime.kuma.pet/version

- The checking interval is about 48 hours, it may need some time to hit next tick.
- It check the version in "slow" property. It is still pointing to 1.13.1, because there is no special change in 1.13.2. And as its name, I will update this value slow.
