### ISSUE TITLE
Add the status page to the backup.json file

### ISSUE THREAD

**Issue by Urban-Hacker** [louislam/uptime-kuma#1500]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I had to restore recently my uptime kuma instance on a brand new installation. I though the .json backup was enough and yes it contains all the monitors but miss the status page which is a bit sad since it forces to manually recreate it.

### ✔️ Solution

Simply add dashboard info to the json to allow for quick restore

### ❓ Alternatives

Currently the main alternative is either a low level backup (backing up the database etc) or rebuilding the status page manually.

**Comment by tarun7singh** [comment]
If this issue is still up for grabs I would like to start work on it.
I might need a little bit of guidance on it.

**Comment by Computroniks** [comment]
@tarun7singh I don't see any pull requests for this so you might as well take a crack at it. I would recommend creating an empty commit using `git commit -m "[empty commit] pull request for <YOUR TASK NAME>" --allow-empty` before you start working as this will allow you to create a PR and get some assistance and feedback on your work.

**Comment by prof79** [comment]
This would be very much appreciated (y) Also had a corruption issue yesterday and re-creating a page with 140+ monitors is no fun. Especially, which would be stuff for other feature requests, since you can't sort or mass-move or mass-select stuff, adding monitors only honors the top-most group, ...

**Comment by kristiandg** [comment]
I vote for this one as well. A lot of design effort going into laying out the perfect status page, only to lose it would be a huge bummer. :)

**Comment by Drallas** [comment]
Is this still open?

**Comment by CommanderStorm** [comment]
> Is this still open?

Yes, this is still an open issue. If you look at the json output of the status pages.

Contributions to https://github.com/louislam/uptime-kuma/pull/2667 are likely welcome.
Currently, the PR is **not blocked on functionality/implementation but on testing**
⇒ if somebody wants to help @chakflying, this would be appreciated

**Comment by chakflying** [comment]
Obsolete as the backup feature has been dropped in #3892.

**Comment by CommanderStorm** [comment]
Chiming in with a more in-depth explanation:

Please see https://github.com/louislam/uptime-kuma/issues/2141#issuecomment-1272360952

> In 1.18.3, the backup feature was deprecated due to [being left] unmaintained.

Backup & Restore with JSON has been deprecated and issues will not be fixed due to the amount of problems it has been causing for our users and us.
The current design is just not maintainable, causing countless bugs.
In `v2.0` the deprecated backup tool is being removed because of this reason.
Please consider using SQL, API based[^1] or infrastructure based[^2] backup instead. 

New approaches to these features should use [SQLite dump](https://www.sqlitetutorial.net/sqlite-dump/) or [MariaDB dump](https://mariadb.com/kb/en/mariadb-dump/) respectively. (Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md))

You can subscribe to these issues meanwhile:
- #2496
- #477

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
[^2]: see https://github.com/louislam/uptime-kuma/issues/477#issuecomment-1557966187 for a setup example
