### ISSUE TITLE
wrangler Cloudflare

### ISSUE THREAD

**Issue by vaheed** [louislam/uptime-kuma#1553]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

First of all thanks for great job :)

Can use Kuma as Cloudflare worker ?

[node-js-support-cloudflare-workers](https://blog.cloudflare.com/node-js-support-cloudflare-workers/)

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Google Chrome 100

**Comment by louislam** [comment]
That is interesting, I will look into it. Thank you for your information.

**Comment by vaheed** [comment]
Thanks, I will wait :)

**Comment by louislam** [comment]
Just have a quick look, it isn't a real Node.js unfortunately.

And Cloudflare Worker is still handling thing per http request, while Uptime Kuma need to run as a server. So it is impossible to run on it.

> What packages don't work?
Many packages that require Node dependencies, such as fs or net/http, aren't supported in Workers because Workers isn't Node—it's [built on V8](https://developers.cloudflare.com/workers/learning/how-workers-works).

**Comment by vaheed** [comment]
Yes, I know workers don't support server-side, I think the Kuma community can add something like this 
status page on Cloudflare workers

something like this on Kuma
https://github.com/eidam/cf-workers-status-page
