### ISSUE TITLE
Cannot build/update on FreeBSD

### ISSUE THREAD

**Issue by draga79** [louislam/uptime-kuma#1574]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Uptime-Kuma 1.14.0 was building and running on a FreeBSD jail. When trying to upgrade to 1.15.0 (or perform a new installation), it fails:

[...]
2310 error command sh -c node-pre-gyp install --fallback-to-build
2311 error gmake: Entering directory '/root/node_modules/@louislam/sqlite3/build'
2311 error   CC(target) Release/obj.target/nothing/../../node-addon-api/nothing.o
2311 error   AR(target) Release/obj.target/../../node-addon-api/nothing.a
2311 error   COPY Release/nothing.a
2311 error   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3380200/sqlite3.c
2311 error   TOUCH Release/obj.target/deps/action_before_build.stamp
2311 error   CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3380200/sqlite3.o
2311 error gmake: Leaving directory '/root/node_modules/@louislam/sqlite3/build'
2311 error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
2312 error node-pre-gyp info it worked if it ends with ok
2312 error node-pre-gyp info using node-pre-gyp@1.0.9
2312 error node-pre-gyp info using node@14.18.1 | freebsd | x64
2312 error node-pre-gyp info check checked for "/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node" (not found)
2312 error node-pre-gyp http GET https://github.com/louislam/node-sqlite3/releases/download/v15.0.3/napi-v6-freebsd-x64-unknown.tar.gz
2312 error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/louislam/node-sqlite3/releases/download/v15.0.3/napi-v6-freebsd-x64-unknown.tar.gz
2312 error node-pre-gyp WARN Pre-built binaries not installable for @louislam/sqlite3@15.0.3 and node@14.18.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
2312 error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/louislam/node-sqlite3/releases/download/v15.0.3/napi-v6-freebsd-x64-unknown.tar.gz
2312 error gyp info it worked if it ends with ok
2312 error gyp info using node-gyp@8.4.1
2312 error gyp info using node@14.18.1 | freebsd | x64
2312 error gyp info ok
2312 error gyp info it worked if it ends with ok
2312 error gyp info using node-gyp@8.4.1
2312 error gyp info using node@14.18.1 | freebsd | x64
2312 error gyp info find Python using Python version 3.8.13 found at "/usr/local/bin/python3.8"
2312 error gyp http GET https://nodejs.org/download/release/v14.18.1/node-v14.18.1-headers.tar.gz
2312 error gyp http 200 https://nodejs.org/download/release/v14.18.1/node-v14.18.1-headers.tar.gz
2312 error gyp http GET https://nodejs.org/download/release/v14.18.1/SHASUMS256.txt
2312 error gyp http 200 https://nodejs.org/download/release/v14.18.1/SHASUMS256.txt
2312 error gyp info spawn /usr/local/bin/python3.8
2312 error gyp info spawn args [
2312 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2312 error gyp info spawn args   'binding.gyp',
2312 error gyp info spawn args   '-f',
2312 error gyp info spawn args   'make',
2312 error gyp info spawn args   '-I',
2312 error gyp info spawn args   '/root/node_modules/@louislam/sqlite3/build/config.gypi',
2312 error gyp info spawn args   '-I',
2312 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2312 error gyp info spawn args   '-I',
2312 error gyp info spawn args   '/root/.cache/node-gyp/14.18.1/include/node/common.gypi',
2312 error gyp info spawn args   '-Dlibrary=shared_library',
2312 error gyp info spawn args   '-Dvisibility=default',
2312 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.18.1',
2312 error gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
2312 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.18.1/<(target_arch)/node.lib',
2312 error gyp info spawn args   '-Dmodule_root_dir=/root/node_modules/@louislam/sqlite3',
2312 error gyp info spawn args   '-Dnode_engine=v8',
2312 error gyp info spawn args   '--depth=.',
2312 error gyp info spawn args   '--no-parallel',
2312 error gyp info spawn args   '--generator-output',
2312 error gyp info spawn args   'build',
2312 error gyp info spawn args   '-Goutput_dir=.'
2312 error gyp info spawn args ]
2312 error gyp info ok
2312 error gyp info it worked if it ends with ok
2312 error gyp info using node-gyp@8.4.1
2312 error gyp info using node@14.18.1 | freebsd | x64
2312 error gyp info spawn gmake
2312 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2312 error In file included from <built-in>:1:
2312 error ./../src/gcc-preinclude.h:5:10: fatal error: 'features.h' file not found
2312 error #include <features.h>
2312 error          ^~~~~~~~~~~~
2312 error 1 error generated.
2312 error gmake: *** [deps/sqlite3.target.mk:143: Release/obj.target/sqlite3/gen/sqlite-autoconf-3380200/sqlite3.o] Error 1
2312 error gyp ERR! build error
2312 error gyp ERR! stack Error: `gmake` failed with exit code: 2
2312 error gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2312 error gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
2312 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
2312 error gyp ERR! System FreeBSD 13.0-RELEASE-p8
2312 error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
2312 error gyp ERR! cwd /root/node_modules/@louislam/sqlite3
2312 error gyp ERR! node -v v14.18.1
2312 error gyp ERR! node-gyp -v v8.4.1
2312 error gyp ERR! not ok
2312 error node-pre-gyp ERR! build error
2312 error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
2312 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
2312 error node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
2312 error node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
2312 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
2312 error node-pre-gyp ERR! System FreeBSD 13.0-RELEASE-p8
2312 error node-pre-gyp ERR! command "/usr/local/bin/node" "/root/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2312 error node-pre-gyp ERR! cwd /root/node_modules/@louislam/sqlite3
2312 error node-pre-gyp ERR! node -v v14.18.1
2312 error node-pre-gyp ERR! node-pre-gyp -v v1.0.9
2312 error node-pre-gyp ERR! not ok
2313 verbose exit 1
2314 timing npm Completed in 54143ms
2315 verbose unfinished npm timer reify 1651041708320
2316 verbose unfinished npm timer reify:build 1651041733341
2317 verbose unfinished npm timer build 1651041733360
2318 verbose unfinished npm timer build:deps 1651041733360
2319 verbose unfinished npm timer build:run:install 1651041733476
2320 verbose unfinished npm timer build:run:install:node_modules/@louislam/sqlite3 1651041733476

Thank you.

### 👟 Reproduction steps

Just follow the official steps: https://github.com/louislam/uptime-kuma/wiki/🆙-How-to-Update#--non-docker

### 👀 Expected behavior

Builds and runs.

### 😓 Actual Behavior

The error described above.

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

FreeBSD 13.0 / amd64

### 🌐 Browser

No browser

### 🟩 NodeJS Version

14 and 16 - not different

**Comment by louislam** [comment]
It looks like a node-sqlite3 issue.

I think you should try to create an empty directory and run `npm install sqlite3`, see if same error.
If yes, please report to their repo.

> ./../src/gcc-preinclude.h:5:10: fatal error: 'features.h' file not found

https://github.com/TryGhost/node-sqlite3/blob/master/src/gcc-preinclude.h

Also please note that I do not test Uptime Kuma on FreeBSD. It is not supported officially. Docker or Debian-based Linux are recommended.

**Comment by bvgastel** [comment]
`npm install sqlite3` works fine on FreeBSD. `npm install @louislam/sqlite3@15.0.3` fails. So seems like it is not working with your own version of sqlite3?

**Comment by louislam** [comment]
It looks like they fixed the FreeBSD issue in 5.0.4.

I will merge upstream updates later.

**Comment by bvgastel** [comment]
Thanks, that would be nice!

**Comment by louislam** [comment]
```bash
npm install @louislam/sqlite3@15.0.6
```

I merged upstream source code, hope this fix your issue.

**Comment by Efiartes** [comment]
Whe i try to install sqli3@15.0.6 uptime-kuma is broken by another library:
`
UptimeKuma # ~/uptime-kuma> npm install @louislam/sqlite3@15.0.6
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /root/uptime-kuma/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /root/uptime-kuma/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
npm ERR!         throw new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Unsupported platform: freebsd
npm ERR!     at assert (/root/uptime-kuma/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
npm ERR!     at BrowserFetcher.setPlatform (/root/uptime-kuma/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:180:36)
npm ERR!     at new BrowserFetcher (/root/uptime-kuma/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:164:14)
npm ERR!     at PuppeteerNode.createBrowserFetcher (/root/uptime-kuma/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:185:16)
npm ERR!     at downloadBrowser (/root/uptime-kuma/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:51:46)
npm ERR!     at download (/root/uptime-kuma/node_modules/puppeteer/install.js:86:3)
npm ERR! 
npm ERR! Node.js v17.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-06T18_42_48_017Z-debug-0.log
`

**Comment by Efiartes** [comment]
But puppeteer can be installed in FreeBSD executing:
`
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install puppeteer
`

**Comment by Efiartes** [comment]
But trying inside uptime-kuma project it breaks:
`UptimeKuma # ~/uptime-kuma> PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install puppeteer
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /root/uptime-kuma/node_modules/@louislam/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! gmake: Entering directory '/root/uptime-kuma/node_modules/@louislam/sqlite3/build'
npm ERR!   CC(target) Release/obj.target/nothing/../../node-addon-api/nothing.o
npm ERR!   AR(target) Release/obj.target/../../node-addon-api/nothing.a
npm ERR!   COPY Release/nothing.a
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3380200/sqlite3.c
npm ERR!   TOUCH Release/obj.target/deps/action_before_build.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3380200/sqlite3.o
npm ERR! gmake: Leaving directory '/root/uptime-kuma/node_modules/@louislam/sqlite3/build'
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/uptime-kuma/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/uptime-kuma/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@17.0.1 | freebsd | x64
npm ERR! node-pre-gyp info check checked for "/root/uptime-kuma/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/louislam/node-sqlite3/releases/download/v15.0.3/napi-v6-freebsd-x64-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/louislam/node-sqlite3/releases/download/v15.0.3/napi-v6-freebsd-x64-unknown.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @louislam/sqlite3@15.0.3 and node@17.0.1 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/louislam/node-sqlite3/releases/download/v15.0.3/napi-v6-freebsd-x64-unknown.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.0.1 | freebsd | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.0.1 | freebsd | x64
npm ERR! gyp info find Python using Python version 3.8.13 found at "/usr/local/bin/python3.8"
npm ERR! gyp info spawn /usr/local/bin/python3.8
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/uptime-kuma/node_modules/@louislam/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/17.0.1/include/node/common.gypi',
{
    "name": "uptime-kuma",
    "version": "1.15.1",
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "https://github.com/louislam/uptime-kuma.git"
    },
    "engines": {
        "node": "14.* || >=16.*"
    },
    "scripts": {
{
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/17.0.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/17.0.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/uptime-kuma/node_modules/@louislam/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.0.1 | freebsd | x64
npm ERR! gyp info spawn gmake
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from <built-in>:1:
npm ERR! ./../src/gcc-preinclude.h:5:10: fatal error: 'features.h' file not found
npm ERR! #include <features.h>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! gmake: *** [deps/sqlite3.target.mk:145: Release/obj.target/sqlite3/gen/sqlite-autoconf-3380200/sqlite3.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `gmake` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System FreeBSD 13.0-RELEASE-p11
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/uptime-kuma/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/uptime-kuma/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
npm ERR! gyp ERR! cwd /root/uptime-kuma/node_modules/@louislam/sqlite3
npm ERR! gyp ERR! node -v v17.0.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/uptime-kuma/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/uptime-kuma/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/uptime-kuma/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System FreeBSD 13.0-RELEASE-p11
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/root/uptime-kuma/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /root/uptime-kuma/node_modules/@louislam/sqlite3
npm ERR! node-pre-gyp ERR! node -v v17.0.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-06T18_47_56_687Z-debug-0.log
`

**Comment by Efiartes** [comment]
I thin puppeteer needs sqlite and sqlite needs puppeteer? But only inside uptime-kuma directory? I dont undertand how node project dependencies works.

**Comment by louislam** [comment]
Puppeteer is a dev dependency, end-users don't need this. Maybe you need to specify `--production`.

Also refer to my first comment here:

> Also please note that I do not test Uptime Kuma on FreeBSD. It is not supported officially. Docker or Debian-based Linux are recommended.

**Comment by Efiartes** [comment]
My infraestructure is working under FreeBSD i so sorry but i would have to search for a FreeBSD compatible alternative.

**Comment by louislam** [comment]
At this point, you may need to stick to 1.14.1 first. You can try again if 1.16.0 get released.

**Comment by Efiartes** [comment]
will 1.14.1 work under FreeBSD? i will try it

**Comment by Efiartes** [comment]
I can confirm that 1.14.1 version works under FreeBSD without issues, i will stick to it since 1.15 gets more mature and compatible with other systems.

**Comment by Efiartes** [comment]
Can i contribute in some way to adapt new version to FreeBSD?
I am sysadmin not coder but i can test you changes if you want.
