### ISSUE TITLE
Backup doesnt restore monitor notifications

### ISSUE THREAD

**Issue by Efiartes** [louislam/uptime-kuma#1631]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have installed last uptime-kuma version: 1.15.1 under Ubuntu22.04/amd64 and node: v16.15.0
The steps to reproduce are:
- I configure some notifiation methods
- I configure one monitor enabling some notification methods
- I backup uptime-kuma
- I restore uptime-kuma

The monitor is restored but with all notification methods disabled.

### 👟 Reproduction steps

The steps to reproduce are:
- I configure some notifiation methods
- I configure one monitor enabling some notification methods
- I backup uptime-kuma
- I restore uptime-kuma

The monitor is restored but with all notification methods disabled.

### 👀 Expected behavior

A complete restoration including monitors and the linked notification methods of each monitor.

### 😓 Actual Behavior

The monitors are restored but with all notification methods disabled.

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Ubuntu22.04/amd64

### 🌐 Browser

Version 101.0.4951.54 (Build oficial) (64 bits)

### 🟩 NodeJS Version

16.15.0

**Comment by chakflying** [comment]
Obsolete as the backup feature has been dropped in #3892.

**Comment by CommanderStorm** [comment]
Chiming in with a more in-depth explanation:

Please see https://github.com/louislam/uptime-kuma/issues/2141#issuecomment-1272360952

> In 1.18.3, the backup feature was deprecated due to [being left] unmaintained.

Backup & Restore with JSON has been deprecated and issues will not be fixed due to the amount of problems it has been causing for our users and us.
The current design is just not maintainable, causing countless bugs.
In `v2.0` the deprecated backup tool is being removed because of this reason.
Please consider using SQL, API based[^1] or infrastructure based[^2] backup instead. 

New approaches to these features should use [SQLite dump](https://www.sqlitetutorial.net/sqlite-dump/) or [MariaDB dump](https://mariadb.com/kb/en/mariadb-dump/) respectively. (Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md))

You can subscribe to these issues meanwhile:
- #2496
- #477

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
[^2]: see https://github.com/louislam/uptime-kuma/issues/477#issuecomment-1557966187 for a setup example
