### ISSUE TITLE
Is there a way to export (or otherwise acquire) alert logs/history?

### ISSUE THREAD

**Issue by mrfuntime** [louislam/uptime-kuma#1653]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My DNS provider is having issues; I am going to raise the issue with them but I was hoping to include supporting alert history from UK.  However, it doesn't look like this functionality is available, or I cannot find it.

Can someone educate me on this, or if this is truly not available, can it be added in a future release?

Thanks
Mike

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

UnRaid 6.9.2 via Docker

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.5

**Comment by shley008** [comment]
I know it's not an 'ideal' solution, but you can use sqlite3 commands to pull info out of the DB directly to a csv file, now you will have to have a basic understanding of databases and sqlite3 (not terribly hard, just look up how to export to csv). Then copy the csv file off the container with the 'docker cp container-id_or_conatiner-name:/db/pathtocsv.csv /copiedcsv.csv' command.

I too would like a way to export the data straight from the web interface, I work with alot of local ISPs and my firewalls give them good data. Since I started with kuma, the only thing I'm missing IS the historical export, but using the database itself works okay. 

Remember, in all cases, you take the risk of running commands on your own database and wiping it out or corrupting it. As a general rule, if you follow the documentations for exporting to csv from sqlite there *shouldn't* be any issues, but again, attempt at your own risk.
