### ISSUE TITLE
Error notification : getaddrinfo EAI_AGAIN api.pushover.net

### ISSUE THREAD

**Issue by Dim3333** [louislam/uptime-kuma#1701]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Pushover notification is out. I obtain this message. Since the first version of Uptime, all was fine.
Now, I can't use it.

![image](https://user-images.githubusercontent.com/43283756/170802282-ba80f666-1b7a-4a92-89a7-98e7be8ce864.png)

### 👟 Reproduction steps

/

### 👀 Expected behavior

/

### 😓 Actual Behavior

/

### 🐻 Uptime-Kuma Version

1.16

### 💻 Operating System and Arch

/

### 🌐 Browser

/

### 🐋 Docker Version

/

### 🟩 NodeJS Version

/

**Comment by Computroniks** [comment]
It would be helpful if you could provide more details rather than just filling out the form with `/`. We can't help if we don't know what system your running and what was happening before you encountered the error. Please could you update the issue to at least include:
* what you were doing when the error occured
* your operating system
* your NodeJS version
It would also be helpful if you could copy any relevant log outputs

The error you are getting seems to relate to a failiure in DNS resolution. You might want to check that you can reslove the domain you are checking

**Comment by Computroniks** [comment]
#1697 is similar to this. You could try upgrading to 1.16.1 as I know that that works for docker at least

**Comment by Dim3333** [comment]
Thanks @Computroniks , the issue cames from my internet connexion. The issue is solved.
