### ISSUE TITLE
Search using IP Address

### ISSUE THREAD

**Issue by aaemon** [louislam/uptime-kuma#1722]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be very nice and helpful if IP address search is enabled. Currently only search by name is working.  

### ✔️ Solution

add IP address search

**Comment by ThomasChr** [comment]
The problem is that we don't have the IP for a monitor, we only have the URL.
Getting the IP for every monitor when searching through the list would be a pain, so I would suggest adding a new field 'last_ip' to the monitor table - or to the heartbeat table.

(Adding it to the monitor table would mean an extra update every time a monitor answers, adding it to the heartbeat table would mean adding it to the history of every answer of a monitor, and in the search function we have an additional database access to the heartbeat table => After all, there no such thing as free lunch.)

Any suggestions on how to proceed?

**Comment by aaemon** [comment]
yeah, I think using the tag would do the trick, thanks and tons of appreciation for this project ❤️
