### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#1801]
- [Bug List](https://github.com/louislam/uptime-kuma/issues?q=is%3Aopen+is%3Aissue+label%3Abug+sort%3Aupdated-desc)
- [Feature Requests](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Afeature-request+is%3Aopen)
- [Help](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+label%3Ahelp+sort%3Aupdated-desc)

**Comment by webysther** [comment]
Hey add to project to close a few similar issues I found.

**Comment by WanXdOffc** [comment]
Please make the next update public, you can register users, but use a limit, for example, 1000 people

**Comment by CommanderStorm** [comment]
@WanXdOffc please stick to the [templates laid out here](https://github.com/louislam/uptime-kuma/issues/new/choose). Otherwise, this number of issues is not manageable.

Your comment is also not clear in what you mean.
Please provide your reasoning in comments suggesting changes in the future.

Note that release planning happens in [projects](https://github.com/users/louislam/projects/4), [milestones](https://github.com/louislam/uptime-kuma/milestones) and [pull requests](https://github.com/louislam/uptime-kuma/pull/2720).
