### ISSUE TITLE
Can't re-order items on status page

### ISSUE THREAD

**Issue by nothsa** [louislam/uptime-kuma#1807]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Re-ordering items on the Status pages do not work on any of my desktop browsers (Chrome, Brave, Firefox, Edge). Clicking-and-dragging on any of the up/down arrow doesn't do anything. I have also tried in Incognito mode and with all extensions disabled on all of the browsers, but that didn't change anything.

I have also tried in the Chrome browser on my phone, and that **_does_** work.

Any ideas what might be causing this, or things that I could try?

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Synology DSM 7.1

### 🌐 Browser

Brave 1.39.122 [Chromium 102.0.5005.115] / Chrome 102.0.5005.115 / Firefox 101.0.1 / Edge 102.0.1245.30

### 🐋 Docker Version

Docker 20.10.3

**Comment by louislam** [comment]
It feels like an OS issue or mouse issue?

It is working fine in my side.

Also you can try the demo site: https://demo.uptime.kuma.pet/

**Comment by erlenddahl** [comment]
I have the same issue. Tested in Firefox, Chrome, Edge on Windows 10 and Windows 11. In all cases, the rows shake slightly when I press down on the drag arrow, but then nothing happens when I try to actually move them around. My uptime-kuma is running in docker on Ubuntu, but I have also tested on the demo site as advised in @louislam's comment above.

The web browser developer console reports no error messages. The inspector shows that when I click down on the arrow, the element's `draggable `property is set to true, and the class `sortable-chosen` is added. When I move the mouse, I can briefly see the `sortable-ghost` class being added as well, then it immediately returns to just the `item` class, and `draggable=false`, and nothing more happens.

In Chrome on Android it works, though. So I can work around this by using my phone whenever I need to re-arrange anything.
