### ISSUE TITLE
Twillo SMS Alerts

### ISSUE THREAD

**Issue by SecureCPU** [louislam/uptime-kuma#1860]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Receiving notification via SMS with Twilio

### ✔️ Solution

Add Twillo as a SMS option for Notifications

**Comment by phanxgames** [comment]
This would be awesome.

**Comment by netspear** [comment]
I opened a feature request for this.
If anyone else can vote on it, that would be great!!

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/392193

**Comment by krisdahl** [comment]
+1

**Comment by woj-tek** [comment]
Hmm... I'm on a latest Kuma and I see Twilio option so it seems it's already there?

However, I would like to add/ask option to log-in via API Key instead of using master AccountSID and AuthToken. See https://www.twilio.com/docs/usage/requests-to-twilio#creating-or-updating-resources-with-the-post-method

Basically one can either use `const client = require('twilio')(accountSid, authToken);` or `const client = require('twilio')(apiKey, apiSecret, { accountSid: accountSid });`, where the second one is more secure and thus recomended.

**Comment by CommanderStorm** [comment]
Any PR adding such functionality is likely to be added to master.
- please also go into detail what you mean by *"more secure and thus recommended"*
- The problem with the notification providers is, that they are for the most part untested/untestable.
   => Screenshots are needed to verify that this change works.

needed change (using curl, as imo this is more readable):
![image](https://github.com/louislam/uptime-kuma/assets/26258709/dabdb80c-3bf3-4e10-af4c-44fa51c79114)

**Comment by CommanderStorm** [comment]
@SecureCPU  given that this is in uptime kuma since #2980 (this issue was a duplicate => was missed in the autocloing), please close this issue 😅 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a00e9da7-5fe2-48d7-a74d-9707af55cb35)

**Comment by woj-tek** [comment]
@CommanderStorm considering this issue got closed I went with followup: https://github.com/louislam/uptime-kuma/issues/3204
