### ISSUE TITLE
Bug: "Certificate Expiry Notification" reset when restoring/importing monitors

### ISSUE THREAD

**Issue by rezzorix** [louislam/uptime-kuma#1897]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I recently moved my uptime-kuma from one machine to another.

So I backed up my monitors into a .json file on the old machine and then restored them again on the new machine.

I have switched off the "Certificate Expiry Notification" in most of my monitors.
However, when restoring, all monitors had this option activated.

I have checked the .json file - all data is correct exported.

When restoring the `expiryNotification": false` in the .json will be ignored and the default setting `expiryNotification": true` is used.

### 👟 Reproduction steps

Backup/Export a list of monitors through webinterface into .json
Import/Restor the .json file through webinterface

### 👀 Expected behavior

Backup/Export settings should match Restored/Imported settings.

### 😓 Actual Behavior

Backup/Export settings **do not** match Restored/Imported settings.

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

FF, Chrome, Edge

### 🐋 Docker Version

20.10.17

### 🟩 NodeJS Version

-

**Comment by chakflying** [comment]
Obsolete as the backup feature has been dropped in #3892.

**Comment by CommanderStorm** [comment]
Chiming in with a more in-depth explanation:

Please see https://github.com/louislam/uptime-kuma/issues/2141#issuecomment-1272360952

> In 1.18.3, the backup feature was deprecated due to [being left] unmaintained.

Backup & Restore with JSON has been deprecated and issues will not be fixed due to the amount of problems it has been causing for our users and us.
The current design is just not maintainable, causing countless bugs.
In `v2.0` the deprecated backup tool is being removed because of this reason.
Please consider using SQL, API based[^1] or infrastructure based[^2] backup instead. 

New approaches to these features should use [SQLite dump](https://www.sqlitetutorial.net/sqlite-dump/) or [MariaDB dump](https://mariadb.com/kb/en/mariadb-dump/) respectively. (Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md))

You can subscribe to these issues meanwhile:
- #2496
- #477

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
[^2]: see https://github.com/louislam/uptime-kuma/issues/477#issuecomment-1557966187 for a setup example
