### ISSUE TITLE
Create my own docker image from my fork

### ISSUE THREAD

**Issue by CreaCloudz** [louislam/uptime-kuma#1950]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I made a fork of your monitoring system I would like to make a docker image of my fork how is this possible? Thank you for your help.

### 🐻 Uptime-Kuma Version

Lastest Custom

### 💻 Operating System and Arch

 Ubuntu 22.04 LTS (GNU/Linux 5.15.0-41-generic x86_64)

### 🌐 Browser

Microsoft Edge

### 🐋 Docker Version

Latest

### 🟩 NodeJS Version

Latest

**Comment by AnnikenYT** [comment]
If you go to the /docker directory of the repository, you'll find a `dockerfile`.
From there, you can run `docker build` to build out the docker image, and then run it like every other image 😄

**Comment by CreaCloudz** [comment]
> If you go to the /docker directory of the repository, you'll find a `dockerfile`. From there, you can run `docker build` to build out the docker image, and then run it like every other image 😄

![image](https://user-images.githubusercontent.com/12797827/181514263-673177d3-8b87-414e-8179-071a14eacd4a.png)

**Comment by louislam** [comment]
Please check these commands:

https://github.com/louislam/uptime-kuma/blob/df7f0b078db12c011286389ae1867f8aa2d8f095/package.json#L33-L37

**Comment by CreaCloudz** [comment]
it doesn't help me much..

**Comment by AnnikenYT** [comment]
> it doesn't help me much..
Didn't see these, try `npm run build-docker` or `yarn build-docker`.

**Comment by satyamsettyeswara** [comment]
Hi,
i've been trying to build docker image locally. after solving lot of issues I ended up here
![image](https://user-images.githubusercontent.com/31738585/188938513-ea3471f3-9b9a-4471-8f2e-43f73174ff27.png)
Do we have any procedure or docs for this?

Can someone help me here?

**Comment by louislam** [comment]
> Hi, i've been trying to build docker image locally. after solving lot of issues I ended up here ![image](https://user-images.githubusercontent.com/31738585/188938513-ea3471f3-9b9a-4471-8f2e-43f73174ff27.png) Do we have any procedure or docs for this?
> 
> Can someone help me here?

You need to set the environment variable `VERSION`.

Alternatively, you can edit `package.json` and change the name `louislam/uptime-kuma:$VERSION` to whatever you want.

**Comment by satyamsettyeswara** [comment]
Yay!!!!🐱‍🏍
@louislam I was finally able to create the docker image in my local system. These are things I've done to create it.

1. Created a file with name TestDockerfile
2. Paste below content in the created file
  
  ```
    FROM node:18-alpine AS build 
    WORKDIR /app
    COPY package.json .
    ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true 
    COPY . .
    RUN npm ci --production && \
    chmod +x /app/extra/entrypoint.sh
    EXPOSE 3001
    VOLUME ["/app/data"]
    HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD node extra/healthcheck.js
    CMD ["node", "server/server.js"]
```

3. Image create command
    This is specific for windows machine. For other OS you have to change platform
    `docker build -f docker/TestDockerfile --platform linux/amd64 -t kuma/uptime-kuma .`
4. Run the docker image to run the container
     `docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma kuma/uptime-kuma`
5. Open your browser and type
     http://localhost:3001/

     **voilà There you have it** 

Not sure if it might have any issues(if you think it causes any problems please update here). since I remove 1 or 2 lines from the actual dockerfile.
But as of  now I was able to create my own image to test my changes

**Comment by satyamsettyeswara** [comment]
Hi @louislam,
I was able to create the docker image in my local system by updating the package.json with
` "build-docker-debian": "node ./extra/env2arg.js docker buildx build -f docker/dockerfile --platform linux/amd64 -t kuma/uptime-kuma . --load"`

But there is one problem, my changes are not reflecting in the newly created image. Could you provide some help??

**Comment by satyamsettyeswara** [comment]
Hi, I was finally able to figure out. How to built a docker images in my local system.

**Solution:**
1. Run `npm run build-dist-and-restart` which builds the dist.
2. Next Comment from line 24 to the end in the docker/dockerfile (why? because I don't have permission to upload to github the artifacts) and save it.
3. Update `build-docker-debian` command in package.json to `"build-docker-debian": "node ./extra/env2arg.js docker buildx build -f docker/dockerfile --platform linux/amd64 -t kuma/uptime-kuma . --load"`(this is for windows for others you have to update the platform tag).
4. Now run `npm run build-docker-debian` it creates the docker image with our changes.
5. Next you can run the command that creates the container `docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma kuma/uptime-kuma`

voilà there you have it.🥳

@louislam Please comment if there were any mistakes

**Comment by Joseph94m** [comment]
@satyamsettyeswara 's hack worked for me, but it seems like there should be a simpler way.

**Comment by satyamsettyeswara** [comment]
@Joseph94m I do think the same. after a while i was able to deduce the commands to this

Solution:
1. Add new command to your package.json file
   command: `"build-myimage": "npm run build && node ./extra/env2arg.js docker buildx build -f docker/dockerfile --platform linux/amd64 -t kuma/uptime-kuma . --load"`
package.json should look like this
![image](https://user-images.githubusercontent.com/31738585/190846981-2badc80c-8426-42d8-8645-8e78e0d46283.png)
2. Next run this command to create you own image
`npm run build-myimage`

/cheers
