### ISSUE TITLE
Imports for `docker-container` monitors are not correctly restored.

### ISSUE THREAD

**Issue by mmuenker** [louislam/uptime-kuma#2015]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

 The `container-name` and the selected `docker host` is not restored but empty.

> The properties `container-name` and `docker host` are correctly exported and appear in the JSON file.

### 👟 Reproduction steps

Create `docker-container` monitor and create a backup. Then import the backup (with overwrite)

### 👀 Expected behavior

The `docker-container` monitor is restored with the `container-name` and `docker host`.

### 😓 Actual Behavior

The restored `docker-container` monitor has empty `container-name` and `docker host` inputs.

### 🐻 Uptime-Kuma Version

1.18.0-beta.0

### 💻 Operating System and Arch

Ubuntu 22.04 amd64

### 🌐 Browser

Chromium 104.0.5112.101

### 🐋 Docker Version

Docker 20.10.17

**Comment by chakflying** [comment]
Obsolete as the backup feature has been dropped in #3892.

**Comment by CommanderStorm** [comment]
Chiming in with a more in-depth explanation:

Please see https://github.com/louislam/uptime-kuma/issues/2141#issuecomment-1272360952

> In 1.18.3, the backup feature was deprecated due to [being left] unmaintained.

Backup & Restore with JSON has been deprecated and issues will not be fixed due to the amount of problems it has been causing for our users and us.
The current design is just not maintainable, causing countless bugs.
In `v2.0` the deprecated backup tool is being removed because of this reason.
Please consider using SQL, API based[^1] or infrastructure based[^2] backup instead. 

New approaches to these features should use [SQLite dump](https://www.sqlitetutorial.net/sqlite-dump/) or [MariaDB dump](https://mariadb.com/kb/en/mariadb-dump/) respectively. (Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md))

You can subscribe to these issues meanwhile:
- #2496
- #477

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
[^2]: see https://github.com/louislam/uptime-kuma/issues/477#issuecomment-1557966187 for a setup example
