### ISSUE TITLE
After 1.18 update many website are reported as being down with code 503, however they are up

### ISSUE THREAD

**Issue by vadikcoma** [louislam/uptime-kuma#2054]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

There are no particular steps to trigger the bug. We updated Kuma to 1.18 and 11 sites out of 150+ reported as being down. 

Request failed with status code 503

I tried pausing and enabling again, but no luck

### 👀 Expected behavior

Site should display as UP

### 😓 Actual Behavior

Shows sites as DOWN

### 🐻 Uptime-Kuma Version

1.18

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome, 104.0.5112.102

**Comment by louislam** [comment]
Error 5XX is usually returning from the web server, could you the web server log?

**Comment by zeroav-org** [comment]
We have also observed this with sites that are behind cloudflare WAF. Immediately after updading to 1.18.0 we get 503. 

The issue is not an Uptime Kuma issue. The issue is that Cloudflare's Super Bot Fighting Mode seems unaware of the new user-agent string or some other metric/behavior that has changed with the 1.17.1 -> 1.18.0 update.

We have a ticket open with Cloudflare but this is going nowhere unless you have an Enterprise account. We have business tier and they don't really care. I suggest @vadikcoma confirm you are using a WAF of any kind on these monitored endpoints ? 

![Screenshot2-D](https://user-images.githubusercontent.com/84272417/189265230-0835576f-48dd-4ad3-b618-60b927fb0917.png)

Maybe related to #1333 ?

**Comment by louislam** [comment]
My guess is after the instance updated, all monitors immediately make requests to all websites in a short period. Then Cloudflare mark this as a bad behavior.

I think you can avoid this by whitelisting your Uptime Kuma's IP in Cloudflare. As the `IP Access Rule` is before `Bots Rule`


![image](https://user-images.githubusercontent.com/1336778/189293251-b3da22b8-431a-49fe-be8c-7e13583b6c6d.png)

**Comment by zeroav-org** [comment]
That's a plausible scenario for why it's being blocked after upgrading. The user-agent alone is not meaningful.

But Super Bot Detection is always on and customer cannot make exclusions unless on Enterprise Tier.

![Screenshot 2022-09-09](https://user-images.githubusercontent.com/84272417/189295985-53ae6cc3-a7ed-40b1-a75b-cfb8e917babe.png)

They claim we can apply for whitelisting but being that we are self-hosted this won't be bullet-proof. For SaaS they go by ASN or IP prefix. In Uptime Kuma's case it would be AI based and still have the occasional false positive. I filed there in #2058 in case you want to give it a try.

**Comment by vadikcoma** [comment]
Yes, I can confirm that we are using CloudFlare and most of the sites with 503 have Bot Fighting Mode enabled

**Comment by louislam** [comment]
So let's follow up in https://github.com/louislam/uptime-kuma/issues/2058.
