### ISSUE TITLE
Documentation on how to setup docker container monitor

### ISSUE THREAD

**Issue by joerich** [louislam/uptime-kuma#2093]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Documentation on how to setup docker container monitor

### 🐻 Uptime-Kuma Version

Version: 1.18.0

### 💻 Operating System and Arch

Ubuntu 14.0

### 🌐 Browser

Chrome is up to date Version 105.0.5195.127

**Comment by rezzorix** [comment]
@c0derMo is the main contributor of this option, maybe can he help out? 

Aside from this @joerich it might be useful to know how docker daemons work.
Therefore here the link to docker documenation: https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by ChipSkylark37** [comment]
Do you have any tips on how to configure Docker monitoring for a Synology Docker setup? I don't believe it exposes a website / TCP port by default and I cannot find documentation on this.

**Comment by joerich** [comment]
> 



> c0derMo
My issue is that I have docker running on my TerraMaster NAS, I've tried using the command you set forth 
"-v /var/run/docker.sock:/var/run/docker.sock" didn't work. When I login via SSH I can see the directory  "/var/run/" and the 
 file "docker.sock" I don't understand what the problem is.

I love this software and would really like to use the docker monitors

On my NAS, Docker was through the TerraMaster control panel Portainer was also.
Everything installed in docker works great.

do I need to open a tcp port for docker and config it that way?

thanks in advance for your help!

**Comment by c0derMo** [comment]
I cant give accurate advice for any of these systems, since I'm not familiar with them.

If you are trying to monitor the docker environment where Uptime Kuma also runs on, chances are high you can access the local docker socket at `/var/run/docker.sock`, binding it to the container as written above.

**Comment by ChipSkylark37** [comment]
That doesn't seem to work for Synology, but I'll try a few different things and see if I can get something to work.

**Comment by rezzorix** [comment]
I understand there are use cases for monitoring the container is up or down instead of monitoring the service (e.g. monitoring wireguard/UDP would be such a case).

So it really depends on the type of service one runs.
It also depends if the uptime-kuma instance is running within same network or not.

In most cases I bet it would be easiest to just setup TCP or HTTP(s) monitors.
If not accessible from the outside world, but with (outgoing) network access, then in "Upside Down Mode".
Also there are heaps of possibilities to access internal services with the different authentication and/or proxy options.

My question regarding dockerd or here uptime-kuma docker monitor... does it return health status of the container?
A docker container status could be "active" but be unhealthy... I didnt find it on first glance in the docs.

**Comment by c0derMo** [comment]
@rezzorix Currently, the monitor does not look at a container's health, just whether it's running or not, since I found it difficult to say generally, that a monitor should count as "down" when it's container is unhealthy... maybe adding a checkbox to the monitor for this purpose would help?

**Comment by rezzorix** [comment]
> @rezzorix Currently, the monitor does not look at a container's health, just whether it's running or not, since I found it difficult to say generally, that a monitor should count as "down" when it's container is unhealthy... maybe adding a checkbox to the monitor for this purpose would help?

Yeah it might help, however, to be honest, I personally think checking docker containers status is easier/quicker to implement via any of  the other monitor options... (except for UDP services of course).

**Comment by ewoks** [comment]
@ChipSkylark37 did you find a way to expose docker.socket of remote Synology via TCP/HTTP(s) so Uptime-Kuma can use it for monitoring non local docker host?

**Comment by ChipSkylark37** [comment]
> @ChipSkylark37 did you find a way to expose docker.socket of remote Synology via TCP/HTTP(s) so Uptime-Kuma can use it for monitoring non local docker host?

No, I gave up he instead just monitor the services hosted by the docker.

**Comment by federicotravaini** [comment]
Hello, I tried to modify `/var/packages/ContainerManager/etc/dockerd.json` adding `{ "hosts" : [ "tcp://192.168.200.19:2375", "unix:///var/run/docker.sock" ], "registry-mirrors" : [] }` but after docker restart the added line gets removed. Did anyone find a solution?

**Comment by CommanderStorm** [comment]
we have adjusted closing `help`-issues a lot.
The comment you are refering to is from 2022..

https://github.com/louislam/uptime-kuma/blob/be2faf64ce8973d49d6c4b29dacdedbffc57855e/.github/workflows/stale-bot.yml#L15-L18

**Comment by CommanderStorm** [comment]
given the quality of help requests we get and the resources I have for support, autoclosing is what we need to keep up.
