### ISSUE TITLE
Support persisting cookies set during Redirects

### ISSUE THREAD

**Issue by GedasBu** [louislam/uptime-kuma#2292]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,
I'm trying to monitor jackett instance which is running on windows vm in proxmox. Uptime-Kuma cannot detect it while I can open jackett web interface with no problem in chrome. My local path is http://192.168.1.36:9117/UI/Dashboard.
Maybe someone has experience with it? 

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Lroxmox lxc container

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
> Operating System and Arch
lxc container

Usually it is a network issue. Did you allow your Uptime Kuma LXC container to access your LAN (192.168.1.X)?

https://github.com/lxc/lxd/issues/1343

**Comment by GedasBu** [comment]
I have Radarr, plex, and sonarr  on the same Vm and its working fine with Kuma. Only Jackett refuses to work.

**Comment by MrBlue90** [comment]
I experience the same issue.
A normal ping works, but checking the webpage doesn't.

**Comment by IRHM** [comment]
For anyone having this issue, I was able to fix it by disabling redirects and adding the 302 (Found) http status code to the monitor for jackett:
![image](https://user-images.githubusercontent.com/37304121/213007840-e64bd6eb-353b-4829-b2b3-65bcfaa49115.png)

**Comment by GedasBu** [comment]
Thanks. That worked for me also.

**Comment by louislam** [comment]
> For anyone having this issue, I was able to fix it by disabling redirects and adding the 302 (Found) http status code to the monitor for jackett: ![image](https://user-images.githubusercontent.com/37304121/213007840-e64bd6eb-353b-4829-b2b3-65bcfaa49115.png)

Do you know the reason? As normally, Uptime Kuma will follow redirects to the final page.

**Comment by IRHM** [comment]
> Do you know the reason? As normally, Uptime Kuma will follow redirects to the final page.

Not 100% sure but it looks like Jacketts web server is setup weirdly.

Found this issue, could be why (uptime-kume gets redirected to login, but doesnt save cookie, goes back to dashboard, then because no cookie, back to login, infinite loop? Not even sure if kuma supports cookies, so I could be wrong): https://github.com/Jackett/Jackett/issues/12475#issuecomment-954224293

**Comment by pkishino** [comment]
Having the same problem as above..
jackett setup on baremetal.. neither accessing through reverse nginx nor directly is working with uptime Kuma, even after trying above tips..

**Comment by pkishino** [comment]
This is still an issue

**Comment by CommanderStorm** [comment]
@pkishino
This issue has been closed because it was raised with the `help` tag.

Please open an issue with more details than the current issue.
If you decide to do so please attach this information:
- Currently there sadly is no way this is reproducible what the response of `jackett` to the inital ping is. => include how jackett redirects
- what cookies it sets

**Comment by CommanderStorm** [comment]
I used https://hub.docker.com/r/linuxserver/jackett/ and getting curl to cooperate was a bit harder:

```bash
curl -v --cookie-jar -b cookiefile --junk-session-cookies --location http://localhost:9117
``` 

<details><summary>Resulting log</summary>
<p>

```log
* Host localhost:9117 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:9117...
* Connected to localhost (::1) port 9117
> GET / HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Date: Tue, 07 May 2024 18:40:36 GMT
< Server: Kestrel
< Location: /UI/Dashboard
< 
* Ignoring the response-body
* Connection #1 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/Dashboard'
* Found bundle for host: 0x5593ad409ea0 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection with host localhost
> GET /UI/Dashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Content-Length: 0
< Date: Tue, 07 May 2024 18:40:36 GMT
< Server: Kestrel
< Location: http://localhost:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard
< 
* Ignoring the response-body
* Connection #1 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard'
* Found bundle for host: 0x5593ad409ea0 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection with host localhost
> GET /UI/Login?ReturnUrl=%2FUI%2FDashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Content-Length: 0
< Date: Tue, 07 May 2024 18:40:36 GMT
< Server: Kestrel
< Cache-Control: no-store,no-cache
< Location: TestCookie
< Pragma: no-cache
* Added cookie TestCookie="1" for domain localhost, path /, expire 0
< Set-Cookie: TestCookie=1; path=/
< 
* Ignoring the response-body
* Connection #1 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/TestCookie'
* Found bundle for host: 0x5593ad409ea0 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection with host localhost
> GET /UI/TestCookie HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/8.6.0
> Accept: */*
> Cookie: TestCookie=1
> 
< HTTP/1.1 302 Found
< Content-Length: 0
< Date: Tue, 07 May 2024 18:40:36 GMT
< Server: Kestrel
< Cache-Control: no-store,no-cache
< Location: Login?cookiesChecked=1
< Pragma: no-cache
< 
* Ignoring the response-body
* Connection #1 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/Login?cookiesChecked=1'
* Found bundle for host: 0x5593ad409ea0 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection with host localhost
> GET /UI/Login?cookiesChecked=1 HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/8.6.0
> Accept: */*
> Cookie: TestCookie=1
> 
< HTTP/1.1 302 Found
< Content-Length: 0
< Date: Tue, 07 May 2024 18:40:36 GMT
< Server: Kestrel
< Cache-Control: no-cache,no-store
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: Dashboard
< Pragma: no-cache
* Added cookie Jackett="CfDJ8KRxCoQqb95MnzVHT7NPkrhBWPC9s_3rW_h8K7jkpvmbbapBmeVF5G-kYvyPVMb36bWxVxX1nnrxqLaJD3w5w9xCBVmT4y3XBdYc7YIn0cO-c4j15e_IwYx1gYEpohNlMMvAzjLp2JSTgdQhvN_6XcbVDj6wQ1gtNTA0PxVhiqvmskmgbKJG_kZ9jcdu2OD3-OQnQIBaVaUQIGvuk-M-VGAPFngNxNwFN5r0H-03Fe5X4MYUUGyOcOWsdurSme9_WfsrszeM4UqE5yp49zdBr30aHhBL2ICAJByy1W8iywgnC6JGgvdYkiHgCC3Z6dU2LuoUwp7p_V0nZlgU4-QD3Tc" for domain localhost, path /, expire 1716316837
< Set-Cookie: Jackett=CfDJ8KRxCoQqb95MnzVHT7NPkrhBWPC9s_3rW_h8K7jkpvmbbapBmeVF5G-kYvyPVMb36bWxVxX1nnrxqLaJD3w5w9xCBVmT4y3XBdYc7YIn0cO-c4j15e_IwYx1gYEpohNlMMvAzjLp2JSTgdQhvN_6XcbVDj6wQ1gtNTA0PxVhiqvmskmgbKJG_kZ9jcdu2OD3-OQnQIBaVaUQIGvuk-M-VGAPFngNxNwFN5r0H-03Fe5X4MYUUGyOcOWsdurSme9_WfsrszeM4UqE5yp49zdBr30aHhBL2ICAJByy1W8iywgnC6JGgvdYkiHgCC3Z6dU2LuoUwp7p_V0nZlgU4-QD3Tc; expires=Tue, 21 May 2024 18:40:37 GMT; path=/; samesite=lax; httponly
< 
* Ignoring the response-body
* Connection #1 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/Dashboard'
* Found bundle for host: 0x5593ad409ea0 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection with host localhost
> GET /UI/Dashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/8.6.0
> Accept: */*
> Cookie: TestCookie=1; Jackett=CfDJ8KRxCoQqb95MnzVHT7NPkrhBWPC9s_3rW_h8K7jkpvmbbapBmeVF5G-kYvyPVMb36bWxVxX1nnrxqLaJD3w5w9xCBVmT4y3XBdYc7YIn0cO-c4j15e_IwYx1gYEpohNlMMvAzjLp2JSTgdQhvN_6XcbVDj6wQ1gtNTA0PxVhiqvmskmgbKJG_kZ9jcdu2OD3-OQnQIBaVaUQIGvuk-M-VGAPFngNxNwFN5r0H-03Fe5X4MYUUGyOcOWsdurSme9_WfsrszeM4UqE5yp49zdBr30aHhBL2ICAJByy1W8iywgnC6JGgvdYkiHgCC3Z6dU2LuoUwp7p_V0nZlgU4-QD3Tc
> 
< HTTP/1.1 200 OK
< Content-Length: 44176
< Content-Type: text/html
< Date: Tue, 07 May 2024 18:40:36 GMT
< Server: Kestrel
< Cache-Control: no-store,no-cache
< Last-Modified: Tue, 07 May 2024 05:58:38 GMT
< Pragma: no-cache
< 
<!DOCTYPE html>
```

</p>
</details> 

<details><summary>Extracted request flow</summary>
<p>

- `GET /`
- => `301` to `Location`=`/UI/Dashboard`
- `GET /UI/Dashboard`
- => `302` to `Location`=`/UI/Login?ReturnUrl=%2FUI%2FDashboard`
- `GET /UI/Login?ReturnUrl=%2FUI%2FDashboard`
- => `302` to `Location`=`TestCookie` with `Set-Cookie`=`TestCookie=1; path=/`
- `GET /UI/TestCookie` with `Cookie`=`TestCookie=1`
- => `302` to `Location`=`Dashboard` with `Set-Cookie`=`Jackett=Cf...D3Tc; expires=Tue, 21 May 2024 18:40:37 GMT; path=/; samesite=lax; httponly`
- `GET /UI/Dashboard` with `Cookie`=`TestCookie=1;Jackett=Cf...D3Tc`
- => `200` with html

</p>
</details> 

So the real request flow is super weird.
Please use an api endpoint instead to monitor the health such as `GET /health` mentioned in https://github.com/Jackett/Jackett/issues/12784#issuecomment-1008434003

Persising cookies during rediects is already tracked in https://github.com/louislam/uptime-kuma/issues/2309 => re-closing as resolved (due to `/health`)

**Comment by Zamana** [comment]
> I have the same issue. Adding `302` response didn't work. (...)

You need to set Redirects to "0" (zero) too.
