### ISSUE TITLE
Data loss after upgrade

### ISSUE THREAD

**Issue by sistein** [louislam/uptime-kuma#2294]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Today I upgraded from 1.17.1 to 1.18.5 .

Since I also updated other packages and stuff I restarted my server as well. 
It ended as such that "pm2 restart uptime-kuma" did not work. I changed to "pm2 start uptime-kuma" which worked - but after the start I was presented the "create new user" screen and all data vanished from the web-ui. 

There are several backupfiles:
![grafik](https://user-images.githubusercontent.com/13909466/200189207-1f1dcfb9-565a-4385-bcd9-14c4f5cf82c0.png)

How may I get use of of one of the backupfiles? 

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Debian

### 🌐 Browser

Vivaldi 

### 🐋 Docker Version

-

### 🟩 NodeJS Version

8.19.3

**Comment by louislam** [comment]
>NodeJS Version 8.19.3
Are you sure? As because Uptime Kuma never supported and can never be started on Node.js <= 13 or 12. Node.js 8 is probably too old.
Did you downgrade Node.js?

Second, the backup file named with this format: `*.bak<datetime>`

To restore the backup (Copy is recommanded)
kuma.db.bak1234567890 => kuma.db
kuma.db-wal.bak1234567890 to => kuma.db-wal
kuma.db-shm.bak1234567890 to => kuma.db-shm

But as I can see, your last backup is 2022-09-03. The recent backup is not existing too. You should find the reason why data loss first, e.g. disk space.

**Comment by mikolajek-fr** [comment]
Same problem here, Uptime Kuma 1.17.1 => 1.18.5 with Debian 11 / NodeJS 14.20.0 and all data lost : screen to register, all monitors disappeared. No problem with previous upgrades.

But there's only 478 MB free on /, maybe it's not enough?
