### ISSUE TITLE
Manual Actknowledge/Silence Option

### ISSUE THREAD

**Issue by BucketCDT** [louislam/uptime-kuma#2397]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

If I am aware of a issue or if I know a issue will happen. I would like a way to Silence or Acknowledge a alarm temporarily instead of full on stopping the recording/Alerting of such program "Pausing"  for a much more less invasive way.

### ✔️ Solution

I would like a manual user option to silence/acknowledge a alarm so it will no longer notify of the issue but will unsilence when the issue is cleared or is okay.

**Comment by Schwoby** [comment]
I personally use the Maintenance feature for this. there is an "Active/Inactive Manually" method that can be used that if you have an issue, you can enable the maintenance, fix your issue, turn maintenance off, monitoring still happens. please correct me if i am wrong here, but i believe the logs of the monitor will still keep the Up/Down record even though the dashbaord and any status pages with the monitor will reflect as under maintenance.

i use this method for when i must fix an issue that randomly happens with a website of mine. the fix is simple, but i don't want the alert that the service is back up. when i go to fix the issue, i turn on maintenance, and fix the issue. after the dashbaord reports the monitor in maint mode & i've fixed the issue, i pause the maint mode and next cycle, it goes from maint to up and i do not get any notification from it.

**Comment by CommanderStorm** [comment]
@BucketCDT I think your feature is already solved by the maintenance mode.
Could you please clarify why your issue is different from the existing functionality, or close this issue? (only you or louis can close issues…)

**Comment by BucketCDT** [comment]
I understand that maintenance mode has a one time feature, but I am talking about a feature that temporary mutes the service until the service is up, **simply** by pressing a button, like pressing the pause button, I understand that pause is an another option, but sometimes I forget to unpause it. I don't know, maybe this is useless but it would be nice to see for myself. Hope this clarifies?

**Comment by CommanderStorm** [comment]
> I am talking about a feature that temporary mutes the service until the service is up, **simply** by pressing a button, like pressing the pause button, 

Assuming your service is goes down, you will not recieve any additional notifications until it is back online again unless you have set up `Resend Notification if Down X times consecutively` for said monitor

> I understand that pause is an another option, but sometimes I forget to unpause it. I don't know, maybe this is useless but it would be nice to see for myself. Hope this clarifies?

So basically, what you are asking is a "Pause for X minutes".
In this case, I would argue that this is better tracked in https://github.com/louislam/uptime-kuma/issues/3372 (title and description being clearer)

Another likely duplicate could be https://github.com/louislam/uptime-kuma/issues/2984

**Comment by chakflying** [comment]
Closing this in favor of #2397 since that has more details.
