### ISSUE TITLE
Valid certificate verification fails (letsencrypt? wildcard?)

### ISSUE THREAD

**Issue by FinalDoom** [louislam/uptime-kuma#240]
Certificate verification fails for my hosts with the message in the UI:
> [HOST] [DOWN] Unable to verify the first certificate

The message in logs via portainer indicates:
> Cannot destructure property 'valid_from' of 'res.request.res.socket.getPeerCertificate(...)' as it is null.

Using latest docker version. The hosts in question are using a valid LetsEncrypt wildcard certificate.
Its validity is shown via openssl and firefox etc. as:
>        Validity
>            Not Before: Aug 13 08:16:32 2021 GMT
>            Not After : Nov 11 08:16:30 2021 GMT

**Comment by chakflying** [comment]
The error message indicates that `getPeerCertificate()` returned null, which according to the [documentation](https://nodejs.org/api/tls.html#tls_tlssocket_getpeercertificate_detailed) only happens if the TLS socket is destroyed. Currently the code should have very little delay between receiving the response and reading the certificate, so this should not be an issue. Are you experiencing high CPU load, or does your host have `HTTP Keep Alive` disabled or something like that?

**Comment by louislam** [comment]
Duplicate with https://github.com/louislam/uptime-kuma/issues/90

Your misconfigured let's encrypted without ca.

**Comment by FinalDoom** [comment]
Most things don't seem to require the fullchain since LE is a generally trusted CA, but that does fix it. Thanks.
