### ISSUE TITLE
No time zone notification

### ISSUE THREAD

**Issue by jhonny-v46** [louislam/uptime-kuma#2420]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Notifications that are sent by kuma to any channel do not respect the time zone defined in the frontend. Example: (UTC-03:00) America/Sao Paulo
![image](https://user-images.githubusercontent.com/86072047/207899065-05d99154-bc17-473c-a224-c9d530176250.png)
![image](https://user-images.githubusercontent.com/86072047/207899116-520aeab3-6523-4861-9858-4b4340a66f66.png)

### ✔️ Solution

Include in notifications the time zone of each country/city

### ❓ Alternatives

Include in notifications the time zone of each country/city

**Comment by ljara2106** [comment]
I agree - this needs to be fixed.

**Comment by CommanderStorm** [comment]
@jhonny-v46 This has been fixed in the https://github.com/louislam/uptime-kuma/releases/tag/1.22.0 Release  by https://github.com/louislam/uptime-kuma/pull/3203 and https://github.com/louislam/uptime-kuma/pull/3152

I missed this issue when linking them to the second PR.
=> Could you close this issue as it has been resolved?
(only you or Louis can do so)

**Comment by CommanderStorm** [comment]
Closing as resolved in the [`1.22.0`-release](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0) by https://github.com/louislam/uptime-kuma/pull/3203 and https://github.com/louislam/uptime-kuma/pull/3152
