### ISSUE TITLE
Release docker images on ghcr registry

### ISSUE THREAD

**Issue by ksurl** [louislam/uptime-kuma#2464]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Consider release of the docker images on the github container registry as an alternative/backup to docker hub due to free/anonymous account pull limits

### ✔️ Solution

tag new builds with ghcr.io/louislam/uptime-kuma in addition to the existing implicit docker.io tag and push to ghcr.

**Comment by pascaliske** [comment]
This is an easy feature! Also would be awesome if builds / pushes could be automated using GitHub Actions or some other CI provider...

**Comment by ksurl** [comment]
Is this planned for future releases or can this issue be closed?

**Comment by CommanderStorm** [comment]
This issue is a duplicate of #53.
Please refrain from posting duplicates, as this just makes issue managemnt harder.

See https://github.com/louislam/uptime-kuma/pull/213.
Louis is not keen on this

⇒ Given that he is the BDFL and the only maintainer (see https://github.com/louislam/uptime-kuma/pull/1349), this likely won't happen.

**Comment by ksurl** [comment]
Fair enough but it was not marked as dupe 6 months ago. I'll go ahead and close this.
