### ISSUE TITLE
Can't click on 'Add' when creating Tags

### ISSUE THREAD

**Issue by Meeeeez** [louislam/uptime-kuma#2482]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The User can't click on the 'Add' button when they click on the 'Add New below or Select' field after entering a tag name that already exists in the 'Name' field.

### 👟 Reproduction steps

1. Create a Tag by entering a name and a color

<img width="413" alt="image" src="https://user-images.githubusercontent.com/64471262/209673629-4fd20a9f-c859-46f7-ac17-1d96b671b4f4.png">

2. Click on 'Add' to create a new Tag

3. Enter the same name as before

<img width="414" alt="image" src="https://user-images.githubusercontent.com/64471262/209673739-b3a0004b-673c-467f-939a-1aea52371e2a.png">

5. Now click on 'Add New below or Select' and select the Tag you created in step 1

<img width="414" alt="image" src="https://user-images.githubusercontent.com/64471262/209673877-455a29ad-37dd-4245-b77f-05c53dbffc56.png">

**The 'Add' button can't be clicked anymore**

### 👀 Expected behavior

The selected tag is assigned to the monitoring.

### 😓 Actual Behavior

The Button no longer works.

### 🐻 Uptime-Kuma Version

1.19.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome 108.0.5359.125

**Comment by jeden92** [comment]
**Issue Replicated**

🐻 Uptime-Kuma Version

1.19.0-beta.2

💻 Operating System

macOS 10.13

🌐 Browser
Firefox 108.0.1

🐋 Docker Version
4.15.0 (93002)

Issue appears to occur when the text for "Tag Name" is left entered into the form, (with error saying tage exists seen in step 3 above).  Deleting the name from the form before selecting already created tag from drop down, returns "Add button" to normal behaviour

Is it possible to add a behaviour that auto removes the tag name text from the field if the same tag is selected from the drop down after the user has already typed the tag name. or does the form need to ignore the data entered in order to save the already created tag?
