### ISSUE TITLE
Authentik: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by rcdailey** [louislam/uptime-kuma#2557]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Lately, I have been getting the below errors for my status check for Authentik:
![image](https://user-images.githubusercontent.com/1768054/211019428-f727b4f1-c2bf-498d-8571-facb06678c45.png)

I have it set up with HTTP like so:
![image](https://user-images.githubusercontent.com/1768054/211019616-9523f6d1-cb6e-434d-8964-f20767567e93.png)

In my case, I am referring to Authentik using the docker bridge URL. I also use the docker DNS name. This works for literally every other service I have running in a docker container, so I am not sure what makes Authentik special other than the fact it is using HTTPS instead of HTTP. However, I am using the same URL that my reverse proxy is using to forward external requests to Authentik.

Can you think of any reason why this stopped working just a few days ago?

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Microsoft Edge

### 🐋 Docker Version

Unraid's version

### 🟩 NodeJS Version

N/A

**Comment by spali** [comment]
As I have authentik too, I tested it on my side.
I use docker compose, so my name resolution is using the service name of the container. In my case this is `authentik-server`.
Even I use http port 9000 docker internal I tested with https on 9443.
Results below.

I think it's docker network related problem... did you check they are in the same docker network and authentik is known on this docker network with this name?
The simplest to test this is usually is to attach to the source container shell and start with a host lookup, followed by a ping and curl test to the target container.
Not tested it with uptime-kuma, but If you miss a utility to test, clone the exact docker definition of uptime-kuma especially the network stuff but use a ubuntu image or anything that contains this utilities.

But it must be something you have changed on authentik, uptime-kuma or docker side since last time it worked.

**Results:**

![image](https://user-images.githubusercontent.com/1839708/213682742-f0eb72db-83de-4313-8aab-85dbeb17517f.png)
![image](https://user-images.githubusercontent.com/1839708/213682809-7cfb075e-cb70-4f07-beee-201d00f7e9e4.png)

**Comment by rcdailey** [comment]
Thank you for helping verify the issue @spali. Conveniently, I'm not seeing the issue anymore after you tested. Weird coincidence... I'm pretty convinced I didn't have a network issue since I have 20+ other services that work fine and status checks work fine for. I'll close this as a phantom issue I guess. If it returns I'll be sure to let you know.

**Comment by burakksglu** [comment]
We also have this issue. It comes and goes for some of the sites we have. The difference is, we have them on another location. So we are not using docker network or service names.
