### ISSUE TITLE
Add `givenPortOnly` config for GameDig monitor

### ISSUE THREAD

**Issue by shadowgamingyt** [louislam/uptime-kuma#2887]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

some of my servers work loading the up time etc but ones that i am using gamedig to access the servers uptime directly it does not work at all and just says its offline constantly 
![image](https://user-images.githubusercontent.com/27635401/222970219-7de913ac-7ce6-4ab1-b088-8b6ddef0e3a9.png)

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

22.04.2 LTS

### 🌐 Browser

edge

**Comment by fletchowns** [comment]
I was having a similar issue with my gamedig monitors. I thought it was related to my firewall rules restricting access to these game servers, meaning that uptime-kuma running in a container on the same server wasn't able to access it. That doesn't seem to be the case though.

As a test, I tried to manually install gamedig in my uptime-kuma container using `npm install gamedig`, and I'm able to successfully query my game servers:
```
uptime-kuma@36af169156a9:~$ ./node_modules/.bin/gamedig --type dayz dayz.my-docker-network:2302
{"name":"My DayZ Server...
uptime-kuma@36af169156a9:~$ ./node_modules/.bin/gamedig --type valheim valheim.my-docker-network:2456
{"name":"My Valheim Server...
```

However the equivalent config through uptime-kuma doesn't seem to work:
![image](https://user-images.githubusercontent.com/153107/223352138-e0bdf73f-da6c-47b1-8784-c809f0ad727d.png)

Didn't find anything revealing in the logs:
```
2023-03-06T23:20:44-08:00 [MONITOR] WARN: Monitor #17 'DayZ': Failing: Failed all 1 attempts | Interval: 60 seconds | Type: gamedig | Down Count: 0 | Resend Interval: 0
```

**Comment by chakflying** [comment]
Can you try setting the DayZ port to `27016`?

**Comment by louislam** [comment]
It seems that `givenPortOnly` set to `false`, it will work. Or as @chakflying said, using 27016 also works.

https://github.com/louislam/uptime-kuma/blob/2dedc1cfbd2eab61ebcc5793ee4a949532d19405/server/model/monitor.js#L523


I checked the games.txt, there is a value called `port_query_offset`.

> dayz|DayZ (2018)|valve|port=2302,port_query_offset=24714

2302 + 24714 = 2016

What I don't understand here is, what is the point of showing the fake port (2302) instead of 27016?

**Comment by chakflying** [comment]
I think `2302` is the port that clients actually connect to, while `27015+` is the Valve Server Query Protocol which is used to query the server status. Some info in  notes in https://github.com/Yepoleb/python-a2s .

The discussion in #2566 suggested the use of `givenPortOnly` because server admins would know which port to use. But it seems that now normal users also wanted to use this feature to monitor games they play, and made it confusing.

**Comment by shadowgamingyt** [comment]
for mordhau ive tried all ports possible even reinstalling the server changing the ports to its recommended to run the server and still nothing and everything is port forwarded.  in console it shows its talking but it ant getting data that its up
![image](https://user-images.githubusercontent.com/27635401/224435521-e93d12aa-e9cb-4605-83a6-4657ccc05321.png)


![image](https://user-images.githubusercontent.com/27635401/224435548-c1b91d96-e4a7-4fc7-bec4-85a9e2ceee22.png)
