### ISSUE TITLE
Cloudflare not updated in last release

### ISSUE THREAD

**Issue by AleksCee** [louislam/uptime-kuma#2952]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

just updated zu the latest dockermimage but it’s not including the last Cloudflare version. In logs at startup:
WRN Your version 2023.2.2 is outdated. We recommend upgrading it to 2023.3.1
is printing out.

### 👟 Reproduction steps

docker pull louislam/uptime-kuma:1
docker stop uptime-kuma
docker rm uptime-kuma
docker run -d --restart=always -p 3001:3001 -v /var/run/docker.sock:/var/run/docker.sock -v /volume1/docker/uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1

### 👀 Expected behavior

Latest version of Cloudflare tunnel is used.

### 😓 Actual Behavior

Old version of Cloudflare tunnel

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Safari on iOS 16

### 🐋 Docker Version

20.10.3

### 📝 Relevant log output

```shell
WRN Your version 2023.2.2 is outdated. We recommend upgrading it to 2023.3.1
```

**Comment by louislam** [comment]
It is not guaranteed to be updated, as it is included in the [base image](https://hub.docker.com/layers/louislam/uptime-kuma/base-debian/images/sha256-bc849283ae649a6a17d00a0d7c3378931222440a176a1ce31579f6bc7f1080d5?context=explore).

If you care about this, you should use cloudflared image separately instead of builtin cloudflared.
https://hub.docker.com/r/cloudflare/cloudflared
