### ISSUE TITLE
How to view "last outage" when it happened >1 wk ago?

### ISSUE THREAD

**Issue by luckman212** [louislam/uptime-kuma#2982]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### I've got...

- uptime-kuma v1.21.0 (Docker container on Ubuntu 22.04.1 host)
- 43 monitors, retention set at 180 days (cur db size=631MB)

### My question is...

How can I easily view the last outage for all of my monitors?

I know I can view them one by one in the UI, but I was looking to view the overall outage stats in one place. I do have an API key set up, but looking at the `/metrics` endpoint I don't see anything there for this. Are there any other endpoints available?

I figured out how to get the data via direct query to the SQLite db (expensive query!):
```shell
sqlite3 /app/data/kuma.db <<EOS
SELECT
  outage_time,name
FROM
  monitor
INNER JOIN (
  SELECT monitor_id, MAX(time) AS outage_time
  FROM heartbeat
  WHERE status = 0
  GROUP BY monitor_id
) AS max_hb ON monitor.id = max_hb.monitor_id
ORDER BY
  name
EOS
```

Any other way to do this? Sorry if I missed this basic info somewhere. I checked the wiki and searched issues as well. If it's useful to someone else, maybe I'll see about making a PR for this feature.

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Ubuntu 22.04.1 LTS

### 🌐 Browser

Chrome 111

### 🐋 Docker Version

20.10.17, build 100c70180f

**Comment by luckman212** [comment]
Please don't close this yet @CommanderStorm 

I can't seem to remove the `stale` label myself. But I think this should still be considered. It has no good solution that I know of, yet.

**Comment by CommanderStorm** [comment]
@luckman212 This is being autoclosed as this is a `help`-issue. 
It is unclear to me why you think I have any part in this ^^

# Using PromQL
I think the best solution for your problem is to [ingest our metrics endpoint into prometheus](https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration) and integrate this as 
```
topk(1, monitor_status{monitor_name="Google"} > bool 0)
```
(adapting as needed)

# Using SQL
I don't know of a better version of the SQL-statement you proposed.
I think the following is probably equivalent, but would not expect a significant performance gain:
```sql
SELECT MAX(h.time) AS outage_time, m.name
FROM monitor m, heartbeat h
WHERE m.id = h.monitor_id AND h.status = 0
GROUP BY h.monitor_id
ORDER BY name
```
Scanning though hundreds of MB worth of data is just slow, which is worsened by the fact that heartbeat has regular inseartions.

**Comment by luckman212** [comment]
@CommanderStorm I tagged you because I saw you've recently been moderating the Issues here. Sorry for that confusion. Thanks for the tip on Prometheus integration, I will look into that.
