### ISSUE TITLE
Option to display only monitors that are down

### ISSUE THREAD

**Issue by Piste** [louislam/uptime-kuma#2985]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I have more than 20 monitors, I'd like to see only those that are down on the dashboard view by selecting the appropriate filter.

### ✔️ Solution

Offer a filter or a checkbox, maybe in the left panel, that makes it possible to filter out monitors that are up.

**Comment by wordpresshosters** [comment]
Would be great to have this feature

**Comment by Piste** [comment]
> in the status page I use css override.

oh I didn't think of this. I guess I could use greasemonkey too (?)

**Comment by ozgurerdogan** [comment]
Well it is better to see them on top of list...

**Comment by CommanderStorm** [comment]
This issue seems very similar to #1585 which has an open PR (#1971).

@Piste if you agree, please close this issue or edit the issue to make it more distinct  ^^
(duplicates don't help to make the ammount of issues more manageable)


@MaxPowers1337  @ozgurerdogan  @wordpresshosters 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Piste** [comment]
Thanks for the pointer, @CommanderStorm. Super helpful.
Closing in favor of https://github.com/louislam/uptime-kuma/issues/1585
