### ISSUE TITLE
Can we have Last-Modified Monitoring with Uptime 

### ISSUE THREAD

**Issue by Blason** [louislam/uptime-kuma#3171]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature

### 🔖 Feature description

Hi Team,

UK is a great and simple one - However when we are monitoring our web application. It would be great if we can get a feature of monitoring last-modified header and if that changed it would be notified immediately?

### ✔️ Solution

This is to monitor the possible attempts of monitoring website defacement.

**Comment by CommanderStorm** [comment]
So basically you want an email every time you/your coworkers change something on the website too? (i.e. a lot of noise)
Is addressing the underlying issue (good auth, intrusion detection) not the better way to go about this issue?
Why is this better in a monitoring tool, instead of the system itsself?

This sounds like a [bodge](https://www.youtube.com/watch?v=lIFE7h3m40U)

**Comment by Blason** [comment]
Well monitoring particular page rather than entire web site and identifying last-modified could be an easy indicator of web defacement and then I have parameter set to monitor specific keyword from body to avoid false +ves.
Yes I agree it might create noise but having that option could be a great feature

**Comment by rezzorix** [comment]
Changedetecion.io might be better for your use case:
https://github.com/dgtlmoon/changedetection.io

**Comment by Blason** [comment]
That looks good!! Thanks for the help
