### ISSUE TITLE
ClickSend SMS Error: Socket connection timeout

### ISSUE THREAD

**Issue by PianXie** [louislam/uptime-kuma#3202]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to use ClickSend SMS for notifications.

When I test the sending, I only get the error message:

<img width="349" alt="Error: Error: Socket connection timeout" src="https://github.com/louislam/uptime-kuma/assets/134958580/1a3bc692-a7a2-4f9b-b197-1180c57fedb1">

The message appears immediately after clicking on "Test". I cannot find any request from uptime-kuma to clicksend via tcpdump.

Unfortunately, I cannot find any logs for this problem.
The problem occurs both when using the Nginx proxy and without the proxy.

If I send a request via cURL from the server, then everything works fine.

```
curl --include \
     --header "Authorization: Basic bV<------------------------------>DEyNQK"\
     --request POST \
     --header "Content-Type: application/json" \
     --data-binary "    {
        \"messages\":[
            {
                \"from\":\"Monitoring\",
                \"source\":\"uptime-kuma\",
                \"body\":\"test sms from monitoring poller to mobile\",
                \"to\":\"+30mynumber\"
            }
        ]
    }" \
'https://rest.clicksend.com/v3/sms/send'
```

### 📝 Error Message(s) or Log

Can anyone help me? I am looking for logs that explain the error message. 

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Debian 5.10.178-3 (2023-04-22) x86_64

### 🌐 Browser

All

### 🐋 Docker Version

pm2 5.3.0

### 🟩 NodeJS Version

v20.2.0

**Comment by CommanderStorm** [comment]
`ClickSend` is one of the less popular providers (since implementing it there has not been a PR/issue on GitHub or the Reddit) ⇒ Something might have broken on our side.

I think this could be one of 3 culprits:
- Just to make sure it is not something else:
  - The `Authorization": "Basic...` Field is also `Buffer:from("login:password").toString("base64")`
  - The number/.. is identical (no spaces/...)
- The difference between the current implementation and your curl command is the weird `"Accept": "text/json"` Header.
  Given that you are running natively, could you try if removing this field fixes this provider?
  See
https://github.com/louislam/uptime-kuma/blob/0735f12d19f3e0caa88284ea4eb1de88456441b6/server/notification-providers/clicksendsms.js#L11-L32
- Note that there may be some indicators of [weirdness with node 20](https://github.com/louislam/uptime-kuma/issues/3138)

Thank you for writing such a good issue (big thanks, how you wrote it should be the standard ❤️).

**Comment by PianXie** [comment]
Thank you for your answer!

I must correct myself, I had not set my tcpdump filter correctly. Requests go out, but there is no response at all. In any case, if the API endpoint is successfully reached, a status code should come back. In case of doubt, a 404.

I have tried many things now. For example, I have removed the "Accept: text/json" header, no change. 
Reversely, if I send `--header "Accept: text/json"` in my cURL request, it works.

I have also hardcoded the Authorization header. That doesn't change anything either.

With `tcpdump -vvv host 54.66.165.8 or host 13.210.77.102 or host 52.65.187.235` I get 18 outgoing packets, nothing comes back. The same with curl, then there are 18 outgoing packets and 18-23 replies. 

I have no idea why there is no response to the requests. 

Unfortunately, I have no idea how to debug this further. I run server infrastructure and implement software on it, but in this case I can't solve the problem on my own :-(

If someone needs API access for clicksend.com for the analysis, I will provide it.

And please excuse my language skills. My messages are translated from deepl.com

**Comment by PianXie** [comment]
> * Note that there may be some indicators of [weirdness with node 20](https://github.com/louislam/uptime-kuma/issues/3138)

Sorry, I missed the line.
With node v19.0.1, sending works perfectly.

`npm install -g node@19.0 --force`

Fixes the problem for me.
