### ISSUE TITLE
7 high security vulnerabilities in current install

### ISSUE THREAD

**Issue by risharde** [louislam/uptime-kuma#3235]
Hi @louislam - just installed up fresh install using the instructions on the front page and it shows 7 high security vulnerabilities - I highly suggest some upgrades so we can avoid crazy stuff happening?

Thanks!

**Comment by CommanderStorm** [comment]
@risharde 
In general: Not all vulnerabilities are created equal. Just because vulnerabilities are classified as `high` does not mean that they are a threat. (the inverse also holds true)


1. For actual security vulnerabilities, please follow this the [`SECURITY.md`](https://github.com/louislam/uptime-kuma/blob/master/SECURITY.md). If this were a real threat, your message could have exposed users ⇒ Please follow responsible disclosure
   Especially note the following line form the policy:
   > Do not use the public issue tracker or discuss it in the public as it will cause more damage.
2. The vulnerabilities you reported are not applicable. Please check if they are next time before raising an issue.
    - [The vulnerability in `fast-xml-parser`](https://github.com/advisories/GHSA-6w63-h3fj-q4vw) is a dependency of the optional AWS-Cognito part of `mongodb`. ⇒ I don't see how this could be exploited
      If you have found a way to do so, please report this, please report this via the method mentioned above. ![image](https://github.com/louislam/uptime-kuma/assets/26258709/43b3b59f-3c19-4f9f-b241-86122c41390b)
    - not applicable, we don't use this feature ![image](https://github.com/louislam/uptime-kuma/assets/26258709/4811b9f1-05c2-4d1c-88d7-fbd2b7b34b82)
    => Please do this work next time, before raising an issue
3. There are only "6" vulnerabilitys in npm:
    ![image](https://github.com/louislam/uptime-kuma/assets/26258709/c3aa75f1-e578-4acf-b8a1-baaa753ac6b5)

Given that this is not a threat, could your close this issue?
