### ISSUE TITLE
[Looking for CSS Expert] The Heartbeat bar so strange in some browsers and DPI

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#326]
![2021-09-03_151653](https://user-images.githubusercontent.com/1336778/131967415-dc4b769c-13ee-4f69-b4e6-109691a98cd3.jpg)

I called it a "beat" for each green block. Beat is a div with width/height. However, in some cases, the beat's width is different from each others. No matters how I set the width, it do not work with all DPI.

Enlarge image: 1920x1080 @ 100dpi  (Windows Server 2019  / Chrome via RDP)
![Unt222itled](https://user-images.githubusercontent.com/1336778/131967421-fe671eb0-cd0b-452d-94f4-af6e91e6d441.png)

https://github.com/louislam/uptime-kuma/blob/f84135ca675944fd59f2927d5fdd747fc9eba2c6/src/components/HeartbeatBar.vue#L95-L102

Edit: JSFiddle: https://jsfiddle.net/tqkermc5/21/

**Comment by chakflying** [comment]
In CSS, "px" doesn't actually mean device pixels, instead the browser will handle display scaling and rendering to the screen, and if the elements does not align to physical pixels, do sub-pixel rendering to improve the result. Since you used non-integer values for the width, it's very likely that the start of each beat does not align to the start of the physical pixels, and somehow the sub-pixel rendering does not handle this situation well. Here I tested `width: 6, margin: 2` and IMO it looks better and does not suffer from the problem.

|original|integer width & margin|
|-------|-------|
|![original](https://user-images.githubusercontent.com/3271800/131996027-3691cb1c-62fd-4a4c-a572-6568fa2c044d.png)|![integer-width](https://user-images.githubusercontent.com/3271800/131996054-48304827-9259-4b25-ad7a-f723dea85665.png)

**Comment by louislam** [comment]
Yes, `width: 6, margin: 2` is good for 100DPI

However, 125 DPI becomes like this.
![image](https://user-images.githubusercontent.com/1336778/132036283-9e6210c1-27fb-42c4-a90d-c16de63cee1f.png)

**Comment by louislam** [comment]
Also, tried many other units, no luck to make them to be even width of all beats in all DPIs.

**Comment by louislam** [comment]
Added
https://jsfiddle.net/tqkermc5/21/

**Comment by louislam** [comment]
It seems that there is no universal solutions for this, I handled by each DPI.

https://github.com/louislam/uptime-kuma/commit/cc25787878c37655ea6ce0cfe4d4fb1e3f224252
