### ISSUE TITLE
Suggest adding multi port detection

### ISSUE THREAD

**Issue by yangyzp** [louislam/uptime-kuma#3265]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Adding multi port detection to a detection task，Simultaneously detecting multiple ports.
As shown in the following figure：
https://s2.loli.net/2023/06/14/b76YVq8nx3PjcMp.png
![Snipaste_2023-06-14_13-06-18.png](https://s2.loli.net/2023/06/14/b76YVq8nx3PjcMp.png)

### ✔️ Solution

Adding multi port detection to a detection task，Simultaneously detecting multiple ports.

**Comment by CommanderStorm** [comment]
But one monitor should only monitor one thing => monitoring more than one thing with one monitor violates the debuggabiltiy of the system.
I think using multiple monitors in a monitor group (new since [`1.22.0-beta.0`](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0-beta.0)) would be a better option.

**Comment by CommanderStorm** [comment]
@yangyzp 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/497 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
