### ISSUE TITLE
ECONNREFUSED 1 API

### ISSUE THREAD

**Issue by fabricioguedeshotmail** [louislam/uptime-kuma#3340]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is it possible to validate an API request in node js (Express), or to return a status page 200 or 400 called at http://ip:3000 ,
 I tried to do it but it returns the error connect **ECONNREFUSED 1**, is it possible to do this monitoring?

### 📝 Error Message(s) or Log

 **ECONNREFUSED 1**

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

Ubunt 22.04

### 🌐 Browser

Google Chrome Last 1.

**Comment by CommanderStorm** [comment]
What are you trying to do?
Yes, you can validate that a page returned by express returns a status code.

Could you please add more details about what you did, what you tried and what did not work?
Attaching Screenshots might also be helpful in getting your point across.

**Comment by Computroniks** [comment]
`ECONNREFUSED` generally indicates that the server you are trying to monitor (or perhaps a firewall between you and the server) refused to connect when Uptime Kuma attempted to make the request. I would suggest that this issue is not with Uptime Kuma but with your network configuration. I would check a couple of things:

1. Is the server running and can you access it from your own computer?
2. Are there any firewall rules controlling access to the server? Perhaps requests are only allowed from certain IP addresses?
3. Are there any firewalls between the server and Uptime Kuma that could affect access?

**Comment by oussjarrousse** [comment]
> 3\. Are there any firewalls between the server and Uptime Kuma that could affect access?

4. the server notice uptime-kuma is sending too many requests and ban it for a short while...
A feature that detects that would be nice!

**Comment by Zvangi** [comment]
In my case it was iptables and iptables-legacy that was rejecting connections from uptimekuma server. The ones proxied by cloudflare was working fine but the ones that are on dns only mode was showing down and econnrefused.

**Comment by jasonfrost1231-maker** [comment]
Thanks for sharing your experience, Zvangi! That’s really helpful to know.
It sounds like iptables/iptables-legacy was blocking connections, which
makes sense given the different behavior with Cloudflare’s proxy mode
versus DNS-only. Glad to hear that the proxied ones worked, but the
DNS-only mode issue could definitely cause confusion. Hopefully, your tip
helps others troubleshoot more easily.
