### ISSUE TITLE
[Slack] Include URL in slack alert

### ISSUE THREAD

**Issue by wojcikm** [louislam/uptime-kuma#3351]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

URL in slack notification is missing now:
<img width="606" alt="image" src="https://github.com/louislam/uptime-kuma/assets/19979741/565ffeb8-a0f4-4da7-8066-3ab093068d7a">

Which is cumbersome to check the website that is failing - I have to go to the dashboard and search for it directly.

### ✔️ Solution

Add URL anywhere in the message - it would be highly appreciated

**Comment by CommanderStorm** [comment]
what kind of monitor are you using?
Could this be another symptom of the issue discussed in https://github.com/louislam/uptime-kuma/issues/3274

**Comment by wojcikm** [comment]
It's HTTP(s) monitor @CommanderStorm

**Comment by CommanderStorm** [comment]
Adding a button like this https://github.com/louislam/uptime-kuma/blob/13ae878ee8e45c652a927f7aad1db34752e61471/server/notification-providers/slack.js#L82-L97
but pointing to this URL should be eazy: 
https://github.com/louislam/uptime-kuma/blob/13ae878ee8e45c652a927f7aad1db34752e61471/server/notification-providers/ntfy.js#L58

The problem is that I don't have a working notification setup for slack. Could you test if adding such a change works and provide a PR?

**Comment by mstgelais** [comment]
Hi. Just wanted to add my voice: this would be a much appreciated feature. Thank you!

**Comment by CommanderStorm** [comment]
> The problem is that I don't have a working notification setup for slack. Could you test if adding such a change works and provide a PR?

See the discussion above

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing **what needs to be done how by whom**.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), as always: [Pull Requests](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) welcome.
