### ISSUE TITLE
[groups] An error occurs when clearing data

### ISSUE THREAD

**Issue by zKoz210** [louislam/uptime-kuma#3396]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Cannot read properties of null (reading 'status')

### 👟 Reproduction steps

Create a group monitor in a group monitor and try clearing the data

### 👀 Expected behavior

Do not receive an error, but wait until all monitoring passes through the links

### 😓 Actual Behavior

![image](https://github.com/louislam/uptime-kuma/assets/28255085/52f4689e-ec25-4c6d-a7bd-653eadb65948)

![image](https://github.com/louislam/uptime-kuma/assets/28255085/7cd9dd3b-efe4-47e3-a981-ef07c0adf514)

We get an incorrect uptime calculation in the group if all links after cleaning did not have time to request data

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Google Chrome 114.0.5735.198 

### 🐋 Docker Version

Docker version 24.0.4, build 3713ee1

**Comment by CommanderStorm** [comment]
@zKoz210 
I tried reproducing this issue but can not (both with an `all up`, `all down`, and `down-up` monitor setup).

![image](https://github.com/louislam/uptime-kuma/assets/26258709/22e1aaf0-68cd-403b-b975-074cbdf1ad6c)

What is the exact setup you used to reproduce this?

To be sure that we are talking about the same stuff:
Whe you are talking about deleting data, you are talking about this button, right?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/7a3423a2-efbf-43d4-b45c-2c8010ee3ede)


I am assuming this has been fixed in the last half year. If this assumption is wrong or my repduction was faulty, we can obv. reopen. ^^
If you can reproduce this, a [screencapture](https://gifcap.dev/) would be appreciated
=> closing as resolved
