### ISSUE TITLE
root CA certificate DST Root CA X3 will be expired in -650 days

### ISSUE THREAD

**Issue by lustmordtheblackpost** [louislam/uptime-kuma#3409]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

root CA certificate DST Root CA X3 will be expired in -650 days sending for sites on Tilda with Let's Encrypt

### 👟 Reproduction steps

sending for sites on Tilda with Let's Encrypt via telegram

### 👀 Expected behavior

This is bug. 

### 😓 Actual Behavior

i don;t know

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 20.04 x64

### 🌐 Browser

Chrome lastest

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3323
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? ^^

**Comment by louislam** [comment]
@chakflying Totally agree, if I know AI, I definitely would make this GitHub action to help me to close these issue. Sadly, I can't.

**Comment by CommanderStorm** [comment]
> If I know AI, I definitely would make this GitHub action to help me to close these issues.

@louislam 
I am not convinced that that would be a thing which could be solvable with AI. (context+reasoning like what, I assume, is required is nothing research has produced until now, afaik)

I do see a few solutions, though:

- For this type of duplicate (near 1:1 duplicate) there are actions out there: https://github.com/MarshallOfSound/probot-issue-duplicate-detection which, going by the code, produce a match based on the title of an issue
- In general, I think a revamp of how issues are closed if they are duplicates is needed. 
  I know that going by https://github.com/louislam/uptime-kuma/pull/1349#issuecomment-1094242302 you would like this to be a small hobby project, but given how many issues are created daily, a step into the community moderation route could be a healthy choice.
  What do you think about these options:
  - **GitHub-discussions instead of `help`-issues**:  
    I think that giving https://github.com/louislam/uptime-kuma/issues/92 another try could be worth it.
    Other projects of similar scale use these discussions and allow a sort of interaction "Look at what I have build" or helping new contrubuters find the courage to get started. See https://github.com/meilisearch/meilisearch/discussions for what I mean.
   The main reason why I think that this schould be reconsidered is that I think this project is at a point where issue management lying solely your shoulders is unmanagable from an effort perspective.
  - **Community moderation via direct nomination:**  
    Another approach would be to allow select people you trust (for example @chakflying ) the ability to close issues for you.
    GitHub has the `Triage` tier for this in the project settings under `Collaboration and Teams`.
    ![image](https://github.com/louislam/uptime-kuma/assets/26258709/845faf28-436f-4211-8df4-d969181cb3d0)
    If you are concearned, rules can be introduced like:
    - "Only close issue for clear duplicates"
    - "If unshure, mark as `likely-duplicate`, comment `I think this issue is a duplicate of #xxx ...` and wait at least 2 Weeks for an answer"  
    
    The advantge of this approach would be that these people could also add tags to issues => making searching easier and maybe reducing duplicates this way.
  - **Community moderation via Issue-voting:**  
    Same as the last point, but requireing less trust is this point, we could allow a group of trusted/active members to review Pull requests and comment commands like `!vote duplicate #XXX,#XXY`.
    Such a command could trigger a comment would trigger a comment by a github action requesting a votum of other members or a comment by the author why this is a distinct issue (specifics of such a message would need to be discussed further)
    If a specifed ammount of people on the community moderation team agree, the issue could be closed. 
  - **Duplicate nomination:** 
    The abiltiy for everybody to comment `!vote duplicate #XXX` which adds a `proposed-as-duplicate`
    Automatically leaving a comment might also be advantageous to explain the process to users.
    => You can review them when you like by just using a filter

=> I think a process on how to handle issue duplicates would be healthy for the project, what do you think about these proposals?

**Comment by loekg** [comment]
This is actually a bug, the Let’s Encrypt X3 certificate has indeed expired but that is actually correct.

https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

“DST Root CA X3 will expire on September 30, 2021. That means those older devices that don’t trust ISRG Root X1 will start getting certificate warnings when visiting sites that use Let’s Encrypt certificates. There’s one important exception: older Android devices that don’t trust ISRG Root X1 will continue to work with Let’s Encrypt, [thanks to a special cross-sign from DST Root CA X3](https://letsencrypt.org/2020/12/21/extending-android-compatibility.html) that extends past that root’s expiration. This exception only works for Android.”

Although I don’t fully understand how this works I believe there are actually two CA certificates, one of which has expired, but Uptime Kuma should ignore this expired CA certificate.

All my properly working Let’s Encrypt certificates now have “expired” CA certificates.
