### ISSUE TITLE
通知钉钉收不到消息，谁能正常使用吗

### ISSUE THREAD

**Issue by wq57wq57** [louislam/uptime-kuma#3458]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

通知钉钉收不到消息，谁能正常使用吗

### 📝 Error Message(s) or Log

1

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

1

### 🌐 Browser

1

**Comment by Snapstromegon** [comment]
Hi @wq57wq57,
I think opening an issue in Chinese won't lead to many results in this project, since this project mainly uses english for all communications.

I've put your title and description through Google translate:

**_"Notification Dingding can't receive messages, who can use it normally?"_**

I think it would be good if you could elaborate more on what your exact problem is, which errors and logs you see and so on, since otherwise I don't think anyone can help you.

**Comment by kenwoodjw** [comment]
pls check log，I use dingtalk is ok.
<img width="416" alt="image" src="https://github.com/louislam/uptime-kuma/assets/10386710/eab51528-6f57-4264-8fd7-00709f069ae8">

**Comment by kenwoodjw** [comment]
> Hi @wq57wq57, I think opening an issue in Chinese won't lead to many results in this project, since this project mainly uses english for all communications.
> 
> I've put your title and description through Google translate:
> 
> **_"Notification Dingding can't receive messages, who can use it normally?"_**
> 
> I think it would be good if you could elaborate more on what your exact problem is, which errors and logs you see and so on, since otherwise I don't think anyone can help you.

btw, Dingding 's English name is DingTalk

**Comment by wq57wq57** [comment]
thanks

**Comment by CommanderStorm** [comment]
> thanks

@wq57wq57 Don't forget to close this issue if it is resolved.
(only you or Louis can close issues)
