### ISSUE TITLE
Grafana OnCall support for Notifications

### ISSUE THREAD

**Issue by ntimo** [louislam/uptime-kuma#3528]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Grafana OnCall is a oncall system from Grafana Labs and available in the cloud and self hosted. Having support for sending notifications to OnCall would be quite nice.

Additional infos:
https://grafana.com/docs/oncall/latest/integrations/webhook/

### ✔️ Solution

Add support for sending Webhook to OnCall for notifications.

**Comment by ntimo** [comment]
Seems like there is already a MR for this: https://github.com/louislam/uptime-kuma/pull/2783

**Comment by CommanderStorm** [comment]
Said MR seems abandoned by  @atmaniak activity on this PR/in general.

Do you have a working subscription to said service?
The only thing that is barring this Notification provider is final testing:
- rebase the PR onto master (won't be a difficult rebase)
- merge the comments I made to make this compliant.
- Provide screenshots (as a quality guarantee, because it's a paid service) of 
  - `UP`/`DOWN`
  - testing event

=> This could be in `v2.0` (or maybe in `v2.1`, there are a lot of big changes coming in `v2.0` already 😉)

**Comment by CommanderStorm** [comment]
https://github.com/louislam/uptime-kuma/pull/2783 was merged and will be avaliable in `v2.0`
=> closing as resolved
