### ISSUE TITLE
[Suggestion] Document ENV variables

### ISSUE THREAD

**Issue by gaby** [louislam/uptime-kuma#355]
Would it be possible to get all the ENV variables supported by uptime-kuma documented in the Wiki section?

**Is it a duplicate question?**
No

**Info**
Uptime Kuma Version: latest
Using Docker?: Yes
OS: Ubuntu 20.04 LTS
Browser: Firefox

**Comment by gaby** [comment]
Doing a simple search on the repo, these are the variables that I could find.

```
NODE_TLS_REJECT_UNAUTHORIZED
NODE_ENV
TEST_CHECK_VERSION
SQL_LOG
SSL_CERT
SSL_KEY
```

**Comment by gaby** [comment]
With #436 now merged, the following variables were added: 

```
PUID
GUID
```

**Comment by erwineverts** [comment]
Link to MR to improve the documentation wiki: https://github.com/louislam/uptime-kuma-wiki/pull/5

**Comment by gaby** [comment]
@erwineverts i dont understand why the wiki is in a separate repo. Makes things super confusing. Also `NODE_TLS_REJECT_UNAUTHORIZED` is missing from the list.

**Comment by erwineverts** [comment]
I guess it's because wiki git repository can't be forked and thus by creating a separate repository, people can contribute.

Sorry, missed that one. My MR is already merged, so I won't add it now.
We could also argue to not include it because it's  strongly discouraged to use it (https://nodejs.org/api/cli.html#node_tls_reject_unauthorizedvalue)

**Comment by gaby** [comment]
@erwineverts Sounds good, closing this.
