### ISSUE TITLE
Handling issues when enabled Firefox's fingerprinting resistance

### ISSUE THREAD

**Issue by obfusk** [louislam/uptime-kuma#3554]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The favicon is broken in Firefox when not allowing access to canvas image data.

### 👟 Reproduction steps

Enable fingerprinting resistance (`privacy.resistFingerprinting`) in Firefox.

### 👀 Expected behavior

A favicon to be shown.

### 😓 Actual Behavior

No favicon, not even one without a badge.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Debian GNU/Linux 11

### 🌐 Browser

Firefox

**Comment by Computroniks** [comment]
The issue appears to be caused by an external package we use to generate the badges for the favicons called Favico. It appears to be this line that causes the issue:

https://github.com/ejci/favico.js/blob/6a3f430be559f93d96573e2a4a0116e154c11319/favico.js#L537
```
 var url = canvas.toDataURL('image/png');
```
It looks like this reads the data in the canvas (which is prevented by firefox) and writes it back to the favicon (it writes blank because firefox blocked the read). This behaviour looks similar to a bug I saw for firefox when looking into this which said a similar thing except with the QR code for web.whatsapp.com (https://bugzilla.mozilla.org/show_bug.cgi?id=1446472)

**Comment by Computroniks** [comment]
Given that the last update to that package was in 2016, I don't think we will get too far with getting this issue fixed there. We might be able to roll our own version of it with the fix though. I will have a bit of a play around with it and see if I can get anything working at all.

**Comment by louislam** [comment]
According to https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting

> It is likely that it may degrade your Web experience

I think it is the case. You have to accept that someone may be broken in this mode. And it is not a web standard, nothing we can do here. 

Since Uptime Kuma is a selfhosted and open source. You can always check the source code to see if Uptime Kuma really track you down via canvas. If possible, it should be safe to add your Uptime Kuma to the whitelist.

**Comment by CommanderStorm** [comment]
> I think it should be possible to handle this in Uptime Kuma

How do you think this can be done?
The issue is that reading the canvas element is blocked. I don't see a way to get around that.
We have a dynamic favicon and I don't think this should change..

I think solving this issue is fundamentally impossible while retaining the dynamic favicon
=> closing as wontfix. We can reopen if somebody comes up with a way to retain this functionality even in this submode of firefox.

In the meantime firefox has implemented a different method:

> changes the behavior when detecting a canvas extraction without
user interaction. It will show a canvas identity block icon with a
hidden doorhanger when auto-blocking the canvas extraction. Users can
make their choice to either block or allow the canvas extraction by
clicking the identity block icon and then refresh the page to make
the canvas permission taking effect.
