### ISSUE TITLE
Events other dan Down not recorded in the events per monitor

### ISSUE THREAD

**Issue by dfranken** [louislam/uptime-kuma#3556]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When monitoring a website, i see that sometimes a request fails with a 503 code. And the Uptime percentage drops. But this event is not shown in the events below. Although i can see it in the graph and in between the green bars (that represent a 200 OK).

The only wat that i can record this in the events, is by setting the retry to 0. But then everytime a notification occurs, but that is not what i want :)

### 📝 Error Message(s) or Log

No error is recorded.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Brave Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)

### 🐋 Docker Version

Docker 20.10.23

**Comment by CommanderStorm** [comment]
For me, the current behaviour is entirely logically.
Retrys affects how notifications and events are accounted, while uptime percentage is accounted directly

**Comment by Computroniks** [comment]
Correct me if I am wrong. Consider the following steps:

1. A monitor is configured with 5 retries
2. It runs and the first try it fails
3. The monitor enters a warning state
4. Nothing is written to the events and the monitor retries
5. The retry is OK and the monitor is marked as UP
6. Nothing is written to the event log.

What you are looking for is at step 4, instead of silently retrying, we log the response to the events log as a warning, even if on a subsequent retry the monitor then passes. To me, this seems to make sense as the monitor does enter a different state (the yellow/orange one) so we should probably log it in the events as well. If I have got this correct, I would suggest changing the label from `help` to `feature request`.

Interestingly, the reason for the pending event is shown on hover of the pill in the heartbeat bar, just not in the event log. So we should probably also include it there.

 
![image](https://github.com/louislam/uptime-kuma/assets/67638596/0cbddb28-0140-4dbb-963b-b91c0b58ce72)
This shows what I described above. The yellow pending pill shows the reason if we hover over it, however this is not shown in the event log below.

**Comment by dfranken** [comment]
> Correct me if I am wrong. Consider the following steps:
> 
> 1. A monitor is configured with 5 retries
> 2. It runs and the first try it fails
> 3. The monitor enters a warning state
> 4. Nothing is written to the events and the monitor retries
> 5. The retry is OK and the monitor is marked as UP
> 6. Nothing is written to the event log.
> 
> What you are looking for is at step 4, instead of silently retrying, we log the response to the events log as a warning, even if on a subsequent retry the monitor then passes. To me, this seems to make sense as the monitor does enter a different state (the yellow/orange one) so we should probably log it in the events as well. If I have got this correct, I would suggest changing the label from `help` to `feature request`.
> 
> Interestingly, the reason for the pending event is shown on hover of the pill in the heartbeat bar, just not in the event log. So we should probably also include it there.
> 
> ![image](https://user-images.githubusercontent.com/67638596/259829124-0cbddb28-0140-4dbb-963b-b91c0b58ce72.png) This shows what I described above. The yellow pending pill shows the reason if we hover over it, however this is not shown in the event log below.

Yes correctly! That is exactly what would be great. Because the pill above is only visible for a relativly short time, depending how  often it tests. So having the events written in the events below, would be great. Other way is by scaling the graph to max 1 week and hover over yellow bars. Idealy the events recorded, just like Down, but also other that what is marked than succesfull, would be great. I'm going to change this to a feature request.

**Comment by CommanderStorm** [comment]
@dfranken 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/688
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
