### ISSUE TITLE
sort monitor before DOWN then alphabetical order

### ISSUE THREAD

**Issue by ale82x** [louislam/uptime-kuma#3567]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

for me is more a clean interface is if a monitor is down is displayed first.
i have some monitor, and sometimes a monitor still down for days and is more clean if displayed first

### ✔️ Solution

create a change of sorting...

### ❓ Alternatives

alternatives is show only monitor DOWN on list ....

### 📝 Additional Context

thank you

**Comment by CommanderStorm** [comment]
This issue is likely resolved in `1.23.0-beta.1` as https://github.com/louislam/uptime-kuma/pull/3312 and https://github.com/louislam/uptime-kuma/pull/3469 were merged.
Please refer to the beta at https://github.com/louislam/uptime-kuma/releases/tag/1.23.0-beta.1.

⇒ Could you close this issue as it is resolved or comment on why it is not? ^^

PS:
For the future, please do run a duplication search, as otherwise managing this number of issues is quite bad, see https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+sort+down ⇒ https://github.com/louislam/uptime-kuma/issues/1585 or other issues

**Comment by ale82x** [comment]
sorry, i searched but probably not that deep...

thank you

**Comment by CommanderStorm** [comment]
@ale82x I think you forgot to close this issue, right?

> Could you close this issue as it is resolved or comment on why it is not? ^^
