### ISSUE TITLE
Send notifications to Azure Service Bus

### ISSUE THREAD

**Issue by jabbermouth** [louislam/uptime-kuma#3586]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Add a notification type to allow notifications to be sent to Azure Service Bus.  Authentication via connection string and managed identity would be preferred as an ASB user is also likely using Azure-based hosting.

### ✔️ Solution

When an up or down notification is raised, an item with the JSON payload sent via a webhook is pushed to a message queue in Azure Service Bus.

My scenario is I want a notification to sent somewhere public that can then be picked up behind a firewall using a pull model to remove the need to open up an inbound port.

### ❓ Alternatives

A simple API which listens for the webhook calls and processes the request.  Main issue is need to open hole in firewall.

**Comment by CommanderStorm** [comment]
This is kind of niche/uncommon notification provider.
If you/someone else would like to contribute such a provider, here is the Contribution guide:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md 

If you do decide to do this:
- shure that the PR includes screenshots of the `DOWN`/`UP` and `testing`/`cert-expiry` events.
- all keys that can/should be translated are in `en.json` (=> our translators can translate this + no merge-confilicts can arise due to this)

Also note that we already can define custom webhooks:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3038520f-818c-418c-846a-61d962e30621)
