### ISSUE TITLE
Elapsed time not responsive and invisible for non-logged in users

### ISSUE THREAD

**Issue by csy7550** [louislam/uptime-kuma#3596]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

"Elapsed time under the heartbeat bar" setting only works if you are signed in, public facing statuspage still display elapsed time and it's not very mobile friendly as seen in attached screenshot.

![original_a8ce379c-642a-48cb-8524-688b9beddb9a_Screenshot_20230818-065002](https://github.com/louislam/uptime-kuma/assets/6471050/bf3c67b3-6016-4898-b27d-9bb9d3ae241d)

### 👟 Reproduction steps

Toggle "Elapsed time under the heartbeat bar" setting.

### 👀 Expected behavior

Elapsed time show if selected, not if turned off.

### 😓 Actual Behavior

Setting works if you are signed in, if not, statuspage still show elapsed time.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Firefox, Chrome.

**Comment by CommanderStorm** [comment]
I think `elapsed time not responsive and invisible for non-logged in users` would be a better title.
Could you change the title please?

**Comment by rhbkweb** [comment]
Also having the same issue.

**Comment by CommanderStorm** [comment]
@pallebone @rhbkweb 

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing **what needs to be done how by whom**.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), as always: [Pull Requests](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) welcome.

**Comment by pallebone** [comment]
Maybe because its a regression added by a new feature, it could be changed so that the default is for this feature to be off, since it never existed before. That way it can be enabled by any logged in user, but logged out users will continue to have the old default way of it being off without experiencing an issue. Then there is not any urgency in fixing the issue also since it is a problem introduced by a new change?

**Comment by louislam** [comment]
It will be hidden on mobile in the next release.

**Comment by pallebone** [comment]
> It will be hidden on mobile in the next release.

Thank you so much for your hard work and dedication on this ❤️

**Comment by pallebone** [comment]
> It will be hidden on mobile in the next release.

Just want to let you know I updated today and can confirm it appears fixed. Thanks again :)

**Comment by samumatic** [comment]
This bugfix only solved the problem under mobile, where the time is no longer displayed by default. The real problem here is that in the appearance settings you can choose whether you want to have the "Elapsed time under the heartbeat bar" or not, but this is then only set as a cookie for the logged-in user. If you delete the cookies again, the elapsed time is there again.

So what we need is a **global** setting for logged-in and non-logged-in users, which this switch defines.

**Comment by chakflying** [comment]
It's not an easy problem to solve, as currently we don't have the UI design to make this an optional global/local setting.

**Comment by samumatic** [comment]
I have now solved the problem for myself. I simply set the opacity to 0 in the custom css area, so that it hides the time display under the bar for me. This is of course only a workaround, but it works.
```
.d-flex.justify-content-between.align-items-center.word {
    opacity: 0;
}
```

**Comment by ismdcf** [comment]
@samumatic  thanks for hack, instead of  opacity you could use display: none which gives the exact intended output
Add the below to the custom CSS block
```
body {
    .d-flex.justify-content-between.align-items-center.word {
        display: none !important;
    }
}
```

**Comment by neocharles** [comment]
> It will be hidden on mobile in the next release.

I am working on a status page to show on digital signage, and, I believe it utilizes "mobile" as the view type - and I have noticed that the heart beat bars are not displayed.  Is that due to this, or potentially something I can work around/fix?
