### ISSUE TITLE
v1.23.0 Removing All Monitors From Tag Deletes the Tag

### ISSUE THREAD

**Issue by zluckytraveler** [louislam/uptime-kuma#3619]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

If you remove all Monitors from a Tag and save, the Tag is deleted.

https://github.com/louislam/uptime-kuma/assets/97180817/c22295fc-5ca9-40ca-9c1f-402ddca72e9b

### 👟 Reproduction steps

1. Create Tag
2. Add Monitor/s
3. Save
4. Edit Tag
5. Remove all monitors
6. Save
7. Tag is Automatically deleted

### 👀 Expected behavior

For the Tag to remain, whether there is any monitors added or not.

### 😓 Actual Behavior

The tag is deleted.

### 🐻 Uptime-Kuma Version

v1.23.0

### 💻 Operating System and Arch

MacOS

### 🌐 Browser

Safari - Version 16.5.2

### 🐋 Docker Version

Docker Desktop  4.12.0

**Comment by ShadowGaming100** [comment]
From what I know the tag will be deleted if is not in any monitor

**Comment by CommanderStorm** [comment]
Said issue (or at least a closely related variant) can also leave the application in an inconsistent state.
I apologize for the long video, I have not found a way yet to reliably reproduce this. I assume this inconsistent state is a timing issue due to the async function calls in this method.

https://github.com/louislam/uptime-kuma/assets/26258709/10dee805-9032-498d-97dd-62eab6fb244f
