### ISSUE TITLE
Help with the security of this tool

### ISSUE THREAD

**Issue by sivamalla42** [louislam/uptime-kuma#3632]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,
I am exploring this tool. I feel this tool will help my purpose. But before installing this tool in my infrastructure, I would like to understand how secure is this. I am looking at security point of view, if this tool can cause any kind of security vulnerability or any kind of bots etc. Can some one help with any kind of documentation to have a kind of proof that this tool is a good to go ahead to have it in my infrastructure

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

mac OS

### 🌐 Browser

chrome

### 🐋 Docker Version

Docker v4.20

**Comment by CommanderStorm** [comment]
As always in security, it depends.
"Is it secure" and "kind of proof that this tool is a good" is not something anybody in IT will or should ever answer with a certain affirmative answer because that is a good indicator that they are don't understand every part of their system. 

Here is our security policy https://github.com/louislam/uptime-kuma/security and the 

What is your deployment strategy?
For example,
- the 1.x series only runs in root-user docker container
- the (not yet ready) 2.x series will run as non-root containers

The security of the tool also depends on your TOMs (Technical and Organisational Measures)
- Would you use the 2FA we offer? (if yes, that menas  extra protections agianst phishing)
- is your pasword secure?
- Would you publish the api-keys to the internet?
- Do you use network-segregation to separate what uptime-kuma should look at and the things it should not?
- Do you have organisational limitations (for example the one mentioned in )

And it depends on what your security-goals:
- confidentiality:
  - We have status pages that may leak information and (password/api-key protected) `/metrics`
  - If a user were to get access to your account, the confidentiality of the services you are monitoring would be at stake.
  - If a user has access to the hardware, the system is transparent via reading the database.
- integrity:
  - this is one of the weaker parts, while the system itsself is integre (we use a sqlite => the acid integrity guarantees apply), we don't have https://github.com/louislam/uptime-kuma/issues/3481
- avaliability:
  - If you have too many monitors, this may cause resource exhaustion through too much IO-Traffic on really slow disks (SD-Cards) or extreme amounts of monitors (<200 is save, depending on monitor type, retention and check-frequency this may also strech way further) 
  - Other than that networking may become prblematic if suddenly countless users ddos your status page (uptime-kuma is only desiged to run on one machine. If said machine's networking is at the physical limit, there is nothing we can do).
- authenticity: are not strong design goals, as this is not possible for the some monitors (think http, ping) to guarantee that the party they are pining is not man-in-the-middled. Other Monitors (https, ..) on the other hand can sort of protect against this to a point.
- non repudiation: I don't know what this would mean in our context => not relevant
- accountability: We have an access-log in which data about the checks we do is saved. We don't have https://github.com/louislam/uptime-kuma/issues/3481

=> If in doubt, why don't you order an external audit?

**Comment by CommanderStorm** [comment]
@sivamalla42 Did that adress your conceans?
Should we update our documentation in a way?
