### ISSUE TITLE
OAuth config invalid - token_endpoint_auth_method invalid or missing 

### ISSUE THREAD

**Issue by s256** [louislam/uptime-kuma#3665]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

While setting up OAuth Authentication for Monitoring I keep receiving 
```
API Endpoint [DOWN] The oauth config is invalid. missing, or unsupported, token_endpoint_auth_method
```
There is no way to set the value, which would then default to `client_secret_basic` here: https://github.com/louislam/uptime-kuma/blob/c4e222d1e6bc3846d6672368ae30301a796fa39e/server/util-server.js#L75

The method is supported (I'm trying to connect to an Azure service) The credentials are working (testing with postman).
 (https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0/.well-known/openid-configuration) 

I couldn't find any documentation about the settings ir limitation of the current oauth implementation to check or compare my settings. 

### 👟 Reproduction steps

* Select `OAuth` as method under "Authentication"
* Select either Header or Body as authentication Method
* Enter `https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/oauth2/v2.0/token` as `token_url`
* Enter random string for `Client_ID`
* Enter random string for `Client_Secret`
* Enter `openid`or `https://api.businesscentral.dynamics.com/.default` as `Scope`

### 👀 Expected behavior

Fail with invalid credentials / or pass with valid credentials

### 😓 Actual Behavior

Receiving an error message: `The oauth config is invalid. missing, or unsupported, token_endpoint_auth_method`

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox

### 🐋 Docker Version

24.0.5

### 📝 Relevant log output

```shell
`Failing: The oauth config is invalid. missing, or unsupported, token_endpoint_auth_method`
```

**Comment by s256** [comment]
Hi, so to replicate the error I simply used fake credentials. Valid credentials do not change the error message. As does changing the scope. What would be a valid value for scope here? According to azure something like 'openid' or 'email'. But I still get the same error message. The "sus " scope you mentioned is straight from the azure doc and is working nicely with postman.
Is there a list of example services which do work? I'm having a hard time finding a working configuration.

**Comment by CommanderStorm** [comment]
This comment does explian how to setup azure AD: https://github.com/louislam/uptime-kuma/pull/3119#issuecomment-1646886833

Flying over the guide the scope indeed looks sus:
> 7. Fill in the scope with the content you choose from step 5 and add the postfix `/.default`. It schuld look like this: `api://{{MY_APP_ROLE_URI}}/.default`

**Comment by s256** [comment]
I'm not setting a scope or expose a custom API in my setup.
Basically we're using this: https://businesscentralgeek.com/how-to-use-postman-to-connect-with-business-central-apis 

Relevant infos:
```
    Access Token URL. Enter this URL with your tenant ID: https://login.microsoftonline.com/(tenantID)/oauth2/v2.0/token
    Client ID. The one copied from Azure.
    Client Secret. The one copied from Azure.
    Scope. Enter: https://api.businesscentral.dynamics.com/.default
```
Which works fine, we're using it like this.
I'll dig deeper into this with curl to see where/how I can see or set the `token_endpoint_auth_method`

**Comment by s256** [comment]
```
curl -XPOST \
-H 'Content-type: application/x-www-form-urlencoded'  \
--data client_id='NOT_SO_SECRET' --data client_secret='VERY_SECRET' \
--data redirect_uri='https://localhost:8200' \
--data grant_type=client_credentials \
--data scope='https://api.businesscentral.dynamics.com/.default' \
--data token_endpoint_auth_method=client_secret_basic \
'https://login.microsoftonline.com/a...98/oauth2/v2.0/token'
```

Works for me. 
The `grant_type` is correct and is set here: https://github.com/louislam/uptime-kuma/blob/c4e222d1e6bc3846d6672368ae30301a796fa39e/server/util-server.js#L87
The auth_method is also correct and working. So I'm confused, why it works in `curl` but the same stuff is not working in kuma...

**Comment by hegerdes** [comment]
No problem. When ever I got time I will look into this repo and feature to see if I can help, but I cant always guarantee quick responses.

I'm not quiet sure what error you are actually getting. Can you please screenshot your config within uptime-kuma (with blurred secrets) and post the full error msg here. 

When I replicate your setup I get:
```
2023-09-01T16:09:14+02:00 [MONITOR] WARN: Monitor #6 'Test': Failing: The oauth config is invalid. unauthorized_client (AADSTS700016: Application with identifier 'abc' was not found in the directory 'Microsoft Accounts'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: f6ca8998-3eed-4425-8ed4-44edbf16a901
Correlation ID: 221fd158-6453-4714-8db5-4b0118147520
```
Which is logical because im not in your tenant and dont have a client "abc"
So you can definitely not set random strings for `clientId`, `clientSecret` or `scope`.

The `Authentication Method` field actually controls the type of how credentials are passed to azure. Currently supported are `client_secret_post` and `client_secret_basic`. Azure accepts both. The first one send the data in the HTTP body, the second as a Basic-Auth Header.
But there is a bug in the code (I made and overlooked):
https://github.com/louislam/uptime-kuma/blob/52946c3e08f975758dcd2ecde8ecd25d330390be/server/server.js#L760

This has to be `monitor.oauth_auth_method`.  Otherwise it always falls back to the default `client_secret_basic`. But this is not the cause for the error you are getting. For the Client Credential grant there is no redirect URL needed, since there is no web-client we are redirecting to because this is a setup without a user-context. See the token sequence [here](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow)

Have you tried to follow the Azure setup I posted in #3119.  Does this work for you?

If any resources I posted here or in the PR are helpful feel free to copy them to a wiki, modify them or print them on a T-Shirt.

**Comment by s256** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/1517486/cd2d0cf3-7801-4e19-a499-bef1485edf10)
![image](https://github.com/louislam/uptime-kuma/assets/1517486/d7745c50-4d55-44b1-93f6-ab8849f29d70)
![image](https://github.com/louislam/uptime-kuma/assets/1517486/6bfaf71f-6fb7-406e-9878-f5cfd70a0823)

You're setup is not really what I need to do to set up API Access to BC. Which is all I did and need. No need to define a role or scope. It's the SaaS version of BC, so it's not so much about monitoring the uptime of azure, but a) check that the credentials are still valid and b) the custom api endpoints are deployed. for a) changing the config to make the monitoring work, seems to defeat the purpose of monitoring in my opinion.

**Comment by hegerdes** [comment]
It seems like in the in the screenshot you use a different tenant than specified above (9188040d-6c67-4c5b-b112-36a304b66dad). So please make sure to provide a consistent config for debugging this.

The guide I provided is not for monitoring Azure. Azure is just the authentication provider and you can protect any resource by using this (or any) auth provider using the oauth spec.

Do you own the resource `api.businesscentral.dynamics.com`? Is it a services directly from Microsoft? If not you do need to register and define a role. Otherwise Microsoft does not know for which claims it should issue the JWT for. If is a Microsoft service, are there any official docs?

Just to make things clear again: You can successfully request a token from Postman and `curl`? Can you post part of the decoded JWT if you can generate one from `curl`

From a severity perspective you should definitely not use the same service account for monitoring and actually using the service. To there might be other ways to verify that the token is still valid

**Comment by TargetCrafter** [comment]
I'm getting the same error, but it seems to be because whenever i save the config the Authentication Method field gets reset:
<img width="282" alt="Before save" src="https://github.com/louislam/uptime-kuma/assets/47614276/23b1ca57-b2da-432d-b93a-bb56f1872d0b">
<img width="285" alt="After save" src="https://github.com/louislam/uptime-kuma/assets/47614276/fc4abe9e-a3d6-4507-8352-59651d82f088">
<img width="303" alt="image" src="https://github.com/louislam/uptime-kuma/assets/47614276/856f47ac-0c03-45d9-b4f8-dbc76e1be3b8">
Running the same request in Postman using it's OAuth 2.0 authentication works perfectly, so the values are not the issue.

I'm monitoring the following endpoint with a keyword check for ""isResolved": false":
`https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/issues?$filter=classification eq 'incident' and service eq 'Exchange Online'`

**Comment by hegerdes** [comment]
I'm on it but this week is tight on my side. Will report back on the end of the week. 

The bug with `monitor.oauth_auth_method` is already noted

**Comment by hegerdes** [comment]
I looked into this but was not able to reproduce the described error. 

What I did:
1. Checked out the 1.23.1 tag
2. Created a Azure App Registration with these permissions:
![image](https://github.com/louislam/uptime-kuma/assets/40325561/a6f838e9-d0f2-4fe2-a13e-c6e98fc812c7)

3. Tested the config with curl and got a token:
![image](https://github.com/louislam/uptime-kuma/assets/40325561/9e3d8ab6-9559-467f-b2e2-4696fceea421)

Moved the config to uptime-kuma:
![image](https://github.com/louislam/uptime-kuma/assets/40325561/be222951-0ff4-42d5-b0e0-2bce8c94c35f)

And I can request a token without a problem.

Unfortunately I dont have a subscription for businesscentral.dynamics.com, are not familiar with that service and dont have any endpoints to test the token against but getting a token was not a problem.

I tested it with the dev mode of uptime-kuma form the 1.23.1 tag and the docker image build of that tag.
I provided a fix for that mentioned bug in #3727. Maybe you can test if the error persist with that fix in place

**Comment by s256** [comment]
I'm running the docker version. I'll see if I find the time in the next days to set up npm. And run it as a dev server.

**Comment by TargetCrafter** [comment]
This is my environment where i got the error:

- Docker desktop installed on a Windows 11 VM
- Uptime-Kuma 1.23.1 installed via docker-compose:
```
# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'


services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
```
- Microsoft App registration with the following permissions (no licenses required):
![image](https://github.com/louislam/uptime-kuma/assets/47614276/a82d3a28-deca-4085-9581-963a0837f2d0)
- Tested the config with postman and got a token and a response:
![image](https://github.com/louislam/uptime-kuma/assets/47614276/44c0dc75-af56-4783-8bf2-3324e0be779c)

<img width="217" alt="image" src="https://github.com/louislam/uptime-kuma/assets/47614276/e311fa04-a154-4563-867e-e4fda3b802d5">
<img width="392" alt="image" src="https://github.com/louislam/uptime-kuma/assets/47614276/37126597-1395-46e1-aea3-11f4fa721b06">

- Tested in Uptime-Kuma and as soon as I save the config, the "Authentication Method" field resets:
![image](https://github.com/louislam/uptime-kuma/assets/47614276/d6723fd5-f14c-4351-8693-f24098406ee6)
![image](https://github.com/louislam/uptime-kuma/assets/47614276/35134be1-075a-4b89-93c6-c4823ae63c14)

This causes the following error:
<img width="301" alt="image" src="https://github.com/louislam/uptime-kuma/assets/47614276/8bf8c618-f01a-42b5-88e6-ab4330b2e657">

**Comment by hegerdes** [comment]
Thanks for sharing your setup @TargetCrafter 

The problem with the resetting auth_method is fixed in #3727. But this should not prevent you form getting a token with the Authorization Header option. Where you still able to get a token with the Authorization Header option using uptime-kuma?

It would be very helpful if you could try out this testing docker image, `hegerdes/testing:uptime-kuma-3727` with the fix of #3727 inplace. Does this work for you? In theory you only need to change the image in your compose file.
_Note:_ This is a testing image. It will be delete in the near future.

**Comment by louislam** [comment]
> I'm running the docker version. I'll see if I find the time in the next days to set up npm. And run it as a dev server.

@s256

You can test it with this special docker image without setting up an environment.

```bash
docker run --rm -it -p 3000:3000 -p 3001:3001 --pull always \ 
-e 'UPTIME_KUMA_GH_REPO=hegerdes:fix-oauth2-auth-method-setting' \
louislam/uptime-kuma:pr-test
```

More info: https://github.com/louislam/uptime-kuma/wiki/Test-Pull-Requests

**Comment by TargetCrafter** [comment]
Running the `hegerdes/testing:uptime-kuma-3727` image fixed both issues for me. The option is now remembered and because of this the athentication is now also succesfull.
Can I keep using this image until the fix is released into master?

**Comment by hegerdes** [comment]
From my side no issue. Just don't consider it supported or in maintenance. Will probably delete it after some grace time as soon as the PR is done.

**Comment by hegerdes** [comment]
@TargetCrafter Just wanting to let you know that I will delete the `hegerdes/testing:uptime-kuma-3727` in the next month. This should not be a problem since it is fixed in master and a new release was published some time ago.

**Comment by TargetCrafter** [comment]
Thanks for the heads up, I updated as soon as it was released, and it's been working ever since, so it can be removed without an issue.
