### ISSUE TITLE
Documentation missing to backup & restore a Uptime-Kuma instance between different servers

### ISSUE THREAD

**Issue by jahway603** [louislam/uptime-kuma#3680]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Documentation is curently missing to backup & restore a Uptime-Kuma instance between different servers

### 👟 Reproduction steps

Read description

### 👀 Expected behavior

Read description

### 😓 Actual Behavior

Read description

### 🐻 Uptime-Kuma Version

N/A

### 💻 Operating System and Arch

N/A

### 🌐 Browser

N/A

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

N/A

### 📝 Relevant log output

```shell
N/A
```

**Comment by louislam** [comment]
Just backup your docker volume.

**Comment by CommanderStorm** [comment]
I don't know what we would write in this documentation.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b2ebafeb-3ebd-4186-89f1-2efadd00672e)

**Comment by MWGMorningwood** [comment]
When copying the data folder over to a different persistent volume (and different kuma container), I get `SQLITE_CORRUPT`.
I for one would really like to see the backup function brought back to full-glory, but that'd probably be fit for a separate issue.

**Comment by CommanderStorm** [comment]
- For the backup functionality see this PR: https://github.com/louislam/uptime-kuma/pull/2667
=> It is essentially missing a way to test if the functionality works and won't magically break in the future. If you are more proficient in writing tests, help in this department would be appreciated.
-  about `SQLITE_CORRUPT`: This means that the data got corrupted on the way to the new location. This can happen due to multiple reasons (network-deamons, bit-flips, ..) but what I would suspect is that you did not shut down both instances before taking a copy.
- Since you are talking about PVCs: Could you please read through this https://github.com/louislam/uptime-kuma/issues/2668 and make sure that you are not using an unsupported filesystem?

**Comment by MWGMorningwood** [comment]
> * For the backup functionality see this PR: [Fix: Update json backup tool for new features #2667](https://github.com/louislam/uptime-kuma/pull/2667)
>   => It is essentially missing a way to test if the functionality works and won't magically break in the future. If you are more proficient in writing tests, help in this department would be appreciated.
I found this an hour or so after posting; I wish I were versed in JS or Vue. I'd definitely be willing to if I were.

>  This means that the data got corrupted on the way to the new location.
It's very believable; I'm doing a weird operation in moving the container from AKS into Az Container Apps.
I think simply downloading a (detached) VHD and re-uploading the contents would be ok, though.

> * Since you are talking about PVCs: Could you please read through this [Any specific reason why uptime-kuma does not support NFS file systems #2668](https://github.com/louislam/uptime-kuma/issues/2668) and make sure that you are not using an unsupported filesystem?
Funny enough, I'm pretty sure the source is NFS (I remember it being quite a battle). The destination is definitely ok, though.

I think my topic is a bit out of the scope of this issue- I'll follow up on more closely related ones (or new) if I can't figure this out.
