### ISSUE TITLE
Setting Primary base URL

### ISSUE THREAD

**Issue by softwarecreations** [louislam/uptime-kuma#3697]
### ⚠️ Please verify that this bug has NOT been raised before.
- [X] I checked and didn't find similar issue

### 🛡️ Security Policy
- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description
Setting Primary base URL on page `Settings > General` has no effect.

### 👟 Reproduction steps
1. Open http://localhost:3001/
2. Confirm you're logged in and it's working.
3. On page `Settings > General`, set Primary base URL to `http://localhost:3001/foobar`
4. Click save
5. Gracefully stop uptime-kuma
6. Gracefully start uptime-kuma
7. Try open http://localhost:3001/foobar/

### 👀 Expected behavior
http://localhost:3001/foobar/ should be the base URL. So for example
http://localhost:3001/foobar/settings/general
http://localhost:3001/foobar/dashboard

### 😓 Actual Behavior
Uptime kuma continues to perform with / as the primary base URL, as before.
The setting has no effect.
![image](https://github.com/louislam/uptime-kuma/assets/28704571/bdf874aa-8071-41aa-b843-aebc5f61624c)

### 🐻 Uptime-Kuma Version
1.23.1

### 💻 Operating System and Arch
Ubuntu 23.04

### 🌐 Browser
Brave, Chromium, FF

### 🐋 Docker Version
Running as a normal user, not using Docker.

### 🟩 NodeJS Version
Node v20.5.1 (npm v9.8.0)

**Comment by louislam** [comment]
> Uptime Kuma does not support a subdirectory such as http://example.com/uptimekuma. Please prepare a domain or sub-domain to do that.

Read more: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by bitdruid** [comment]
I agree with you. BASE_URL for a subpath should be generally available. 

Please overthink the implementation of this.

> FYI, the reason I asked (a few months ago)
> 
> For security I wanted to hide my uptime kuma under a random subpath like example.com/fsdokjsdfkofsdidfs
> 
> It's easy for a subpath to be secret. But there are pitfalls to having a secret sub-domain. You can't just use a letsencrypt cert for a subdomain because letsencrypt publishes the domain names of all certs issued. If you use a wildcard cert it can potentially be a secret subdomain but then there's also DNS leaks etc.
> 
> I ended up using a subdomain obviously, because as per this thread UptimeKuma doesn't support subpath.

**Comment by WayneGongCN** [comment]
Hello Uptime Kuma team,

I'd like to request support for a configurable baseUrl feature, or more simply, implementing relative paths in the HTML files. 

Currently, when deploying Uptime Kuma under a subfolder (e.g., example.com/uptime/), there are issues with static assets and API calls since they use absolute paths. This could be easily solved by using relative paths in the HTML for assets and API endpoints, rather than hardcoded root paths.

For example, changing paths like "/js/app.js" to simply "js/app.js" would allow the application to work correctly regardless of the deployment path. This small change would make Uptime Kuma much more flexible for various deployment scenarios, especially behind reverse proxies or in subfolders.

This is a common practice in web applications and would greatly improve deployment flexibility without requiring complex configuration options.

Thank you for considering this suggestion.
