### ISSUE TITLE
Allow a user configurable push URL instead of randomly generated hash.

### ISSUE THREAD

**Issue by shivaneshlal** [louislam/uptime-kuma#3737]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

As Uptime Kuma's user base expands, there's an increasing need for flexibility in how we deploy and maintain scripts for multiple instances. One area where this flexibility can greatly benefit users is in the push URL.

Currently, Uptime Kuma generates a randomly hashed push URL which, while secure, can pose challenges for automated deployments and scripts across various instances. By allowing users to define custom parameters in the push URL instead of solely relying on the randomly generated hash.

For those who use automation tools or scripts to deploy multiple instances, having a predictable or user-defined URL can significantly streamline the process.
If users can define their parameters, they can create naming conventions or structures that make sense for their specific use case, making it easier to manage and identify individual instances.
Custom parameters can aid in better integration with third-party tools and platforms, as users can ensure that URL structures align with other systems they're using.

### ✔️ Solution

We believe this enhancement will improve user experience, especially for power users and those managing multiple Uptime Kuma instances. While security is paramount and the randomly generated hash serves an important purpose, providing the option for custom parameters can offer both security and convenience when done correctly.

We hope to see this feature in the upcoming releases of Uptime Kuma.

Thank you for considering this request!

**Comment by dponzone** [comment]
I was about to open a feature-request about the push probe but perhaps it's a better fit to put my comments here.

What I had in mind is for the push probe to become more versatile. Currently, it's hardcoded to receive a value in ms (so the result of a ping test for instance) but it could be opened to any kind of values (meaning the values and labels on the graph should be more agnostic).
This way, it could become the Grafana for the commoners (the commoners being those who lack the time or skills to implement any Grafana/InfluxDB/...).

In my particular cases, I am pushing simultaneous voice calls with that. So it works the way it is, but one could ask why the numbers are in ms.

shivaneshlal, I don't know if this was your idea also.

**Comment by CommanderStorm** [comment]
@dponzone Not related to this issue => The correct issue is #2256

**Comment by CommanderStorm** [comment]
@shivaneshlal 
> can pose challenges for automated deployments and scripts across various instances

So you are likely using the [thrid party api](https://uptime-kuma-api.readthedocs.io/en/latest/) to create the monitors.
=> wouldn't it be possible to use the url you get via said api?

I don't quite get why the hardening needs to be softened in this part. If somebody can guess the push url they can set a monitor to be up/down, control the ping or insert messages.
All of these are very undesirable.

**Comment by CommanderStorm** [comment]
> @shivaneshlal
> So you are likely using the [thrid party api](https://uptime-kuma-api.readthedocs.io/en/latest/) to create the monitors. => wouldn't it be possible to use the url you get via said api?
> 
> I don't quite get why the hardening needs to be softened in this part.

I am going to close this issue as not planned.
I don't think a usecase for this actually exists, due to the api options mentioned above.
Allowing users to remove this level of security is something that I don't see a benefit from.

If I am missing something, we can reopen

**Comment by IzzySoft** [comment]
@CommanderStorm use-case: we have multiple servers reporting in via Push-Monitors. Our Uptime-Kuma instances are deployed via Ansible. If a re-deployment is needed, the current status would mean we'd have to reconfigure all the reporting servers with new push URLs.

I see no problem getting the **initial** URLs manually – and then also store those with our other "secrets", i.e. in an Ansible Vault (encrypted file). But for re-deployment / relocation of Uptime Kuma instances, being able to have the "new instance" using the very same values would be very useful. Any chance for that?

**Comment by CommanderStorm** [comment]
Why would you have to reconfigure all reporting servers with new push urls?

**Comment by IzzySoft** [comment]
Because we cannot set them automatically – unless we've missed something? How would I specify the URL when adding a new Push Monitor on a fresh setup via Ansible? To visualize it by an example:

* (multiple machines running already, which shall report in via Push Monitor on given events)
* setting up Uptime Kuma for the first time, or adding the Push Monitors for the first time: if done manually, the Push URL is generated via the Web-UI. We couldn't find a way to specify URLs for a scripted setup – but at the very first setup, URLs need to be configured with each server anyway (which would be OKish for the initial setup)
* those "multiple machines" get configured with the URL
* **now, a new Uptime Kuma instance shall be established** (e.g. the server is moved to a different provider, DNS is updated accordingly so the URLs would remain the same). How can we create the identical Push Monitors, with the identical Push URLs, so none of those machines need to be "reconfigured"?

> Moving the server does not change the urls. restarting the server also does not.

Apologies that I wasn't clearer in my terminology. I wasn't speaking of plugging the very same server into another location, or copying the files of a VM – but about deploying a new server in a different data center while the original one is still running, and then switch the DNS. Deployment happens via Ansible. So we are not moving files or machines. Same btw. in case of a server crash requiring a fresh deployment. Our Ansible config is stored in a Git repo, and that way in sync on multiple locations, enabling us to easily "redeploy" a server "someone threw a grenade into", to put it drastically.

**Comment by CommanderStorm** [comment]
Sorry, but what you want is not uptime Kuma.

You want Infrastructure as code, which is not something that we offer (out of scope). Other projects are a better fit for you here. Consider looking at gatus or similar.

We support the simple set up monitor, slap it in the cronjob kind of monitoring. We don't have dedicated ansible/other IAC support or other enterprise features like user management, sso, ...
For moving to a new server we suggest shutting down, moving the db and turning it back on.
 
What can work is to insert monitors into the SQLite table the way how you want them it is in some version and then letting our auto-db migration make this into the schema for the latest version. This does not play nicely with your preferred workflow after this since changes in UK are not done on your infrastructure monitoring template

**Comment by CommanderStorm** [comment]
We are not adding IAC. This is not the style we are after and at some point we need to cut scope.
We are already to much of an "eilerlegende wollmilchsau", which is not maintainable.
We really don't have the bandwith to maintain more options, look at the number of PRs/Issues and how we are behind on this.

Given the current structure, adding a testcase for push monitors is also somewhat difficult. Would maybe need refactoring first.
Adding to the websocket API option - maybe, as long as it comes with a test. This will not be avaliable in the frontend and is thus not manually testable for me.
