### ISSUE TITLE
Browsers don't show host or very slow refresh

### ISSUE THREAD

**Issue by mrmagoo1** [louislam/uptime-kuma#3789]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

the server running on LXC or VM with 4core and 4GB ram on 50Gb ssd disk, when load the first time and add hosts all works good, but after some day ( from 5 to 10) without add any new host, the browser as very slow to view the host or not show any host. I've 150 host on it with only ping setup every 20sec per host.

### 👟 Reproduction steps

create 4 group and 30host per group, set every single host to ping every 20sec, and add 1-2 tag.
open kuma from Brave, Firefox, Chrome, Safari give same problem after 5-10 days.

### 👀 Expected behavior

i think it's a problem to load o refresh the page, or db setting.

### 😓 Actual Behavior

i've to restar from new every time, restore Json or data won't resolve.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

ubuntu - debian - windows10 - macos

### 🌐 Browser

Chrome, Brave-Latest, Safari-Latest, Firefox

**Comment by CommanderStorm** [comment]
In the v1, the database size heavily grows with number of monitors and retention lenght.
This file-size growth leads to degraded IO-performance.

This issue will be fixed by v2, as https://github.com/louislam/uptime-kuma/pull/2750 was merged and we support external mariadb.
In v1 you can work around this by sharding (i.e. writing 50 pings/minute to the db) or by lowering the retention period.

Please close this issue, as this is resolved in the next release-train

**Comment by mrmagoo1** [comment]
ok thank's,
I'll perform the workaround.
When is schedule the v2 release?

**Comment by CommanderStorm** [comment]
> When is schedule the v2 release

As with all open-source projects, there is no schedule.
See this milestone for the prgress: https://github.com/louislam/uptime-kuma/milestone/24
