### ISSUE TITLE
Kuma crashes and crashes whole server

### ISSUE THREAD

**Issue by LucEmanu** [louislam/uptime-kuma#3829]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello, i updated and upgraded my Debian server and restarted it and then i noticed after some time it crashed my whole server.
How can i fix this? ._.

### 👟 Reproduction steps

I logged onto my server after it restarted and startet uptime kuma with a screen (screen node ...).
Then after 10-15 minutes i tried to log onto my server again and it didn't work. 

### 👀 Expected behavior

Just not to crash and not to crash the whole server.

### 😓 Actual Behavior

Does crash the server and itself, did not react anymore in the browser.

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Google Chrome 117.0.5938.108

### 🐋 Docker Version

-

### 🟩 NodeJS Version

18.17.1

### 📝 Relevant log output

```shell
-
```

**Comment by kokofixcomputers** [comment]
Can you give me some screenshots? I cannot reproduce.

**Comment by CommanderStorm** [comment]
Please also share the reelavan logs, how you host it (docker/node/pm2) and other relevant factors (low RAM/CPU/IO/Disk space)

**Comment by LucEmanu** [comment]
There is no screenshot because it just crashes withput showing an error. 
And i use node v20 (also tried it with v16).
The server has 4 GB Ram and enough disk space, Kuma runs on his own vm.

**Comment by louislam** [comment]
Likely a hardware issue. Debian is super stable, it is unlikely to be crashed by Uptime Kuma which is just a JavaScript application built on Node.js.

So please try to change another server (physically) to run it.

**Comment by h4knet** [comment]
Hello,
I'm sharing my experience too here because I guess it might help a little.

I had my Raspberry Pi 4 crashing quite frequently since I installed uptime-kuma in Docker, it wasn't crashing before and it would crash between 1 to every 3-4 days. I originally thought it would be linked to a defect on the SD card but since I removed uptime-kuma after seeing this issue, my Raspberry Pi isn't crashing anymore.

It might be due to high CPU or RAM usage but the result was that my rpi4 became unresponsive and only responded to pings; I couldn't open an SSH connection.

In the end, I really think Kuma has something to do with it. I'm using Kuma on another server of mine but no issues so far. If it can help I was using the chrome plugin to get http responses with screenshot; I think it might be the culprit, taking too much ram or CPU at one point and DoS-ing the whole server as a result.

Sadly I can't share much details here because I had to hard reboot the server every time.

Hope it helps.

**Comment by h4knet** [comment]
Unfortunately the reported issue is still there. 

I acknowledge its tough to have factual data or to replicate it easily but my pi4 never froze before I used uptime-kuma on it and it didn’t happened after I removed it.

I really think the culprit might be the browser check (with Chrome) that might blow up the whole thing. 

I had issues on another server with it and not using it anymore made the server stable.

**Comment by CommanderStorm** [comment]
It might be of note that our handling of how browser sessions are handled is a valid pointer for improvement.

This issue is continued to be tracked in #3788, as I think this issue only targets OOM caused by the memory leak of real-browser instances being spawned and kept around as noticed there.

=> closing as a duplicate ^^
