### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by larod241** [louislam/uptime-kuma#3935]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello, 

Would it still be possible to allways supply the Windows portable version? 
Updating from the Windows version is not possible in the environment in which I use UptimeKuma.

Thanks for your great work.
Sincerely 

### ✔️ Solution

Provide a Windows package for each update

**Comment by CommanderStorm** [comment]
@louislam you removed the windows portable from the docs in https://github.com/louislam/uptime-kuma/pull/3856
Is this intentional or just prepwork for v2?

**Comment by louislam** [comment]
Yes I removed it from the wiki. I am not interested to maintain this anymore, because the antivirus issue is getting worse again over time.

https://www.virustotal.com/gui/file/a3daff66c2c946a6a1de657aeddfd6a4aeeeb7c33c87743cfa96044bb14a15a9/detection


But you can still find it under the 1.23.1 page.
https://github.com/louislam/uptime-kuma/releases/tag/1.23.1


> Updating from the Windows version is not possible in the environment in which I use UptimeKuma.
> Provide a Windows package for each update

You can prepare it by yourself at this moment. Make sure `core` folder is not existing and run `uptime-kuma.exe` on a PC with Internet access. It should download the latest version of core. Zip the `core` folder, copy and unzip into your server.

**Comment by kokofixcomputers** [comment]
> Yes I removed it from the wiki. I am not interested to maintain this anymore, because the antivirus issue is getting worse again over time.
> 
> https://www.virustotal.com/gui/file/a3daff66c2c946a6a1de657aeddfd6a4aeeeb7c33c87743cfa96044bb14a15a9/detection
> 
> But you can still find it under the 1.23.1 page. https://github.com/louislam/uptime-kuma/releases/tag/1.23.1
> 
> > Updating from the Windows version is not possible in the environment in which I use UptimeKuma.
> > Provide a Windows package for each update
> 
> You can prepare it by yourself at this moment. Make sure `core` folder is not existing and run `uptime-kuma.exe` on a PC with Internet access. It should download the latest version of core. Zip the `core` folder, copy and unzip into your server.

Did you put any virus in there? or use any dependencies that have virus?

**Comment by chakflying** [comment]
This is a pretty ignorant comment but here is the issue that discussed it: #3142

**Comment by CommanderStorm** [comment]
Closing as we have decided that the [pain of supporting the windows PE version of our sofware is too much of a pain for us to shoulder.](https://github.com/louislam/uptime-kuma/issues/3935#issuecomment-1778922822)
We recommend switching to switch to the methods from our installation guide: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
