### ISSUE TITLE
Listen localhost project and port

### ISSUE THREAD

**Issue by volkankoc** [louislam/uptime-kuma#3956]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can I listen to an application running on localhost port 4000?
I did it with https and it didn't work, I tried it with port and it still didn't work

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

docker

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
See https://docs.docker.com/engine/reference/commandline/run/#publish

```bash
docker run -it -p 4000:3001 -v uptime-kuma:/app/data louislam/uptime-kuma:latest
```

**Comment by volkankoc** [comment]
No, my system is running on the internal network.
I have a few projects that use different ports on the network.
For example, 4000 is the backend, 4100 is the frontend.
Now what do I need to do to control these?
I want to test the backend running on port 192.168.1.40:4000 in the internal network.

**Comment by CommanderStorm** [comment]
You are quite unclear in what your exact network topology is (where are you pinging from/to, what is on these ports)

Have you tried the steps noted here: https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by louislam** [comment]
You should use "monitor" instead of "listen" in the topic, as "listen" has different meaning in the context.

By default, Docker containers are isolated, it is completely normal that you cannot access your "localhost" by default. You need "host mode" or "bridge network" to do that.

Read more: https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
