### ISSUE TITLE
Different URL for api push

### ISSUE THREAD

**Issue by notscottsmith** [louislam/uptime-kuma#3991]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

As part of how we do security at my workplace, we use differing URLs to obfuscate services which need access without any kind of authentication in front of it (e.g. Cloudflare). Is there a way to configure Kuma to recognise a different URL for API calls being done as part of a push test for a monitor?

e.g. kuma.company.com for the status page but api.company.com/api for the API calls?

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Kubernetes

### 🌐 Browser

Firefox

### 🟩 NodeJS Version

16.20.2

**Comment by chakflying** [comment]
The Status Pages do not need the websocket or the API to function. Have you tried setting a custom domain for your status page?

**Comment by sevmonster** [comment]
I think what @notscottsmith is talking about is similar to what I talked about [here](https://github.com/louislam/uptime-kuma/issues/4179#issuecomment-1843825134). For example, I use a special, internal-only URL for some of my HTTP monitors that only Uptime Kuma can access, that bypasses proxy authentication and sends directly to the underlying webapp. These pages may also potentially shim the proxy request headers so that the application returns correct data. It would be a major security threat should a URL like this be made public, if proper mitigations are not in place/not working to make sure that external/unauthed users cannot access the service via that URL. And currently, Uptime Kuma always shows the URL for HTTPS monitors with no option to disable it.

**Comment by CommanderStorm** [comment]
@sevmonster this issue is specific to the push monitor.

I think you have not found this button on the status page:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/e39a6169-95fd-48a0-beb9-08e306f2417e)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/d4eaa1e0-dd09-4bec-b2f2-4064f914081f)

**Comment by sevmonster** [comment]
Thanks for reminding me about that, I forgot it existed since I never use it because of the reasons I specified. I will make a new issue.
