### ISSUE TITLE
how update windows version

### ISSUE THREAD

**Issue by aliamg1356** [louislam/uptime-kuma#4076]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

hi
pls help me for update in windows to latest version
tnx

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

windows 11

### 🌐 Browser

115

**Comment by CommanderStorm** [comment]
It is unclear what deployment you are using.
Are you using docker or nodejs? Have you read https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update
What part are you stuck on?

If you are referring to the windows portable, please refer to https://github.com/louislam/uptime-kuma/issues/3935 => this is no longer supported due to the effort required being unreasonable

**Comment by CommanderStorm** [comment]
Closing as we have decided that the pain of supporting the windows PE version of our sofware is too much of a pain for us to shoulder.
We recommend switching to switch to the methods from our installation guide: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
