### ISSUE TITLE
After update groups and status page empty

### ISSUE THREAD

**Issue by Tealk** [louislam/uptime-kuma#4156]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I update Kuma, the groups are always empty after the update and the status page is emtpy too and all tags are lost.

![image](https://github.com/louislam/uptime-kuma/assets/12276250/d7a66016-3f2c-457d-9152-4df279293f42)

### 👟 Reproduction steps

I execute the following update steps: https://codeberg.org/Tealk/ansible_collection/src/branch/master/playbook/update-kuma.yml

### 👀 Expected behavior

i use the latest verision and all data remains persistent

### 😓 Actual Behavior

i update this software but all the entries are taken out of the groups and the status page is empty

### 🐻 Uptime-Kuma Version

1.23.8

### 💻 Operating System and Arch

ebian GNU/Linux 11 (bullseye) (5.10.0-26-amd64)

### 🌐 Browser

Firefox 120.0.1 (64-bit)

### 🐋 Docker Version

none

### 🟩 NodeJS Version

v16.20.2

**Comment by Tealk** [comment]
> Not a official method, you should ask them. I suggested you should change to the official method to install Uptime Kuma.

I built the script, these are the commands I took from the readme but summarized in ansible.

**Comment by louislam** [comment]
I have no experience with ansible, but I think you missed two important command:

```
git fetch --all
git checkout 1.23.8 --force
```

https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

**Comment by Tealk** [comment]
the only difference is that i use the master branch, but when comparing 1.23.8 and master there is no difference.

**Comment by louislam** [comment]
Definitely difference. The master branch is a development branch.

As I said, you should follow each command, otherwise, it could break your Uptime Kuma as the master branch is unstable.

**Comment by louislam** [comment]
No such standard. 

Any git branches could be development, and tag for release, I think it is more common.

And also that why Docker is existing in the world, it could prevent a lot of these mistakes by just pulling the docker image in order to update.

**Comment by chakflying** [comment]
In hindsight, delay merging 2.0 to master until closer to release might have been a better decision since it's causing so much trouble. I think it's caused by a slight difference in expectation between a library and an application, where for an application the master branch is usually considered to be stable-ish. But the blame is still on people writing bad instructions and blindly pulling master.

**Comment by louislam** [comment]
> In hindsight, delay merging 2.0 to master until closer to release might have been a better decision since it's causing so much trouble. I think it's caused by a slight difference in expectation between a library and an application, where for an application the master branch is usually considered to be stable-ish. But the blame is still on people writing bad instructions and blindly pulling master.

I think it is ok, I think the number of affect users are very very very small, according to the number of issue report vs non-Docker install: (I don't have the exact stats, but it should be a reference: https://www.npmjs.com/package/@louislam/sqlite3)

The most important is, I would say it is kind of hidden strategy on GitHub to make the project looks like it is in active development (indeed it is), because the last commit/date is always visible on the front page of the repo.
