### ISSUE TITLE
支持mq,memorycache，网页监控

### ISSUE THREAD

**Issue by gaye746560359** [louislam/uptime-kuma#4172]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

支持mq,memorycache，网页监控

### ✔️ Solution

支持mq,memorycache，网页监控

**Comment by CommanderStorm** [comment]
This issue is entirely unclear in what monitor is being requested. googling `mq,memorycache` does not yield good results.
Please put in the effort that you would expect in return. What is the documentation of the system you want to monitor 
What is the documentation of the system and how should it be monitored?

**Comment by kokofixcomputers** [comment]
We are all volunteers helping with this project in our free time. Please make issues clearer as those unclear issues just waste our time.

**Comment by CommanderStorm** [comment]
Closing due to issue quality
