### ISSUE TITLE
Setup Github Discussions for requests for help and others

### ISSUE THREAD

**Issue by solracsf** [louislam/uptime-kuma#4191]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Keep Github **Issues** for bug reports, and **Discussions** for, well...discussions :)

### ✔️ Solution

https://github.com/features/discussions

**Comment by CommanderStorm** [comment]
Previous discussion in https://github.com/louislam/uptime-kuma/issues/92#issuecomment-887386810

**Comment by louislam** [comment]
My answer in Dec 2023 is still no.

I did try it again in my new project:
https://github.com/louislam/dockge/discussions

But unfortunately, it is not much improved since then. There are a lot of useful features like the linking issue feature and the auto close feature are still not available for Discussions, which means I have to manually reply the pull request url and manually close the feature request. 

It makes me want to close Discussions again for Dockge.


And unless they implemented it, I won't consider to enable it for Uptime Kuma for now.

You can go to here to upvote the feature:
https://github.com/orgs/community/discussions/2971

**Comment by solracsf** [comment]
I understand, but when a repo is mixed between bugs and user questions, hard to sort them (frop a user/dev perspective, not a maintainer...).

But still, your call here of corse. Thanks.

**Comment by CommanderStorm** [comment]
> but when a repo is mixed between bugs and user questions, hard to sort them

We have recently added `area:...` tags to all of our open non-`help` issues to help with deduplication.
=> you can use these to filter issues as well. See https://github.com/louislam/uptime-kuma/labels
(there may be a few wrong asignments, if you see one, feel free to ping me)

I see the main problem with `help` issues not in where they are but rather in the `help`-issue quality https://github.com/louislam/uptime-kuma/issues/4172 is a good example of this.
