### ISSUE TITLE
[groups] Rules for combinations

### ISSUE THREAD

**Issue by superen7527** [louislam/uptime-kuma#4227]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

 1 more matching rules 
 
 2 add matching combinationsat the moment,
 
### ✔️ Solution
1 There seems to be an issue with this already, but I would like to add regular expressions as conditions.

2 it seems thatcan only combine them in groups, but if can, I'd prefer to do it as a conditional statement in a monitor.

Stripped from https://github.com/louislam/uptime-kuma/issues/4013

**Comment by CommanderStorm** [comment]
As stated in https://github.com/louislam/uptime-kuma/issues/4013
> 謝謝你的建議，一般來說，我們希望一個 Issue = 一個建議/問題/錯誤報告

The rationale behind this is quite simply that rewording issue titles/descriptions, assiging tags and other stuff related to managing issues is impossible otherwise.

> I would like to add regular expressions as conditions

Currently these issues exist
- https://github.com/louislam/uptime-kuma/issues/1851
- https://github.com/louislam/uptime-kuma/issues/2735
- https://github.com/louislam/uptime-kuma/issues/1938


I think you mean you would like REGEX as a general monioring option for all monitors that support checking content
"The current plan" to get this implemented is #3919 or a PR building on top of this.

> add matching combinationsat the moment

> it seems thatcan only combine them in groups, but if can, I'd prefer to do it as a conditional statement in a monitor.

Something was lost in translation here.

I think you are referring to either of these Issues:
- #2487
- #1089
- #3387

=> as far as I read this, the second point is a duplicate.

**Comment by CommanderStorm** [comment]
Closing as a duplicate as by discussion above
