### ISSUE TITLE
You can monitor Google Drive sheets if they go to the trash

### ISSUE THREAD

**Issue by richardani** [louislam/uptime-kuma#4292]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

You can monitor with Uptime Kuma if Google Drive sheets go to the trash?

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 20.04.6 LTS

### 🌐 Browser

120.0.6099.130

**Comment by CommanderStorm** [comment]
Currently, this is not a supported monitor directly. I am going to hazard a guess that this might be better done via process changes instead of monitoring.

If google does offer an api, you can likely utilise it to monitor this.
I think the correct docs is here: https://developers.google.com/docs/api/reference/rest/v1/documents/get?hl=de

**Comment by CommanderStorm** [comment]
https://script.google.com/ this might also be interesting
