### ISSUE TITLE
What is the upper limit of monitoring items?

### ISSUE THREAD

**Issue by L-69** [louislam/uptime-kuma#4359]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

What is the upper limit of monitoring items?

### 📝 Error Message(s) or Log

What is the upper limit of monitoring items?

### 🐻 Uptime-Kuma Version

/

### 💻 Operating System and Arch

/

### 🌐 Browser

/

### 🐋 Docker Version

/

### 🟩 NodeJS Version

/

**Comment by CommanderStorm** [comment]
Depends what montiors you want to run, how often they run and what retention you want.
There is no implemneted limt, but some monitors consume a lot of cpu/memory like "real-browser" (because it runs chrome) or other limits (f.ex. requesting big json files often => network bandwith) 

We are seeing some limits of the frontend at ~1000 monitors, but this will be fixed in v2.0.
We have not yet done concrete benchmarking on v2.0 where the newer limit is.
