### ISSUE TITLE
Uptime kuma exe version not working status page on iframe

### ISSUE THREAD

**Issue by volkankoc** [louislam/uptime-kuma#4380]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am using Uptime Kuma windows exe version. I want to display status pages as iframe. but I was not successful. I run the application via cmd with the following code
uptime-kuma.exe --disable-frame-sameorigin=true
uptime-kuma.exe --disable-frame-sameorigin=false
I tried both commands and it didn't work. The version I use is
https://github.com/louislam/uptime-kuma/releases/download/1.23.1/uptime-kuma-windows-x64-portable-1.23.1-2.zip

I would be happy if you help

### 📝 Error Message(s) or Log

no error log

### 🐻 Uptime-Kuma Version

1.23.1 exe version

### 💻 Operating System and Arch

Windows

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
> I am using Uptime Kuma windows exe version.

We don't offer the windows portable anymore due to maintainability issues with Windows Defender and other Malware scanners (See https://github.com/louislam/uptime-kuma/issues/3935 for further context).
Please refer to our installation instructions: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

How to configure an iframe is documented here: https://github.com/louislam/uptime-kuma/wiki/Status-Page#custom-subdirectory--custom-html-on-status-pages

Closing as not planned, as maintaining the exe is not something that we can offer as decided in #3935

**Comment by volkankoc** [comment]
I solved this problem
Edit line:124 server.js
const disableFrameSameOrigin = true;

its worked iframe
