### ISSUE TITLE
Vaultwarden "/alive" endpoint

### ISSUE THREAD

**Issue by LightD31** [louislam/uptime-kuma#4423]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Vaultwarden has a "/alive" endpoint that returns a string containing a single timestamp e.g. `"2024-01-25T13:57:13.532029Z"`
Using the JSON query, I can't parse this JSON, but it works just fine in https://try.jsonata.org/

### 👟 Reproduction steps

Use the HTTP - JSON query probe
Use a website that returns a single string as JSON
Try to parse the JSON (For example `($toMillis($now())-$toMillis($))<10000`

### 👀 Expected behavior

The JSON parses just fine

### 😓 Actual Behavior

The JSON isn't parsed

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 12 (Proxmox LXC)

### 🌐 Browser

Firefox 122

**Comment by chakflying** [comment]
https://github.com/louislam/uptime-kuma/blob/36196f632d499fddef436a3aacf2f11a01958f07/server/model/monitor.js#L594-L601

I think this was added because when we receive a string, it's likely that we have received a serialized JSON that needs parsing. We didn't expect it to be an already parsed JSON, which is "just a string".

I wonder if we can check the response content-type to prevent this.

**Comment by louislam** [comment]
Found a related discussion:
https://vaultwarden.discourse.group/t/return-alive-response-in-json-format/2905
