### ISSUE TITLE
Email (or any other) Notification upon creation of Scheduled Maintenance

### ISSUE THREAD

**Issue by skeelkat** [louislam/uptime-kuma#4438]
### 📑 I have found these related issues/pull requests

None Found

### 🏷️ Feature Request Type

Maintenance

### 🔖 Feature description

Add Notification Mechanism for Scheduled Maintenance upon add or edit.

### ✔️ Solution

A nice to have, would be that an email notification (or other) is sent to a specified recipient the moment after a scheduled maintenance is added and or edited.

This will provide administrators to notify certain parties of planned / scheduled maintenance all from Uptime Kuma

**Comment by CommanderStorm** [comment]
This issue is tracked in https://github.com/louislam/uptime-kuma/issues/2462
=> closing as a duplicate

Note that #2462 might require https://github.com/louislam/uptime-kuma/issues/508 or other creative mechanisms of managing which notification provider should be chosen first. If you have good Ideas, please comment them in #2462

Our contribution guide is here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
