### ISSUE TITLE
Back up without historic data

### ISSUE THREAD

**Issue by heffneil** [louislam/uptime-kuma#4442]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I noticed a warning about the export and import options in the program. I am looking to backup the monitors, not their historic data and the notification data so I could restore them in the case of a loss.  Is there some way to export the data programmatically periodically?  i have reduced the retention in the meantime but I would just like the config data separately to be backed up.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime:  Docker
- Database:  BuiltIn
- Filesystem used to store the database on:  BuiltIN
- number of monitors: 40

**Comment by CommanderStorm** [comment]
Currently, such a functionality does not exist.

Please see https://github.com/louislam/uptime-kuma/issues/2141#issuecomment-1272360952

> In 1.18.3, the backup feature was deprecated due to [being left] unmaintained.

Backup & Restore with JSON has been deprecated and issues will not be fixed due to the amount of problems it has been causing for our users and us.
The current design is just not maintainable, causing countless bugs.
In `v2.0` the deprecated backup tool is being removed because of this reason.
Please consider using SQL, API based[^1] or infrastructure based[^2] backup instead. 

New approaches to these features should use [SQLite dump](https://www.sqlitetutorial.net/sqlite-dump/) or [MariaDB dump](https://mariadb.com/kb/en/mariadb-dump/) respectively. (Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md))

You can subscribe to these issues meanwhile:
- #2496
- #477

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
[^2]: see https://github.com/louislam/uptime-kuma/issues/477#issuecomment-1557966187 for a setup example
