### ISSUE TITLE
How to import multiple site?

### ISSUE THREAD

**Issue by baalchina** [louislam/uptime-kuma#4447]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I have more than 200 sites want to monitor by uptime-kuma, but I found there seems no import function? I tried using backup/restore, while backup is not woking now?
So, how can I import multiple sites using xls or csv? Thanks.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Rocky 9.3, docker

### 🌐 Browser

Chrome,edge,firefox

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: default sqlite
- Filesystem used to store the database on: local
- number of monitors: 200+

**Comment by CommanderStorm** [comment]
Currently, no import function exists.
Furthermore, the backup feature was dropped in `v2.0` due to not being maintainable.

Currently, this is blocked by not having an API (we think we need this to not repeat the maintainability issues of the backup feature).
The current approach to implementing this is in https://github.com/louislam/uptime-kuma/pull/3854


Please consider using SQL or API based[^1] adding of monitors instead.

You can subscribe to/read these issues for further context/a notification if/once this gets implemented:
- #1190
- #1323
- #4308

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
      An example of how to use the third party API would be
      ```py
      from uptime_kuma_api import UptimeKumaApi
      api = UptimeKumaApi('INSERT_URL')
      api.login('INSERT_USERNAME', 'INSERT_PASSWORD')
      api.add_monitor(
          type=MonitorType.HTTP,
          name="Google",
          url="https://google.com"
      )
      api.disconnect()
      ```
