### ISSUE TITLE
Summarize Downtime in Notifications

### ISSUE THREAD

**Issue by Gill-Bates** [louislam/uptime-kuma#4452]
### 📑 I have found these related issues/pull requests

Not found

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

When a monitored host goes online again, it would be helpful if the notifications also indicated how long the host was down.

### ✔️ Solution

Implement the feature.

**Comment by CommanderStorm** [comment]
Thanks for this issue but this is already tracked in #177 as far as I can tell.
=> closing as a duplicate.

The last attempt blocked because https://github.com/louislam/uptime-kuma/pull/3394#issuecomment-1725356957.
Contributions in this area REQUIRE a discussions beforehand to avoid wasting time like in #3394
