### ISSUE TITLE
settings proxy import / export

### ISSUE THREAD

**Issue by jacoballen55** [louislam/uptime-kuma#4465]
### 📑 I have found these related issues/pull requests

there is no option for proxies import. I raised this last year but no response.

### 🏷️ Feature Request Type

Settings

### 🔖 Feature description

adding proxy import would be good.

### ✔️ Solution

adding in settings to setup new proxy import in format
ip:port:username:password

**Comment by CommanderStorm** [comment]
# Proxy backup

> I raised this last year but no response.

Not true, #2426 was closed as the backup feature introduced too many bugs and was unmaintainable.
Please see https://github.com/louislam/uptime-kuma/issues/2141#issuecomment-1272360952

> In 1.18.3, the backup feature was deprecated due to [being left] unmaintained.

Backup & Restore with JSON has been deprecated and issues will not be fixed due to the amount of problems it has been causing for our users and us.
The current design is just not maintainable, causing countless bugs.
In `v2.0` the deprecated backup tool is being removed because of this reason.
Please consider using SQL, API based[^1] or infrastructure based[^2] backup instead. 

New approaches to these features should use [SQLite dump](https://www.sqlitetutorial.net/sqlite-dump/) or [MariaDB dump](https://mariadb.com/kb/en/mariadb-dump/) respectively. (Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md))

You can subscribe to these issues meanwhile:
- #2496
- #477

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
[^2]: see https://github.com/louislam/uptime-kuma/issues/477#issuecomment-1557966187 for a setup example

**Comment by CommanderStorm** [comment]
# Proxy import

Why do you need this?
I am not quite convinced that adding such a feature would benefit the general user, as (at least the way I think our users use proxies => see #4456 for a relevant discussion)

I think the third party API might be a better fit[^1] for your use case (you did not specify the WHY).

[^1]: https://uptime-kuma-api.readthedocs.io/en/latest/api.html#uptime_kuma_api.UptimeKumaApi.add_proxy

**Comment by bcookatpcsd** [comment]
.. just wanted to add

K12 here.. 10 buildings.. heavy into proxying.. 

Migrated from a docker uptime-kuma to a standalone for db/latency issues.. 

Seems all the 'proxy checks' we had on defined hosts were not the the backup/migrations (in whatever state that is in)

It was not clear they were not in all that we migrated/moved.

**Comment by CommanderStorm** [comment]
@bcookatpcsd I don't fully know what you wanted to add.
Your comment does not go into why adding this via the thrid party API (https://github.com/louislam/uptime-kuma/issues/4465#issuecomment-1934470071) is not a better fit.

> Migrated from a docker uptime-kuma to a standalone for db/latency issues

I don't know what you are trying to do, but docker and standalone should not have latency differences to access the SQLite database. If you are trying to access an external DB to execute checks on, the latency should also be basically the same.

If you are trying to run many monitors (~500 on regular disks) or have lots of retention configured, the proper fix for this is to upgrade to `v2.0` (or `1.23.X` if you have not yet, there are some fixes in said release such as `incremental vacuum`) once it is out.
We have made some deep performance improvements, like storing data in an aggregated form.

> It was not clear they were not [in the backup]

That is why this feature will get removed in `v2.0` as stated in https://github.com/louislam/uptime-kuma/issues/4465#issuecomment-1934462816.
I think the warning on the backup page is enough to discourage the usage or to not expect that the export will be complete:

<details><summary>deprecation warning on the <code>Settings > Backup</code></summary>
<p>

![image](https://github.com/louislam/uptime-kuma/assets/26258709/2b0cff75-d056-4ac1-8f9a-c92f6e039241)

</p>
</details>

**Comment by CommanderStorm** [comment]
I think my argument from above why this can and should be solved via the [third party api](https://uptime-kuma-api.readthedocs.io/en/latest/api.html#uptime_kuma_api.UptimeKumaApi.add_proxy), the [third party cli](https://github.com/BigBoot/AutoKuma?tab=readme-ov-file#kuma-cli--) or in the future also the first party api (#118).
I don't see a reason for a dedicated proxy export/import to exist.
=> closing as not planned.

If I am missing a part, we can reopen this issue.
