### ISSUE TITLE
Deactivate notification temporarily

### ISSUE THREAD

**Issue by Tealk** [louislam/uptime-kuma#4493]
### 📑 I have found these related issues/pull requests

nothing

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be good if you could deactivate the notification temporarily, otherwise the server sends out thousands of notifications when it has problems.

### ✔️ Solution

A setting with which you can deactivate all notifications.

**Comment by CommanderStorm** [comment]
Two mechanisms exist for this use-case:
- you can pause a monitor on the edit page
- you can issue a maintanace period
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/fc5a2417-8a84-4622-8d69-fff0f778a4bd)

**Comment by Tealk** [comment]
that's not what i had in mind.
i have 40 entries, i can't switch off the notifications for all of them individually just because the internet connection is poor.
maintanace is also inappropriate because the services that are checked are working but the server on which uptime kuma is running has problems.

i have received 100 notifications in the last 30 minutes because some check has supposedly timed out, although only the uptime kuma server had problems.

**Comment by CommanderStorm** [comment]
In such a case, you might want to increase your retry setting.

Checking for Internet connectivity is tracked in https://github.com/louislam/uptime-kuma/issues/774 or in other conditional-monitoring related issues.

**Comment by Tealk** [comment]
these are rather network problems at the hoster, i had this 2-3 times in 1-2 years so far. nevertheless it is annoying because all channels are spammed.
so a button to globally disable notifications would be great.

**Comment by apio-sys** [comment]
If I might add to this discussion a general remark about monitoring. 

Your Uptime Kuma server (or whatever other self-hosted monitoring service you use) is very important for you since you are basically monitoring your SLA vis-à-vis your customers may they be internal or external. 

So you would put it somewhere, where this SLA makes sense. I.e. I have external customers all served from the same DC. I place my monitoring software *elsewhere* to make sure my pings to those services actually make sense as if they where the clients' audience trying to reach that service. 

Obviously, it's useless to put that machine in a situation with poor network conditions. In other words, your monitor server needs to be treated as VIP and should *never* have problems. Otherwise monitoring doesn't make sense at all. IMHO I would never run this as a Docker image other than for development purposes and have your prod machines running on bare-metal with "un-bottle-necked" redundant network connections.

Beyond that, and to help in certain situations/specific conditions, there are fine-tuning options in Uptime Kuma as @CommanderStorm indicates which are very good to help with this. And as for the subject of this ticket "Deactivate notification temporarily" I can't see why that would be beneficial in any scenario. If you got the 100 alerts, it's already too late to go to your U.K. server to change it's behaviour no? And you can join the discussion in #774 of course for follow-up.

**Comment by Tealk** [comment]
this misses the point, this is about a one-time network disruption that cluttered the ntfy and matrix channel with messages that were false.
The server's network problems lasted for an hour and then they were over, and only in this case would this button be extremely useful.

@apio-sys 
I'm sorry that I don't have the money to get hardware and network for a hobby project that has 100% uptime (and now please don't come to me with "that doesn't exist").
i pay everything out of my own pocket and that in addition to my running costs, yes i get support from the users of the software but i am still several thousand euros in the red...

**Comment by apio-sys** [comment]
Hey @Tealk I will not come back to you with "that doesn't exist". Of course, I have hobby projects as well with close to zero funding but when they go down or their stats are wrong because - I don't know, the cleaning person unplugged the server to plugin the hover since there is only one socket, and I'm hardly exaggerating - I don't care since I don't have an SLA here right? I don't know why you are several thousands in the red (sounds scary), but that is really unrelated here and I suggest you join the discussion on #774 for further exchanges since this is closed here I notice.

**Comment by Tealk** [comment]
so i see #774 and my request as 2 different requirements. but ok then i'm out of here for now.

**Comment by CommanderStorm** [comment]
> IMHO I would never run this as a Docker image other than for development purposes

@apio-sys 
I don't quite know what you are precisely talking about.
Docker should be basically the same reliability as the core tech is just namespaces + cgroups + .. => the kernel is the same
I think you might be confusing docker and VMs when you are talking about.

Docker has reliability advantages as it ships with a system as configured by us
=> there won't be any configuration related mishaps (unless we ship a bug) and you get things like NSCD or embedded MariaDB (>v2.0) for better results.

Could you link to some docs/ resources about your concerns?

**Comment by apio-sys** [comment]
No Frank @CommanderStorm I can't link to any docs about this, hence I stated IMHO. This is just my opinion of an old service man. I think you guys are doing a great job supplying both a Docker conf and a "classic" one as one might say. As you say *"Docker should be basically the same reliability"* and that's where I like to be my monitoring system to be running on bare-metal (and monitoring services that might be containerized themselves) since I want to remove as much as layers as possible. See my point of view? I have SLAs to keep and previously PHPmon was helping me do this and now it's Uptime Kuma. And what a step up it is! Thanks.
