### ISSUE TITLE
Notification not triggered when services comes UP

### ISSUE THREAD

**Issue by typro33333** [louislam/uptime-kuma#4512]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have setup notify check healthy my gitlab server. Also i have setup notify webhook through to Lark Suite. It has sent alert when services down but when services up, it not alert again.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: K8s
- Database: sqlite/embedded
- Filesystem used to store the database on:  NFSv3 on HDD
- number of monitors: 1

**Comment by CommanderStorm** [comment]
From your description this could be multiple things.

What was the log output?
How have you configured the monitor in terms of retention settings?

**Comment by typro33333** [comment]
So, I will show you all my step to notification my Lark.
1. Create bot webhook in group chat Lark suite then it give me URL hook without credential.
2. Then I go to Lark Suite docs to read about custom layout notification: [Docs Lark Custom](https://open.larksuite.com/document/client-docs/bot-v3/add-custom-bot. )
<img width="498" alt="Screenshot 2024-02-22 at 12 36 26" src="https://github.com/louislam/uptime-kuma/assets/62330937/24b60f31-bca1-436f-aa46-04fd47b5831f">

4. I have tested send message complete to Bot Lark but just only when services gitlab down time. It should be when gitlab uptime it with send notification that service is uptime. Finally, it sent again downtime notification. ( It mean it send 2 times downtime though service on uptime).

**_My Question with if gitlab uptime how uptime kuma send custom another notification uptime to bot ?_**

**Comment by CommanderStorm** [comment]
So we are talking about two differnt things. Your inital message gave the impression that NO allert is send out on a monitor coming `UP`

> but when services up, it not alert again

You are talking about something different in the second message.

> Finally, it sent again downtime notification

This is because you have configured the webhook to open the issue in larksuite.
Said webhook is send on both `DOWN`/`UP`/Certificate Expiry/Testing.
Currently, filtering what notifications get passed to which notification provider is not supported.
See https://github.com/louislam/uptime-kuma/issues/508 for the tracking issue

Please see https://github.com/louislam/uptime-kuma/issues/3715 for how to configure Lark via `Feishu` as the notification type or how to contribute a dedicated notifiaton type for Lark ^^

**Comment by typro33333** [comment]
Thanks so much for answer to help me.
