### ISSUE TITLE
Use Cloudflare Access in front of Uptime Kuma

### ISSUE THREAD

**Issue by kangapi** [louislam/uptime-kuma#4533]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'd like to use Cloudflare Access in front of Uptime Kuma. I have disabled authentication as indicated. 

<img width="485" alt="Capture d’écran 2024-02-26 à 16 47 02" src="https://github.com/louislam/uptime-kuma/assets/78305748/06609d20-3993-48cf-a99b-64e51d04a578">

I would like to authorize access to uptime kuma only to certain users but allow anyone to access the status pages. 
So I created 2 applications on the Zero Trust dashboard. One to authorize only certain users to access all paths and another to authorize all users to access the "/status" and "/api" paths. 

<img width="1148" alt="app zero trust" src="https://github.com/louislam/uptime-kuma/assets/78305748/6fe5f77e-2e78-4adb-ba2c-d565e4e26ad0">

### 📝 Error Message(s) or Log

But if I go as a normal user to the page "www.example.com/status/statusPage" an error appears

<img width="827" alt="Capture d’écran 2024-02-26 à 17 04 47" src="https://github.com/louislam/uptime-kuma/assets/78305748/bfa73c2d-dc13-42cf-880f-ad856cd67fb9">

Maybe I should do something different?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian Bullseye

### 🌐 Browser

Google Chrome 121.0.6167.184

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.7

**Comment by CommanderStorm** [comment]
So something has returned you an html site instead of a js site.
Have you looked at what the content of said html site was?

You handled two of the routes. How are the other routes handled?
These are the routes that are called for a sample stauts page (excluding index+api)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/49a7480b-70e4-41e9-bf84-5ea5059885e9)

> [!WARNING]
> Note that other routes like the `/metrics` may leak information if you disabled auth.
> => Keep these protected

> [!CAUTION]
> Note that allowing `/api` for anybody might have security impliations if https://github.com/louislam/uptime-kuma/pull/3854 gets done in `v2.1`

=> I would recomend to use a custom domain name for your status page instead. See https://github.com/louislam/uptime-kuma/wiki/Status-Page#domain-names-for-status-pages

**Comment by kangapi** [comment]
Ok thanks, so I use a custom domain for my status page that I authorize to everyone and I have another main url where I only authorize certain people. The problem is that I just have to go to the url I authorize, add "/dashboard" and the page is accessed because authentication is disabled.

**Comment by CommanderStorm** [comment]
I don't quite get what you are refering to and where the problem lies.

- any requests to the main url (uptime.example.de) => under cloudflare auth => need to authorise via cloudflare
- any requests to the status url (status.example.de) => NOT under cloudflare auth => need NOT authorise via cloudflare

What exactly is working how?
As far as I understand your statement, you
- go to uptime.example.de
- authorise in cloudflare
- are now authorised and can access `/dashboard`

**Comment by kangapi** [comment]
The problem is that if I go to status.example.de which is not under cloudflare auth everyone can access /dashboard

**Comment by kaywoz** [comment]
I had the same issue but the below works.

the tunnel
![image](https://github.com/louislam/uptime-kuma/assets/64521603/f272f31b-c775-4269-bb23-d2519e67fdcb)
Applications
![image](https://github.com/louislam/uptime-kuma/assets/64521603/dd187cfd-8594-4c58-8ad5-2ebbc0d01cd6)
My allow policy, but nothing special as it allows everyone to the Status page.
![image](https://github.com/louislam/uptime-kuma/assets/64521603/45397045-9c60-4730-a836-62d76b6da211)
This allows you access to the Status page
![image](https://github.com/louislam/uptime-kuma/assets/64521603/f3fd7f00-3640-4741-969b-844de28ce503)
But not to /list or /dashboard or other endpoints found here as far as I tested; 
![image](https://github.com/louislam/uptime-kuma/assets/64521603/49976adc-7841-4e14-9889-fa236a9615b4)

https://raw.githubusercontent.com/louislam/uptime-kuma/master/src/router.js

hope this help.
