### ISSUE TITLE
`Error: write EPIPE` during shutdown

### ISSUE THREAD

**Issue by ozgurkazancci** [louislam/uptime-kuma#4611]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Whenever I stop the uptime-kuma service, I get in my data/error.log file the error messages I pasted here.
Any idea would be much appreciated.
Regards.

### 📝 Error Message(s) or Log

```raw
[2024-03-21 23:37:05] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:962:11)
    at Socket._write (node:net:974:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at console.value (node:internal/console/constructor:305:16)
    at console.log (node:internal/console/constructor:380:26)
    at Logger.log (/usr/local/uptime-kuma/src/util.js:140:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

FreeBSD 14

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: Node.js version: `18.19.1`
- Database: SQLite Version: `3.41.1`
- Filesystem used to store the database on: UFS
- number of monitors: 0

**Comment by CommanderStorm** [comment]
What is the monitors type?

**Comment by CommanderStorm** [comment]
I was asking because you reported that you have

> number of monitors: 1

I cannot reproduce this issue with a fresh (temporary) instance:

```
sudo docker run -p 3001:3001 louislam/uptime-kuma:1
```

Lets dig into this further:
- In what state are you when you send the shutdown command? (what actions have you performed previosly, do you have the website open, ...)
- How do you send the shutdown command (are you using the gracefull shutdown `SIGKILL` or are you `SIGILL`-ing the process)?

**Comment by CommanderStorm** [comment]
Okay...
Lets get to a common denominator:
How did you install uptime kuma exactly (could you share your full configuration)? (our [installation guide](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install) does not talk about services...)

These are the lines before shutdown (depending on your installation path nscd is likely not there)
```
2024-03-22T01:09:51Z [SERVER] INFO: Adding socket handler
2024-03-22T01:09:51Z [SERVER] INFO: Init the server
2024-03-22T01:09:51Z [SERVER] INFO: Listening on 3001
2024-03-22T01:09:51Z [SERVICES] INFO: Starting nscd
```

and these are the lines after shutdown has been (depending on your installation path nscd is likely not there)
```
2024-03-22T01:10:48Z [SERVER] INFO: Shutdown requested
2024-03-22T01:10:48Z [SERVER] INFO: Called signal: SIGTERM
2024-03-22T01:10:48Z [SERVICES] INFO: Stopping nscd
2024-03-22T01:10:48Z [SERVER] INFO: Stopping all monitors
```

**Comment by chakflying** [comment]
This is probably some kind of race condition caused by the OS / service config, such that the `stdout` pipe gets closed before the main process terminates. Given that this only occurs on shutdown, and we can't reproduce, I don't see a priority in fixing this.

Anyone who can reproduce this, feel free to try handling the closed pipe with something like [epipebomb](https://github.com/mhart/epipebomb).

Related: https://github.com/nodejs/node-v0.x-archive/issues/3211

**Comment by chakflying** [comment]
Wow I didn't know there's actually a cli argument to require a module before startup, I guess you learn something new everyday :)

**Comment by CommanderStorm** [comment]
Given that this is only reproducible on freebsd (=not a platform we officially support due to lacking users) and that this is not reproducible on platforms that we support, I am going to close this as resolved without putting in the effort to set up freebsd and debug why this race condition really happens (TBH: I am not sure if the deamon command forewards the `SIGTERM` in the first place).
