### ISSUE TITLE
Recuring Interval Maintenances display wrong dates in the maintenance list

### ISSUE THREAD

**Issue by eakteam** [louislam/uptime-kuma#4634]
### 📑 I have found these related issues/pull requests

NONE

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Trying to add a Recuring Interval Maintenance and it seems that it gets the wrong dates.

E.g. trying to add this maintenance on `04/07/2024`
![uptime1](https://github.com/louislam/uptime-kuma/assets/8820741/3d21e1c0-7d78-4f8d-9166-ddb9ebeba1ab)

It shows wrong data here.
![uptime2](https://github.com/louislam/uptime-kuma/assets/8820741/c0894a0b-9014-4f02-a36c-1150efcf1f95)

### 👟 Reproduction steps

Add a recuring interval maintenance e.g. running once every 7 days starting from a specific date and after it ads it, it displays the wrong data in the Maintenance list.

### 👀 Expected behavior

It should show the right date which we have added in the first step.

### 😓 Actual Behavior

It shows the wrong date.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04 LTS

### 🌐 Browser

Google Chrome Version 123.0.6312.86 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: NodeJS v20.12.0
- Database: sqlite/embedded
- Filesystem used to store the database on: ext4 on SSD
- number of monitors: 7

**Comment by buzzinJohnnyBoi** [comment]
Hello, is anyone currently working on this issue? If not, then I would like to try my hand at it.
Thanks.

**Comment by CommanderStorm** [comment]
Nobody is currently working on this to my knowledge ^^

**Comment by buzzinJohnnyBoi** [comment]
I have made a little bit of progress, I was able to reproduce the error and have isolated it to this line of code:
`\server\model\maintenance.js` on line 300
`let start = dayjs(this.beanMeta.job.nextRun(dayjs().add(-this.duration, "second").toDate()));
`
If the interval is 5 or 7, this evaluates incorrectly (the dayjs obj element $d = `Tue Apr 16 2024 06:00:00 GMT-0400 (Eastern Daylight Saving Time)`, instead of the correct value, `Sat Apr 13 2024 06:00:00 GMT-0400 (Eastern Daylight Saving Time)`)
But, if the value is 6, or 4-1, then it evaluates correctly to `Sat Apr 13 2024 06:00:00 GMT-0400 (Eastern Daylight Saving Time)`.

My question is, what exactly is the `this.beanMeta.job.nextRun` function doing? Is it part of the `redbean-node` lib somehow?
I am new to contributing, so any help would be much appreciated.

**Comment by CommanderStorm** [comment]
Not quite. `beanMeta.job` is the [`croner`](https://github.com/Hexagon/croner/tree/master) instance for said maintenace period.

Said variable comes from here:
https://github.com/louislam/uptime-kuma/blob/05606c69e7feb7cf4c033e2eb7c6f43ca7d1c5d0/server/model/maintenance.js#L266-L268

To your question:

> what exactly is the `nextRun` function doing

Sadly, croners docs is not great, but hey..
https://github.com/Hexagon/croner/blob/aa932979a949258af2c8093e8af88f15d743342e/src/croner.js#L195-L204
=> the line finds the next runtime as dayjs, based on the current time-duration. I would need to look into if timezones are correctly passed here.

The duration is initialised here:
https://github.com/louislam/uptime-kuma/blob/05606c69e7feb7cf4c033e2eb7c6f43ca7d1c5d0/server/model/maintenance.js#L390-L436

**Comment by buzzinJohnnyBoi** [comment]
Thank you for that info, @CommanderStorm, I think I can solve the issue now, here is my approach: 
The task will run at the selected time, every possible day, but in the args for the `new Cron()` I will include the `interval` param, which will be the time for 5, 7, or whatever interval of days. I will also include the `startAt` in the args.
This will work for any date that is in the future, as it will start on the start date and then continue on every interval after that.
However, if the date is in the past, then it will start as soon as possible, so today or tomorrow.
This problem is solved if the date for the next maintenance start date/time is calculated. 
E.g. if the start day is Apr. 14, 2024, (4 days ago) for a 6 day interval, then it will recalculate the start date for the cron to be Apr 20th.
Below is some sample code to demonstrate this.
Please let me know if this approach makes sense, and if it does, I will incorporate these changes and hopefully commit the changes soon :)

```javascript
import { Cron } from "croner";

const intervalInDays = 6;

let startDate = new Date('2024-04-14T07:00:00Z');

const hour = startDate.getUTCHours();
const minute = startDate.getUTCMinutes();

const cronString = `${minute} ${hour} * * *`;

const task = () => {
    console.log("Running task");
};

const now = new Date();
if (startDate < now) {
    const differenceInDays = Math.ceil((now - startDate) / (1000 * 60 * 60 * 24));
    const numberIntervalsSinceStartDate = Math.ceil(differenceInDays / intervalInDays);
    startDate.setDate(startDate.getDate() + numberIntervalsSinceStartDate * intervalInDays);
}

console.log(`This will run every ${intervalInDays} days, starting from ${startDate}`);

const job = new Cron(cronString, { interval: intervalInDays * 24 * 60 * 60, startAt: startDate.toISOString() });

job.schedule(task);

console.log(job.nextRuns(5));

```

**Comment by CommanderStorm** [comment]
Could you provide a PR instead? Revieingg what has to be changed is more error prown than nessesary via comments..

**Comment by buzzinJohnnyBoi** [comment]
Hi, @CommanderStorm, the PR should be ready for review. I did not use the strategy described above, instead I had to re-calculate the Cron every time the maintenance task is run. While it is not optimal because code needs to be added for only that strategy, it works for every use case.

**Comment by buzzinJohnnyBoi** [comment]
I fixed the `croner` lib to a point I can test with it, but I was wondering about the scope so I don't commit code that is unnecessary.
I have currently changed the `maintenance.js` file so that whenever the Start Date/Time is (future or past), it will base the interval off that.
However, since it is only checking if it should be running every `x` number of days, then in some scenarios it might not be perfect.
Consider the following: 
`Maintenance Time Window of a Day`: 10:00-12:00
`Interval`: 7 days
`Start Date`: May 23
`Current Time`: (when saving the maintenance window) 11:00, May 23
Result: since the program is only going to check if it should be running every 7 days, (starting from May 23, 10:00), then the next time it will run is May 30, 10:00 since the time it was supposed to start as was in the past.
Also, if Uptime Kuma goes down for a minute when the maintenance window is supposed to start, then it will not run for that entire period.
A solution to this would be to add a check if the current time is between the start and end time when saving the interval, then set the cron to something that will be able to run throughout the period. e.g. `0 10 23 5 *` with no interval, and then when the maintenance window is complete, re-calculate the cron.
Let me know if this would be necessary or if the existing fix will be sufficient. @CommanderStorm @chakflying

**Comment by buzzinJohnnyBoi** [comment]
So, croner is now at version [8.1.0](https://github.com/Hexagon/croner/releases/tag/8.1.0), which includes the changes with interval, hopefully allowing me to resolve this issue :)
Let me know if my above ^^^ concerns are something to be addressed or if it is fine the way it is.
