### ISSUE TITLE
How can I change the Ntfy title and description notification?

### ISSUE THREAD

**Issue by volkankoc** [louislam/uptime-kuma#4643]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to change the Ntfy title and description notification

![image](https://github.com/louislam/uptime-kuma/assets/22777823/c61e5273-d98d-452b-b7d0-4a629cb0db59)

### 📝 Error Message(s) or Log

no error log

### 🐻 Uptime-Kuma Version

1.23

### 💻 Operating System and Arch

Windows

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime:  Exe
- Database:  Sqlite
- Filesystem used to store the database on: ssd
- number of monitors: 1

**Comment by CommanderStorm** [comment]
Currently this is not possible.

https://github.com/louislam/uptime-kuma/blob/effd0197ac9899ff6574810189755d62e81c71d1/server/notification-providers/ntfy.js#L53-L55

Allowing for templating in notification providers is tracked in https://github.com/louislam/uptime-kuma/issues/646

**Comment by volkankoc** [comment]
Thank you but i using exe version. How is  i make

**Comment by CommanderStorm** [comment]
We dropped the support for the windows exe version due to the pains that antivirus false-positives caused.
See https://github.com/louislam/uptime-kuma/issues/3142 for further context.

Please consider moving to a supported deployment.
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

> How is i make

What are you asking here?
As stated above, allowing for templating in notification providers is tracked in https://github.com/louislam/uptime-kuma/issues/646. Please read through said issue. ^^
Currently, we don't have templating support for notifications.
