### ISSUE TITLE
What is the proper way to migrate from PM2 to Docker?

### ISSUE THREAD

**Issue by waitwhatActo** [louislam/uptime-kuma#4675]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to migrate from PM2 to Docker, whilst keeping all my data, settings, etc. Is there a way to do it, and if so, how should I go about it?

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04 x86_64

### 🌐 Browser

Microsoft Edge 123.0.2420.65

### 🖥️ Deployment Environment

- Runtime: Node.js 20.12.2
- Database: Unsure, whatever the Node.js installation methods uses by default
- Filesystem used to store the database on: Ubuntu on an SSD
- number of monitors: 62

**Comment by CommanderStorm** [comment]
- Shut down PM2
- make a backup of the data folder
- copy data to the docker containers storage (bind to a local volume instead of a named volume instead for simpler transition)
- start docker container with said data

What is likely (have not tested what would happen) important is that you are not using the PM2 specific monitor tailscale.
