### ISSUE TITLE
prometheus metric `monitor_cert_days_remaining` missing after update to 1.23.12

### ISSUE THREAD

**Issue by DerGary** [louislam/uptime-kuma#4698]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/4693
- https://github.com/louislam/uptime-kuma/issues/2455

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

after update to 1.23.12 monitor_cert_days_remaining is not exported anymore, it is still shown in the dashboard.

### 👟 Reproduction steps

use 1.23.12 and create monitor for an https website

### 👀 Expected behavior

monitor_cert_days_remaining is exported as in version 1.23.11

### 😓 Actual Behavior

the monitor_cert_days_remaining metric is missing

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

debian/docker

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.7
- Database: embedded
- Filesystem used to store the database on:  
- number of monitors: 5

**Comment by CommanderStorm** [comment]
Are you using a proxy or plain http?

**Comment by DerGary** [comment]
Plain https

**Comment by CommanderStorm** [comment]
This bug was likely introduced by https://github.com/louislam/uptime-kuma/pull/4630 and is likely caused by a timing issue between

https://github.com/louislam/uptime-kuma/blob/e797abd10836e4724881d345e04a1306cab4fe07/server/model/monitor.js#L517-L519

and

https://github.com/louislam/uptime-kuma/blob/e797abd10836e4724881d345e04a1306cab4fe07/server/model/monitor.js#L1013

**Comment by Krafting** [comment]
I have a dashboard in grafana, and I don't have the stats (for the metrics below) anymore since the Update 

`monitor_cert_is_valid` and `monitor_cert_days_remaining`
