### ISSUE TITLE
uptime does not detect the certificate

### ISSUE THREAD

**Issue by scomper** [louislam/uptime-kuma#4701]
### 📑 I have found these related issues/pull requests

Searched but no relevant questions found

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The certificate for the website redmine.v-call.cn is not detected by uptime.
The certificate has been installed and is displayed correctly in the browser, but uptime does not detect the certificate.

https://www.racent.com/ssl-check?q=redmine.v-call.cn
![CleanShot 2024-04-22 at 10 35 10@2x](https://github.com/louislam/uptime-kuma/assets/13041847/5e09fdc3-27e2-4815-a549-7c1d8ac8fecc)

### 👟 Reproduction steps

Adding monitoring for redmine.v-call.cn does not show the expiration date of the certificate.

### 👀 Expected behavior

It feels like uptime doesn't detect this domain as having a certificate.

### 😓 Actual Behavior

![CleanShot 2024-04-22 at 10 34 13@2x](https://github.com/louislam/uptime-kuma/assets/13041847/121bec41-8083-40a1-b9ff-29badb09cdb7)

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

macOS 14.5 23F5059e

### 🌐 Browser

Chrome 124.0.6367.62  (arm64)

### 🖥️ Deployment Environment

OrbStack info:
  Version: 1.5.1
System info:
  macOS: 14.5 (23F5059e)
  CPU: arm64, 8 cores
  CPU model: Apple M1

**Comment by scomper** [comment]
Upgrading to version 1.23.12 solved the problem, anyway, thanks a lot!

**Comment by CommanderStorm** [comment]
This was one of the bugs that we have fixed in the last release.

Please update your uptime kuma version to the most recent one and report back if this does not resolve your issue.
I am going to close this as I think this resolves this issue.

Reasons where you might want to wait for the release after that:
- you have weird locales (3 letter locales or the first one being English with valid fallback locales)
- or proxys
- or you scrape the metrics endpoint
