### ISSUE TITLE
Please use meaningful HTTP Codes in different answers

### ISSUE THREAD

**Issue by GAS85** [louislam/uptime-kuma#4740]
### 📑 I have found these related issues/pull requests

E.g. #3754

### 🏷️ Feature Request Type

API / automation options

### 🔖 Feature description

Use HTTP codes in API that are relevant to the action. E.g. currently everything is `200`. Even when User tries to login with wrong User name or Password, answer on a `POST` Request will be `200` with body `ok`. But it is not ok :smile:.

### ✔️ Solution

Here answer should be `401` Unauthorized. This will help to improve service with e.g. Fail2ban or any status monitoring systems.

**Comment by CommanderStorm** [comment]
But 200 is correct:
- Since Uptime Kuma is a single page application (SPA), technically the server always return `index.html`
 => `200 - OK`.
- the connection with the `socket.io` server is successfull
  => `200 - OK`

We don't have a `POST` Request for the login field. Idk what you are talking about.
The only `POST` (which is returning `ok` => you likely looked at this part) is happening as part of the `socket.io` workaround for broken websockets (i.e. the websocket upgrade mechanism):
https://socket.io/docs/v3/how-it-works/#http-long-polling

This login information is send via the websocket connection (as the rest of the apps communication):

![Screenshot from 2024-05-04 15-53-30](https://github.com/louislam/uptime-kuma/assets/26258709/f9cb17e9-469d-40d2-bd93-1f04c1bb53a7)

See https://github.com/louislam/uptime-kuma/issues/759 for another issue in the same.

**Comment by CommanderStorm** [comment]
> This will help to improve service with e.g. Fail2ban [...]

Can you provide a CONCRETE example? Fail2ban reads logfiles and blocks ip adresses accoding to https://github.com/fail2ban/fail2ban
=> the status code should not matter

> This will help to improve service with e.g. [...] any status monitoring systems.

Please provide further details.

**Comment by GAS85** [comment]
I see, when Webservices are broken there is a POST Request:
![изображение](https://github.com/louislam/uptime-kuma/assets/6813635/ee91dff7-bd5e-4fa1-8af8-6185ec8aa693)

Basically even in standard fail2ban package there are few services preconfigured with even exact 401 error:

- [Openhab](https://github.com/fail2ban/fail2ban/blob/c04e12dd8de0eaa3851da76d476c5c0c69dfe2d6/config/filter.d/openhab.conf#L10)
- [HAProxy](https://github.com/fail2ban/fail2ban/blob/c04e12dd8de0eaa3851da76d476c5c0c69dfe2d6/config/filter.d/haproxy-http-auth.conf#L31)
- [Traefik](https://github.com/fail2ban/fail2ban/blob/c04e12dd8de0eaa3851da76d476c5c0c69dfe2d6/config/filter.d/traefik-auth.conf#L59)

And basically many more with some manual setup, e.g. [Harden Nextcloud 17+ with Fail2Ban, GUI and WebDAV - Ubuntu 20.04](https://gist.github.com/GAS85/957e0b1a4f30120225a7be09b173eb24)

**Comment by CommanderStorm** [comment]
> there are few services preconfigured with even exact 401 error

Well there are also a few configured with the messages that we already publish as noted in https://github.com/louislam/uptime-kuma/issues/3754#issuecomment-1722419358
See [Bitwarden](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/bitwarden.conf) for example..

I don't see value in refactoring the login page to `POST`'ing with `200`/`401` responses.
This should be solvable with the tools that we already supply...

**Comment by GAS85** [comment]
This can work too, thanks 😀
