### ISSUE TITLE
Security advisory

### ISSUE THREAD

**Issue by Tchebychev** [louislam/uptime-kuma#4784]
DO NOT PROVIDE ANY DETAILS HERE. Please privately report to https://github.com/louislam/uptime-kuma/security/advisories/new.

Why need this issue? It is because GitHub Advisory do not send a notification to @louislam, it is a workaround to do so.

Your GitHub Advisory URL: https://github.com/louislam/uptime-kuma/security/advisories/GHSA-5hjg-3v4v-3cx7

**Comment by louislam** [comment]
The advisory is closed, but I think it is a good question, I make it public to see what other people think.

@Tchebychev is concerning plaintext storage of sensitive information inside the SQLite database like PostgreSQL monitor's password.

But I didn't encrypt them, because I think encrypting them is meaningless, as the encryption key will be in the same data directory. If an attacker can read your SQLite database, they can probably get the encryption key to decrypt the information too.

Unlike user password hashing (one-way hashing), passwords can still be verified after being hashed. But for a PostgreSQL password, Uptime Kuma would have to decrypt it to connect to the PostgreSQL database. That is the difference.

**Comment by louislam** [comment]
From the advisory:

> PoC
I carried out this test in a Pod running on Openshift:
    Connection to the uptime kuma Pod terminal
    sqlite3 /app/data/kuma.db
    select * from monitor;
    This command displays this:

From another perspective, a lot of deployment methods like `.env`, `docker-compose.yaml` or hardcoded password inside a source code program are also in plain text. 

So, I think we need a strong reason why storing a plain text password in a .env file is considered acceptable, but Uptime Kuma is not ok.

**Comment by CommanderStorm** [comment]
I have writtten my take on this one here: https://github.com/louislam/uptime-kuma/issues/4778#issuecomment-2124913962

=> lets continue any discussion there

**Comment by CommanderStorm** [comment]
Plese respect my comment from above, lets continue the discussion in https://github.com/louislam/uptime-kuma/issues/4778

**Comment by CommanderStorm** [comment]
> You have closed both this issue and the other as completed

I think I have made my point that
- [mariadb offers encryption at rest](https://mariadb.com/kb/en/data-at-rest-encryption-overview/) (thus we don't need to add that if a user uses that storage) and
- how reopening https://github.com/louislam/uptime-kuma/issues/4778 for `SQLITE-SSE` (looks complicated to me and not knex-compatible, but maybe a database person can help us with this) is somewhat pheasable.

Discussing stuff in two issues simultaneously does not really have a point => lets continue the discussion in https://github.com/louislam/uptime-kuma/issues/4778
If you really want we can make that into a discussion issue..
