### ISSUE TITLE
How to heal these vulnerabilities?

### ISSUE THREAD

**Issue by MeandraX** [louislam/uptime-kuma#4793]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After running a vulnerability scan with the $ npm audit command, 4 vulnerabilities with high severity were detected. I ran the $ npm audit fix command, even forcing it by adding --force to the command, but it fails to fix these vulnerabilities.

### 📝 Error Message(s) or Log

![vulnerabilities_and_version](https://github.com/louislam/uptime-kuma/assets/170633474/3a46fe94-07cc-430e-a1ae-8306697a15df)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
The problem comes from the fact that https://www.npmjs.com/package/node-radius-client has been abandoned and no suitible alternative exists.

> [!CAUTION]
> `npm audit fix --force` is VERY desructive.
> I would never recomend using said command. It most likely will brick the part of the systme you want to fix.
> As with all vulnerabiliy reports, looking into if you are actually vulnerable is very important.

https://www.npmjs.com/package/node-radius-client does not use the clone function from `hoek` and is therefore NOT vulnerable to the prototype pollution.
=> not a security issue

Please see the comments from 
- https://github.com/louislam/uptime-kuma/issues/3319

> I don't see maintaining a radius client ourselves as a viable strategy.
Currently, there is no viable alternative.
Unless vulnerabilities are found in `node-radius-client`, I would tend to stick to it.
> 
> The only alternative out there seems to be https://github.com/retailnext/node-radius, which has
> - a GitHub page
> - but hasn't had a meaningful commit in the past 6 years 

> Yes, I don't see any better replacements on npm too at this moment. Feel free to open a new feature-request in the future if someone make a new and better library for this.
