### ISSUE TITLE
If host's dns fails, no notifications are sent

### ISSUE THREAD

**Issue by roughnecks** [louislam/uptime-kuma#4858]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,
today I made a change to my VPS that caused systemd-resolved to fail with `;; communications error to 127.0.0.53#53: timed out`

No notifications were sent because no service resolved anymore. I found out about the issue only later and by chance only.
Currently I have xmpp, matrix and mail notifications.

As soon as I restored dns functionality, several emails about services being up again arrived to my inbox.
Am I doing something wrong or a workaround exists?

Thanks

### 🐻 Uptime-Kuma Version

Versione: 1.23.13

### 💻 Operating System and Arch

Debian 12 x64

### 🌐 Browser

Chrome Versione 125.0.6422.142 (Build ufficiale) (a 64 bit)

### 🖥️ Deployment Environment

- Runtime: Docker version 26.1.4, build 5650f9b, nodejs v18.19.0

**Comment by CommanderStorm** [comment]
> Am I doing something wrong or a workaround exists?

If we can't send notifications to the outside due to not having internet connectivity, we can't send notifications via the internet.

There are a few notification providers that don't require this. See the SMTP monitor for one of them. See https://github.com/louislam/uptime-kuma/issues/2793 for further details.

I don't see us not having internet connectivity as something fixable/monitorable by us. I would recommend to have a second instance somewhere in a different location monitoring uptime-kuma (["who watches the watchers"](https://en.wikipedia.org/wiki/Who_Watches_the_Watchers))

Think this resolves your question. If anything is unclear, feel free to reach out ^^
