### ISSUE TITLE
Update the container to Bookworm

### ISSUE THREAD

**Issue by TommyTran732** [louislam/uptime-kuma#4885]
### 📑 I have found these related issues/pull requests

The container currently uses Buster which is EOL. There are lots of vulnerabilities from security scans. It would be better if it can be upgraded to Bookworm, or preferably moved to a more sensible base distro.

### 🏷️ Feature Request Type

Deployment

### 🔖 Feature description

Update to Bookworm

### ✔️ Solution

Build the container to Bookworm

### ❓ Alternatives

Use a more sane OS for the base distro

**Comment by CommanderStorm** [comment]
V2.0 has upgraded to bookworm. See #4500 for the status on this release
https://github.com/louislam/uptime-kuma/blob/master/docker/debian-base.dockerfile

OS level flaws are very seldomely exploitable.
If there is a concrete thing you are worried about, we can discuss that. Otherwise I don't think this is something to worry about/invest time into.
