### ISSUE TITLE
Include Status Pages on export

### ISSUE THREAD

**Issue by chmichael** [louislam/uptime-kuma#4976]
### 📑 I have found these related issues/pull requests

Haven't found related topic

### 🏷️ Feature Request Type

Settings

### 🔖 Feature description

Hello,
  Please add an option to Include Status Pages on export/import.

Thank you

### ✔️ Solution

Include Status Pages data into the export json or create new format.

**Comment by CommanderStorm** [comment]
Closing as a duplicate/resolved.
In-depth answer:

Please see https://github.com/louislam/uptime-kuma/issues/2141#issuecomment-1272360952

> In 1.18.3, the backup feature was deprecated due to [being left] unmaintained.

Backup & Restore with JSON has been deprecated and issues will not be fixed due to the amount of problems it has been causing for our users and us.
The current design is just not maintainable, causing countless bugs.
In `v2.0` the deprecated backup tool is being removed because of this reason.
Please consider using SQL, API based[^1] or infrastructure based[^2] backup instead. 

New approaches to these features should use [SQLite dump](https://www.sqlitetutorial.net/sqlite-dump/) or [MariaDB dump](https://mariadb.com/kb/en/mariadb-dump/) respectively. (Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md))

You can subscribe to these issues meanwhile:
- #2496
- #477

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
[^2]: see https://github.com/louislam/uptime-kuma/issues/477#issuecomment-1557966187 for a setup example
