### ISSUE TITLE
How to change port?

### ISSUE THREAD

**Issue by iconoclasthero** [louislam/uptime-kuma#5003]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

3001 is not going to be open.
there are no instructions for how to change that if you're not using docker.
please explain how this is done and at least put it in the advanced install instructions so that when i search for port in the instructions it shows up in the git/npm/pm2 install section.

### 🐻 Uptime-Kuma Version

i don't know, i can't get it to run yet

### 💻 Operating System and Arch

rhino

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

nothing, i can't get it to start because i can't change the port.

**Comment by iconoclasthero** [comment]
https://github.com/louislam/uptime-kuma/wiki/Environment-Variables
says: `node server/server.js --host=127.0.0.1 --port=8080`
but 
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
says: 
```
# (Recommended) Option 2. Run in the background using PM2
# Install PM2 if you don't have it:
npm install pm2 -g && pm2 install pm2-logrotate

# Start Server
pm2 start server/server.js --name uptime-kuma
```
and 
pm2 says:
```
pm2 start server/server.js --port=3066

  error: unknown option `--port'
```

so that's not super helpful.

So going back to the wiki:
`(1.20.0) For non-Docker users, you can create a new file named .env in the root directory. The format is like this:`

In the root directory **of what?**

**Comment by iconoclasthero** [comment]
a lot of things in this general self-hosted ecosystem use 3000, 3001, invidious, mstream to name two.
first of all, why are you using 3001 at all?  it's very likely whatever someone wants to monitor is already using it.

second, where is the config file to set this?  running with systemd I at least can use it's tools to systemctl edit updae_kuma and look at where the config file is...

**Comment by CommanderStorm** [comment]
If you are concearned with simplicity, I would suggest choosing the preconfigured docker environment instead of dealing with native dependencys.

Below, you are passing the `--port` option to [`pm2`](https://pm2.keymetrics.io/). Since pm2 does not have such an option, that won't work.

```
pm2 start server/server.js --port=3066

  error: unknown option `--port'
```

The canoncal way of configuring these options using `pm2` is documented here: https://pm2.keymetrics.io/docs/usage/environment/

If you want to configure this via the `.env` file, please put that at the root of the project that you cloned.

About the docs: PRs appreciated. It is really hard to keep up with issues, let alone providing fixes and documentation.

**Comment by sohitdeveloper** [comment]
while writing the docker-compose file or running the container, you can pass your desired host container.
