### ISSUE TITLE
Website with working ipv4 address, and non-responsive ipv6 address, will show as "down" on monitor

### ISSUE THREAD

**Issue by ShadowJonathan** [louislam/uptime-kuma#5006]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/1242 and
- https://github.com/louislam/uptime-kuma/issues/4914 seem to be related, but both don't address my issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

1. Have a website with both an A and AAAA record
2. Have the IP behind the A record be responsive, but the IPv6 behind the AAAA record be unresponsive

### 👀 Expected behavior

Uptime-kuma would happy-eyeballs (or similar) both IP addresses resolved behind the domain name, and try to hit either.

### 😓 Actual Behavior

The HTTP request fully fails, and times out.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian 12, Docker

### 🌐 Browser

Arc

### 🖥️ Deployment Environment

- Runtime: Docker 20.10.24+dfsg1
- Database: Sqlite
- Filesystem used to store the database on: EXT4
- number of monitors: 44 (incl. groups)

**Comment by CommanderStorm** [comment]
The node version shipped in v1.23.x does not have happy eyeballs support.
v2.0 bumps that to a version that includes happy eyeballs and should resolve this issue.
See #4500 for further details what needs to happen before we can publish that release.

Since this is likely resolved in v2.0 I am going to close the issue as resolved.
