### ISSUE TITLE
Considerations when running from a static source

### ISSUE THREAD

**Issue by robdejonge** [louislam/uptime-kuma#5027]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm looking to run Uptime Kuma on a router where each time I reboot, all changes to the filesystem get lost. The idea is that once I've configured it, I'll package up `/app/data` and every time it gets started it will basically reset to that packaged configuration. This limitation is due to the router hardware. 

The version of Uptime Kuma will be static, so database changes across versions will not be an issue. 
The monitors configuration will rarely be edited, but when I do I'll do this in a shadow config and repackage `/app/data` again.
Filesystem writes are possible, a RAM disk will be created to host this filesystem. 

One question I already have is how I can clear `/app/data` of historical monitor data, so that I have a 'clean package' (insert pun here). 

I'm looking for some advice on what other considerations I should be thinking about in preparing for this install. 

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

RouterOS / ~Debian @ armv7

### 🌐 Browser

Safari

### 🖥️ Deployment Environment

- Runtime: RouterOS custom docker environment (dont know the details), using your official Docker container
- Database: kuma.db
- Filesystem used to store the database on: RAM disk 
- number of monitors: "a dozen or two"

**Comment by robdejonge** [comment]
Regarding 'clearing historical monitor data' ... when I browse the data in kuma.db, it looks like clearing the `heartbeat` table would suffice at least at this very moment?

**Comment by CommanderStorm** [comment]
I would recommend to buy a raspberry pi and put it next to the router. Much less work in the long run. (Value your time)

Heartbeats are stored in the heartbeat table. Deleting them should not have consequences other than deleting heartbeats ^^

Regarding the file, that is a temporary file by sqlite.
It is not encrypted as assumed.
See https://www.sqlite.org/tempfiles.html
If you can delete it might depend on your data-loss tolerance and how graceful you shut down the DB.
Since no such file extension is documented you have likely made a typo in the reported filename
