### ISSUE TITLE
Public event sending for nostr

### ISSUE THREAD

**Issue by kehiy** [louislam/uptime-kuma#5035]
### 📑 I have found these related issues/pull requests

not found

### 🏷️ Feature Request Type

Change to existing notification-provider

### 🔖 Feature description

I think the Nostr notifications must support public sending as well. It will send a public event for service changes. 

### ✔️ Solution

We can add a new feature for the Nostr provider to publish event's based on NIP-1 without encryption and receiver.

**Comment by CommanderStorm** [comment]
This is kind of niche/uncommon notification provider.
If you/someone else would like to contribute such a provider, here is the Contribution guide:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md 

=> A contribution for whatever you need from that provider would be appreciated

For notification providers the testing effort is mostly offloaded to the contributor side (otherwise this does not scale)
=> Please make sure to include the screenshots we request in the contribution guide
