### ISSUE TITLE
Restore Import Backup

### ISSUE THREAD

**Issue by water2022** [louislam/uptime-kuma#5045]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I changed my server and now I need to import backup files from another server, what is the best way to accomplish this now?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian12

### 🌐 Browser

google

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
The backup feature is depcrecated and should not be used. Please
- shut down the instance,
- transfer the `data` folder,
- do a checksum check to ensure successfull transmission to the new machine and
- then start it up at the new place.

A more in-depth explanation:

Please see https://github.com/louislam/uptime-kuma/issues/2141#issuecomment-1272360952

> In 1.18.3, the backup feature was deprecated due to [being left] unmaintained.

Backup & Restore with JSON has been deprecated and issues will not be fixed due to the amount of problems it has been causing for our users and us.
The current design is just not maintainable, causing countless bugs.
In `v2.0` the deprecated backup tool is being removed because of this reason.
Please consider using SQL, API based[^1] or infrastructure based[^2] backup instead. 

New approaches to these features should use [SQLite dump](https://www.sqlitetutorial.net/sqlite-dump/) or [MariaDB dump](https://mariadb.com/kb/en/mariadb-dump/) respectively. (Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md))

You can subscribe to these issues meanwhile:
- #2496
- #477

[^1]: using the third-party API: https://uptime-kuma-api.readthedocs.io/en/latest/
[^2]: see https://github.com/louislam/uptime-kuma/issues/477#issuecomment-1557966187 for a setup example

**Comment by water2022** [comment]
![无标题](https://github.com/user-attachments/assets/cc8072ed-b32e-4aeb-896e-6a912ee0036b)
Hi, which file exactly is being migrated?

**Comment by CommanderStorm** [comment]
Your screenshot shows the directory in which docker stores all (?) it's data.
You want the volume where you mounted the `data` folder instead.
