### ISSUE TITLE
Verify connectivity of host before the notifications

### ISSUE THREAD

**Issue by guionardo** [louislam/uptime-kuma#5067]
### 📑 I have found these related issues/pull requests

I've not found related issues.

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

The constant verification of internet access to host must occurs before every monitor execution. 
In the case of missing internet access, false positives on the monitors will be reported.

### ✔️ Solution

In every loop, kuma must check if this internet connection is healthy and if not, register it in logs, pausing the monitors.
When the internet connection is OK, logs the recovery and continues running the monitors.

### ❓ Alternatives

I think the condition of checking the internet connection health is a simple e functional solution.

### 📝 Additional Context

Nothing more to consider.

Thanks

**Comment by CommanderStorm** [comment]
Please refer to https://github.com/louislam/uptime-kuma/issues/1089

**Comment by GitBaer** [comment]
Since the solution for "Dependent monitoring of hierarchical monitors" (https://github.com/louislam/uptime-kuma/issues/1089) probably won't be implemented quickly, I urgently request that a feature be added to check for network connectivity before marking a monitor as "down." This could be done, for example, by using two reference servers.
