### ISSUE TITLE
40+ URLS - The dashboard showing nothing

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [louislam/uptime-kuma#5079]
### 📑 I have found these related issues/pull requests

We have added 40+ urls, after that whenever we hit the home page, it showing nothing. We have to wait for 15mins then it'll load all the URLS.

![image](https://github.com/user-attachments/assets/91d04b7c-65b1-4d85-9720-50cebfddb9d9)

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

Add 40+ URLs

### 👀 Expected behavior

Home page should load

### 😓 Actual Behavior

Not able to see any URLs

### 🐻 Uptime-Kuma Version

 1.23.11

### 💻 Operating System and Arch

Ubuntu 24

### 🌐 Browser

Chrome - Latest

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by craeckor** [comment]
Had the same issue.
This is (i believe) because of the database being too big. After like 500MB it will start to lag extremely hard and the page will become very unresponsive because...
No idea.
Either try to decrease all of your Heartbeat Intervals or decrease your Monitor History and then try to shrink your database. This should help. Now, my databases is like ~240MB and it works fine.

**Comment by CommanderStorm** [comment]
Please see #4500 for recommendations how to get around the performance limitations if V1. You are likely using pretty slow disks when you are hitting this at 40 monitors.

Without further evidence to the contrary, I think this is done.
=> Closing as resolved
