### ISSUE TITLE
Insert/Copy curl of request

### ISSUE THREAD

**Issue by unuchak** [louislam/uptime-kuma#5116]
### 📑 I have found these related issues/pull requests

no

### 🏷️ Feature Request Type

New monitor, Change to existing monitor

### 🔖 Feature description

Add possibility to insert new monitor as curl and add possibility to copy curl of request.

### ✔️ Solution

Add possibility to insert new monitor as curl and add possibility to copy curl of request.

**Comment by CommanderStorm** [comment]
Inserting as curl is fairly difficult given the plethora of protocols/crypto-backends/.. that curl supports.
Partial support via parsing of the command would create a different can of worms. I don't think we should touch this at the moment.

Copying the command (and generally better debugging functionality) is something that I would love to see a PR on. => Marking as a good first issue because I think this should be fairly straightforward. I think a good basis would be a `debug` button next to the safe button which opens a modal (to have a place to put explainaining text) with a copyable text field with the curl command. No backend changes should be nessesary

**Comment by nekojanai** [comment]
I would like to take this on if possible
```
  I think a good basis would be a debug button next to the safe button which opens a modal (to have a 
  place to put explainaining text) with a copyable text field with the curl command. No backend 
  changes should be nessesary
```

I would implement it exactly as described above.
`src/components/Confirm.vue`
seems to already use some form of modal I would take the template from there and adjust it for this use case.

**Comment by CommanderStorm** [comment]
> I would implement it exactly as described above.

Thanks, much appreciated. The template to go from seems like a good bet ^^

> For DNS I would use something like `dig` instead

Yea, that would make sense. Have not thought about this.
If you have time for that, that would be awsome (if not, someone else can do this in another PR => loadsharing is a superpower of open source)

**Comment by CommanderStorm** [comment]
Our contribution guide (includes how to setup a dev environment) is [here](https://github.com/louislam/uptime-kuma/blob/b287a25de735d14c6e078d57e99b4587f10697cd/CONTRIBUTING.md). Feel free to ping me if there is anything unclear (being unclear in the docs is a bug too) or you have other questions 😉

**Comment by Anurag0218** [comment]
is this issue still open? is anyone working on it? If not, can I take it up?

**Comment by CommanderStorm** [comment]
Shure, nobody else has commented or provided a PR for this ❤️

**Comment by Itachii27** [comment]
Hi @CommanderStorm I want to work on this issue. Kindly assign this to me.

**Comment by nekojanai** [comment]
@Itachii27 I'm already working on this?
see https://github.com/louislam/uptime-kuma/issues/5116#issuecomment-2369864760

**Comment by nekojanai** [comment]
Is there an easy way to update translation strings?
