### ISSUE TITLE
Use `pingdom_http_custom_check` to optain more information about the server

### ISSUE THREAD

**Issue by jmros** [louislam/uptime-kuma#515]
Use pingdom estatus to optain more information about the server

example:
```html
<pingdom_http_custom_check>
<status><strong>OK</strong></status>
<response_time><strong>96.777</strong></response_time>
</pingdom_http_custom_check>
```
https://jonsview.com/how-i-use-pingdoms-http-custom-feature

**Comment by CommanderStorm** [comment]
I am not convinced that this would make for a good feature.
Instead, this would be quite messy to implement and maintain.

You can already achieve these results via the `push` monitor without the extra mess of adding `xml` parsing.
If you return `json` instead of `xml` you can use the `json-query` monitor.

I am going to close this issue as a `wontfix` due to not really seeing why this is useful or significantly different compared to the current (idk when we implemented them) alternatives.
