### ISSUE TITLE
Multiple status page

### ISSUE THREAD

**Issue by loan-talvat** [louislam/uptime-kuma#530]
It would be perfect to be able to create several status pages with or without password and to choose the monitors to display

**Comment by adumont** [comment]
I was also looking into this same Feature 👍 .

**Comment by TheoCouss** [comment]
Waiting about that

**Comment by LoanDEV** [comment]
> 
> 
> @raphaelbernhart
> 
> Thanks, but I recommend that you should not implement it.
> 
> It is because I made a big wrong assumption that there should be only one status page in the current implementation. Changing from single `one-to-one` relation to `one-to-many` relation is super hard.

I think you shouldn't be pessimistic, anything is possible and clearly it's not such a big development

**Comment by pepa65** [comment]
It looks like this is the big one. Apart from integrating polling from multiple locations, this feature is what would make this super pro.

In the final analysis this is only a display issue. You could always create an extra table -- but any database change means that upgrading needs to check if the olde database needs changing.

**Comment by ebanDev** [comment]
This could be reaaally awesome ! :D

**Comment by mikespears** [comment]
This would be an amazing feature to have.

**Comment by raphaelbernhart** [comment]
> @raphaelbernhart @louislam Did you got any progress yet on this topic? I created by accident a duplicate issue (after searching your issue didn't show in results for some reason). So I'm also eager to have a multi-statuspage feature.
> 
> What is actually holding back the development for this? Are we hold up by a database scheme issue? Because those things can be workaround by creating migrating scripts to ensure no data gets broken when moving from single to multi. Not saying it is easy peasy done, but its also not impossible. But we need at least some feedback on how we can move forward on this or at least know what community can do to help fix another base problem first. Otherwise we never get to see any progress on many more advanced features that just queue up.
> 
> One of the possibilities I see, is perhaps a temporary Docker container that runs a one off migration script to make sure everybody survives such upgrade.

Unfortunately not as I don't have time atm. Also I can't just change the database/backend structure of the whole project without permission from @louislam. As he mentioned above...changing the whole system and/or structure of a database isn't a easy task. You would have to:
- change the structure of the backend/db
- write the whole UI around it
- migrate the old systems to the new structure

There is a lot of room for bugs. So if we would to decide wether we update the db we have to consider all of these steps and we would have to form a team so that everybody can make a small part. F.e. I haven't done database migrations very often yet.

@louislam ?

**Comment by codeagencybe** [comment]
@raphaelbernhart 

Ah yes, for sure, we don't want to break anything obviously. But I think changing the database structure at this point in an early stage is much better than doing it later, making it even more harder. 

I think the first step is to re-look at the database for sure. And think about maybe other parts too that benefit from adding many2one or many2many relations. 
The UI rewriting is the last part. I think the steps required are like below

1. change the structure of the backend/db
2. migrate the old systems to the new structure (seperate one time Docker run effect or maybe a CLI script that user can run onetime on demand to upgrade)
3. write the whole UI around it


In terms of migrating data, I think this shouldn't be the biggest problem since changing from a single status page to multiple ones, is a fair straight forward migration. There is no risk involved in mixing up data etc... since there aren't any multiple status page yet. So that's a onetime effort to be done and we are good with that. 
The single status page will become the first one of multiple pages. 

The hard part comes in evaluating what other moving parts need to move along. Like metrics, events, etc... all of them need have many2many relations for status pages.

**Comment by codeagencybe** [comment]
@louislam Thanks for the PR!  Looking forward so much to this :D 
I have just donated 150$ to your project to help a little bit in making Uptime Kuma more succesful.

**Comment by xeruf** [comment]
Rather than focusing on a smooth migration, I would suggest you simply start working on this as version 2.0 with a new structure that incorporates the lessons learned in the past months, and think about migration once that is working.
