### ISSUE TITLE
Wow! Uptime Kuma is one of trending projects now!

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#590]
Just checking why it suddenly gain a lot of stargazers today and found that it is one of trending projects now!

Thank you so much! 🐻👍

https://github.com/trending

![image](https://user-images.githubusercontent.com/1336778/136366605-a2036cdd-9b64-40ea-9b1f-b88fd857db5c.png)

**Comment by proffalken** [comment]
It's a fantastic project, really appreciate the work that you're putting into keeping it all under control @louislam!

**Comment by i-am-gizm0** [comment]
@techno-tim did a video featuring this project the other day, so that's at least partly responsible

**Comment by rezzorix** [comment]
> 
> 
> @techno-tim did a video featuring this project the other day, so that's at least partly responsible

The reason for success:
The project is great, well managed and was the right thing at the right time for a demand that was urging for a tool like uptime-kuma.

So all praise to the developer and contributors rather than a youtuber with 60K followers.
No disrespect, all advertising is good, so every video that spreads the word is I believe highly appreciated.
But the project had already its momentum up (several hundred thousand if not already millions of pulls before the video went live).

**Comment by Drallas** [comment]
Great tool, very happy I found it!
