### ISSUE TITLE
Send notification every X minutes

### ISSUE THREAD

**Issue by pfrade1996** [louislam/uptime-kuma#594]
**Is it a duplicate question?**
I don't think so, I didn't find  it.
**Is your feature request related to a problem? Please describe.**
Yes, for example, when services go down in the middle of the night, they tend to get "buried" amongst other notifications.
**Describe the solution you'd like**
Perhaps a toggle to set "Send notification every X minutes" when a service goes down.
**Alternative Features**
Maybe disable alaramistic during a time period for certain services

**Additional context**
When we make backups some of the services have to go down in order to make a proper backup. This triggers alarmistic and makes it hard to go trough what is down in the morning without looking at the dashboard.

**Comment by CommanderStorm** [comment]
@pfrade1996 
Given that the currently live version of uptime-kuma ships with this option: 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/9c486e2c-9c2d-4b9a-844c-ba3ec744e0ad)

I think this is resolved.
If you agree, could you please close this Issue; otherwise this will become an immortal zombie, which are really hard to issue-manage.
