### ISSUE TITLE
AppRise Rest API notification support

### ISSUE THREAD

**Issue by 12nick12** [louislam/uptime-kuma#619]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add support for the apprise rest api that can be found [HERE](https://github.com/caronc/apprise-api).

**Describe alternatives you've considered**
The default apprise works great, but would love to be able to use it over a rest api

**Additional context**
None, other than thank you for the awesome product.

**Comment by LilTrublMakr** [comment]
I would also like to see this. I use the API in scripts and it makes it really easy to add or remove services in one place. All you would really need to add for configuration is a line for a url.

In my case, I have a configuration for SuperApp. It gets configured in the API using json or text file. All Uptime Kuma would be concerned with is being provided the notify url (http://example.com/notify/SuperApp) and then it would just use the same other info as the current Apprise notifier (title and message). 

If I wanted to change the services, I could change it in the API and not have to change anything in Uptime Kuma. 

Example UI to explain what I am trying to say since I suck at describing things:
![Screenshot 2021-12-03 221209](https://user-images.githubusercontent.com/54646041/144694900-c175b44e-7c7c-4807-84dc-3d924301b90d.png)

**Comment by louislam** [comment]
If you are using Docker, the latest version is bundled apprise 0.9.6 which is supporting apprise api.
https://github.com/caronc/apprise/wiki/Notify_apprise_api

**Comment by CommanderStorm** [comment]
Closing as resolved by https://github.com/caronc/apprise/wiki/Notify_apprise_api
