### ISSUE TITLE
Implement Templates for Notifications

### ISSUE THREAD

**Issue by deefdragon** [louislam/uptime-kuma#646]
## Is it a duplicate question?
This is a potential solution to a number of other issues, consolidating them into one, and has been discussed briefly in those other issues.

### Requests to have different information in the notification
#604, #582, #543, #524, #458, #456, #428, #262, #232, #208, #201, #172, #40 
Potentially a #570 work around
#543 Would be solved when writing the new templates
#117 in part. Some plugins could include custom actions via extending the filters that exist within liquidJS

### Potential long term bonuses/considerations
Having templates built up would allow for custom reports to be written like requested in #366 (requires a reports task system to be built up)
Would allow for inserting custom data into notifications like requested in #202 (would require saving of custom information for monitors/tags/groups/global etc.)

## Is your feature request related to a problem? Please describe.
The messages sent in notifications have several different components which many have requested the ability to modify parts of or all of, and each of which requires translation.

## Describe the solution you'd like
The implementation of a template engine such as [liquidjs](https://github.com/harttle/liquidjs) to allow users to customize the message sent as they see fit if they wish to do so. This would also condense the messages into as few formats as possible for translation. 

Some implementations such as Discord require an object to use the API. In this case, the template would be used to generate a JSON object that would then be parsed and used as the required object.

## Describe alternatives you've considered
#627 currently proposes adding regex-bassed key replacement in the email subject. It would also possible to leave the components individual and just customize/translate each one, but that would likely be a messy, hard to update solution.

## Additional context
I can see 4 major steps to this. 

1. Create the system to lookup, parse and return the templates
2. Alter notifications to use common, simple templates in their message
3. Alter front end & db to allow using custom templates
4. Implement global template setting

2 and 3 would have to done for the simple notifications, as well as for the JSON object implementations. 1 would basically be re-usable, however a fallback will be required in the case that the data returned from the template is not valid JSON.

I am willing to work on this, however I would like some input & other eyes before I do so. I want to make sure I am not going in the completely wrong direction. This is also a large enough change that, as has been mentioned, I want the sign off of @louislam before I go any further.

**Comment by louislam** [comment]
It would be really difficult in my opinion. I would suggest that it should be implemented it once we have a whole picture of it.

I have a similar thoughts before, but I can't think of a good approach, because there are a lot of formats here, for example:

- Line, Discord, Slack, Rocket.chat and more: All different JSON formats / payloads, also it is conditional (e.g. up = green, down = red).
- Email: subject and body

> 4. Implement global template setting

With this situation, how could global template be implemented?

> 3. Alter front end

For notification like Discord, how is it look like in frontend? Textarea with json?



For your information, currently, there are two usages of Notification.send(...);
https://github.com/louislam/uptime-kuma/blob/2a1fd93444d082e9d473f6548861d4aacd50dea6/server/notification.js#L74

1. General messages
```javascript
Notification.send(notification, "Hello👋");
```

2. Sending important up/down notifications
```javascript
Notification.send(notification, "[Test][🔴 Down] 404 Not Found", monitor, heartbeat);
```

**Comment by bakeDong1** [comment]
how about global variable like statping

**Comment by deefdragon** [comment]
So, I have started on this, and gotten a quick and dirty example to work.
While parsing the template in place of `msg` on line 328 can work, I am once again wondering if it would be better to put the template parsing inside `Notification.send`, and not 328.

I wonder this because I think that when a test notification is sent, it could include some mock objects for the monitor and heartbeat. Combined with parsing the template in `Notification.send`, the user will be able to not only test connection to the notification provider etc, but also be able to see what the notification will look like when received.

**Comment by deefdragon** [comment]
Question on translation: Do we have the a way to translate things server side? I'm not seeing any previous uses, and part of why I started this was so that the default templates could be translated.

**Comment by tiakun** [comment]
Would it be easier if this is implemented not globally but per notification type? It would also allow the customization per notification type, e.g. some users might want short message for SMS but longer messages for chat/message apps.

**Comment by deefdragon** [comment]
It would be easier, but it would make the notifications aspect of uptime kuma even more of a dis-congruous mess. 

The ideal would be to have a consistent notification form/message for everything, and while it's ok now, it could be much better. 

The thing is, there are other aspects of UK that should get worked on first (groups, notification controls/cascading etc). Louis only has so much time to test, and addressing the notifications system is rather low on the list.

I'm going to close this issue for now, as it is very likely not going to get addressed until a V2/notifications core code re-write.

**Comment by Qumans** [comment]
Since Feishu notifications can only fix templates, and I wanted to customize the content, I used webhook, and the url was the Feishu bot's webhook url. After clicking the test, it shows that the delivery was successful, but there is no message for my flying book. I can receive the flying book after testing with postman. And many times will appear Error: Error: getaddrinfo ENOTFOUND open.feishu.cn. Whatever the form of notification

**Comment by Qumans** [comment]
> 由于飞书通知只能固定模板，而我想自定义内容，所以我使用了webhook，url是飞书bot的webhook url。点击测试后显示发送成功，但是没有我的飞书的消息。经过邮递员测试后可以收到飞行书了。而且很多时候会出现Error: Error: getaddrinfo ENOTFOUND open.feishu.cn。无论何种形式的通知

Why did I not receive the message after kuma successfully sent it? Same url, same body, but I get messages through postman@

**Comment by borrelan** [comment]
Hello,

I would like to thank the team behind Uptime Kuma for such an awesome service that I have come to depend on. As this issue is ongoing, would you be willing to consider change the static entry of "[Uptime Kuma]" in the ntfy notification to include the "Friendly Name"?  When you have more than one instance pushing to the same topic it makes it difficult to determine which instance is pushing the notification.  One could also argue what's the point of the setting "Friendly Name" if it's not used?

Thanks again!!!

**Comment by realies** [comment]
<img width="251" alt="Screenshot 2024-08-30 at 02 52 16" src="https://github.com/user-attachments/assets/3776a1ab-6af7-4e02-8292-704881e8fb0d">
i see a lot of text duplication when i add a slack webhook - the notification friendly name is Uptime Kuma and the webhook name is Uptime Kuma - is there a way to remove the friendly name from the notification text? or even the whole "Uptime Kuma Alert" row altogether?

**Comment by CommanderStorm** [comment]
Removing that line is likely fine, feel free to provide a PR.
Given the number of notifications providers and maintainers I can't afford timewise to fix and test this myself
=> we are quite heavily reliant on contributors in this department, see our contribution guide ^^

PS: for the future, consider opening on new issues. For specific issues, which are not closely related to their parents, this otherwise spams too many people.

If you are instead looking for message templating, that code is in master but needs to be lifted from the SMTP/webhook implementations into one that can be shared between all monitors.
This would allow other monitors to make fields properly templated.
PRs welcome..

**Comment by frauberawg** [comment]
Would it be possible to revisit the topic of implementing templates for notifications in Uptime Kuma? This feature would allow for greater customization of messages and make translation easier.

**Comment by PilaScat** [comment]
Telegram

**Comment by echandler-anl** [comment]
We'd like this for Microsoft Teams notifications

**Comment by crashedthecymbal** [comment]
I just tried a push monitor, to see if a script ran. I know, Uptime Kuma is not meant to do that, but it is already very close to healthchecks.io 

SInce the script runs only once / day - I used the "Upside Down Mode". 
It's working okay, the "red/down" now means the script ran.
The notification allthough is really confusing. This could be solved with a custom message.

The custom messages as simple variables which can be set in the Settings/Notifications section
When the variables / messages (2 variables - 1 for Up/OK and 1 for down/No heartbeat in this time window) is set it will overwrite the defaults (OK / No heartbeat in the time window )

Script ran with push monitor in Upside Down Mode

![Image](https://github.com/user-attachments/assets/df77ee09-64af-40b5-990f-5889e7e99e3d)

Notifications in Gotify are confusing and could be resolved with custom messages

![Image](https://github.com/user-attachments/assets/c157dcfa-9e48-4359-ab3f-e7978596c7d8)

Instead of OK -> My custom message like: "Script just ran"
Inseat of No heartbeat in the time window -> My custom message like: "Script will ran again in 24h"

**Comment by CommanderStorm** [comment]
Yes. The status from https://github.com/louislam/uptime-kuma/issues/646#issuecomment-2732953980 is still accurate though.

If you use a notification provider we don't support this feature on, we would love for a PR.

**Comment by PilaScat** [comment]
{{ status }} tells only up, down and test, no maintenance status, should be added

**Comment by CommanderStorm** [comment]
Since there has been some confusing what it takes to enable templating on a notification provider.

Basicallly, applying the changes from `src/components/notifications/Telegram.vue` and `server/notification-providers/telegram.js` from the following PR are nessesary.
- https://github.com/louislam/uptime-kuma/pull/5637 is the closest to an reference PR

Afterwards, testing that it still works is required.

**Comment by crashedthecymbal** [comment]
When using Gotify,  I would like to see the "Friendly Name" as message heading - instead of "Uptime-Kuma".
If you add multiple monitors in Uptime-Kuma, every notification in Gotify has the big heading "Uptime-Kuma", followed by a smaller one, which gives you the actual affected service/app.

Screenshot - Use the "The Friendly Name"  as heading - instead of "Uptime-Kuma"
![Image](https://github.com/user-attachments/assets/183f5538-7986-466a-96a0-3616829fd377)

**Comment by CommanderStorm** [comment]
Your FR is not related to templating.
Please discuss this in a different issue
