### ISSUE TITLE
Restore Didn't Restore Status Page

### ISSUE THREAD

**Issue by aaronstuder** [louislam/uptime-kuma#776]
I've been testing Uptime Kuma for a few weeks now on my PC and now I'm moving it to one of our docker hosts.

When restoring everything came back but no status page. Is this a bug or by design?

**Comment by jasonwitty** [comment]
this should be part of the integrated backup. I second this feature request, if restoring volume manually is the way to restore then this feature shouldn't exist at all. but yet it does, and its used and it fails to restore the status page. 

I would actually like to see this feature implemented along side an option to execute the backup from a cli command or some other automated way that could be implemented in your own docker compose file. 

The use case is that as a user I do not want to maintain a persistent volume for this service and additionally I would like the ability to deploy uptime kuma to different locations / regions to montior from those locations. If the status page would restore from my json backup, and i had a way to import the backup as part of my deployment, then i could just include a json file of what I want to monitor as part of my deployment, deploy it anywhere and not need to worry about a persisten volume.

**Comment by markdesilva** [comment]
You don't actually need a persistent volume to backup the kuma.db file. The /app/data directory is available in the container whether you have a persistent volume or not. A persistent volume is just convenient when you upgrade UK. You can actually set a cron job within the container itself to scp out the kuma.db file to some other machine.

**Comment by jasonwitty** [comment]
Im not posting support for this feature because i need help understanding how to copy a volume. please read my use case. this is specifically requested to make it easy to deploy the service at different endpoints / regions. 

Having a JSON source file that is plain text is easily configured with ansible or tarraform. For example when you deploy to US-WEST-2 vs US-WEST-1 I want to update the title on the status page and additionally want the alerts that come into discord or slack to say which region failed. if I go down the route of restoring the volume i have to manually set all of this.

Additionally a persistent volume is absolutely required if you run in an HA environment like k3s, k8 or ECS in AWS. if your health check fails for any reason, node goes down, your HA system is going to automatically relaunch the service. If you do not have a persistent volume the way this project works right now everything will just disappear when it is launched. If this feature is implemented, then I can make the restore part of the launch config and it will not require a persistent volume.

**Comment by markdesilva** [comment]
Sorry, a little confused. You mentioned in your post 3 days ago, '"The use case is that as a user I do not want to maintain a persistent volume for this service" but then in your latest post you say "Additionally a persistent volume is absolutely required if you run in an HA environment". So, do you want to use a PV or not?

Also from your latest post:

> If you do not have a persistent volume the way this project works right now everything will just disappear when it is launched.

But UK does use PV. The first step of the installation instructions for the docker installation is to make the volume. the docker start command subsequently is to start with the PV.

```
docker volume create uptime-kuma
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
```

I apologize if I don't understand and I've got things wrong.

**Comment by markdesilva** [comment]
> @louislam @markdesilva Thank for you help. Any links on this?

Hi @aaronstuder, apologies, I missed this post.

https://youtu.be/r_A5NKkAqZM

This video goes through a lot on UK, but there is a portion about using the back up feature where host says to just back up the docker persistent volume for that container. 

If you want a one liner in your crontab, you could use this:

```
0 0 * * * cp /var/lib/docker/volumes/uptime-kuma/_data/kuma.db /full/path/to/backup/directory/kuma.db_`date +"%d-%m-%Y_%H%Mhrs"`
```

This will make a backup copy of the kuma.db with the date and time appended in the directory where you want to store the backups.

Or if you have passwordless ssh set up between a remote machine and UK server then use rsync:

```
0 0 * * * /usr/bin/rsync -avzPq root@<UK server>:/var/lib/docker/volumes/uptime-kuma/_data/kuma.db /full/path/to/backup/directory/kuma.db_`date +"%d-%m-%Y_%H%Mhrs"`
```

You can remove backups from the directory older than 7 days using this in the crontab as well:

```0 0 * * * /usr/bin/find /full/path/to/backup/directory/ -type f -atime +7 -name "kuma.db_*hrs"```

Again, replace /full/path/to/backup/directory/ with the full path of where you want to store your backups.

Hope this helps.

**Comment by louislam** [comment]
@markdesilva

⚠️ Don't just backup the `kuma.db`. The sqlite db could be corrupted in this way.

Backup the whole `data` directory is suggested.

**Comment by markdesilva** [comment]
> @markdesilva
> 
> ⚠️ Don't just backup the `kuma.db`. The sqlite db could be corrupted in this way.
> 
> Backup the whole `data` directory is suggested.

Oh ok!

In that case, I'll modify the crontab as such:

```
0 0 * * * cp -R /var/lib/docker/volumes/uptime-kuma/ /full/path/to/backup/directory/uptime-kuma_`date +"%d-%m-%Y_%H%Mhrs"`
```

And if using rsync:

```
0 0 * * * /usr/bin/rsync -avzPq root@<UK server>:/var/lib/docker/volumes/uptime-kuma /full/path/to/backup/directory/uptime-kuma_`date +"%d-%m-%Y_%H%Mhrs"`
```

And to remove backups over 7 days old:

```
0 0 * * * /usr/bin/find /full/path/to/backup/directory/ -type d -atime +7 -name "uptime-kuma_*hrs" -exec rm -rf {} \;
```

Essentially if you want to restore from the backup do:

```
cd /var/lib/docker/volumes
docker stop uptime-kuma
mv uptime-kuma uptime-kuma.bak
cp -R  /full/path/to/backup/directory/uptime-kuma-<date and time of backup you want to restore> uptime-kuma
docker start uptime-kuma
```

**Comment by jasonwitty** [comment]
@markdesilva 

i think this feature request has become a mix of instructions on how to copy a volume properly and a feature request to make the status page part of the JSON clear text backup file. 

I am only speaking to the feature request and my comments are advocating for this feature and describing why this is not fully covered by backing up a volume. if you are trying to backup your volume, then my request isnt exactly what you are trying to do though it would be an easier way for you to backup if this feature were accepted by the authors. 

to make this work i would also need an automated way to restore created or documented from json backup file as well. Then in theory i could pull this project, build the container with a custom docker file which initiated a restore after the container came up. I could also modify the clear text json as part of my build process. I could then push the build to ECR and run in fargate in different AWS regions with minor customizations such as the alert name and test titles, urls,etc. 

since the alerts can all go to slack or discord or wherever a consolidated database as being discussed in some other feature requests is not required. This is a easier way of turning this into a monitoring system from different regions. you would just have a different fqdm for each region and alerts would all be consolidated into your notify endpoint with custom messages.

**Comment by markdesilva** [comment]
Hi @jasonwitty, yes I understand what you are trying to have put in place, just that your earlier posts were contradictory. 

In any case, I did try to look at a means to convert the SQLite db to a json file from the command line, but it requires several steps and isn’t straightforward. It’s a far way off from what you actually want but I thought I’d try anyway. However, in light of what @louislam mentioned of not just backing up the kuma.db I put that on hold.

**Comment by jasonwitty** [comment]
thank you

**Comment by fishyFrogFace** [comment]
duplicate of #555?
