### ISSUE TITLE
[Feature]: Change status

### ISSUE THREAD

**Issue by ctvient28** [louislam/uptime-kuma#829]
### 📝 Describe your problem

Is there a way to have an option like Operational instead of the bar in the status page?

### 🐻 Uptime-Kuma version

1.9.1

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐋 Docker

20.10.9

### 🏷️ Docker Image Tag

1.91

### 👀 Have you spent some time to check if this question has been raised before?

- [X] I checked and didn't find similar question

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by deefdragon** [comment]
To confirm, you are referring to how [Cloudflare status for example](https://www.cloudflarestatus.com/) has "Operational" vs "Re-Routed" etc. whereas UK only  has the heartbeat bars?

Assuming the answer is yes, I think it wouldn't be too hard to use most recent ping to set a status. 

![cloudflare](https://user-images.githubusercontent.com/3053654/139487471-b3fa17d7-c9d4-4508-bcf8-98443b7dc204.png)

-----

### Some brainstorming
I'm thinking that it would be best if this and the bar were separately toggled as to if they show up. That way you could have none, either, or both showing.

I'm thinking `Operational`, `Degraded`, `Down`, and `Recovering` as some potential starting terms, but what each of them means is potentially up for debate.

Down: The service has not responded to a ping for N pings. (Uses the retry number in the monitor to define down?)
Degraded: At least one ping has been missed continuously in the last N. (or, optionally, the ping time is above a specific threshold)
Recovering: Reached the state of down, but is now responding to pings again. (Or, reached a state of down/degraded, but has been green for the most recent half of pings)
Operational: all good in last N pings

------

### Some far future considerations:
Would it be possible to set rules as to when the different terms are used? Then other statuses could be defined by the user instead of hard coded.
Would it be possible to use these states to trigger notifications?
Then a notification could go out if the monitor has become degraded instead of just down. It Would depend on custom rules again, and would likely require notification configuration options (#233) too.

**Comment by ctvient28** [comment]
@deefdragon exactly this is the one I'm talking about.  I hope we can get this feature too :)

**Comment by Kriiiiiiiz** [comment]
Would be great to have it at UK

**Comment by deefdragon** [comment]
Thinking about this some more, if we are messing around with what is displayed on the status pages, and configuring what gets displayed, we should probably be working on #818 at the same time as this. I think the files touched would be almost the same, so its worth considering at least.

This may be doable as part of #863, but I think its more likely to be done after.
