### ISSUE TITLE
Frequent False Down Notifications behind Cloudflare

### ISSUE THREAD

**Issue by ducky710** [louislam/uptime-kuma#87]
Hey I recently switched to uptime kuma from statping and have been getting a lot of false down notifications since. Usually every few hours or so i'll get one or two services randomly "Timing Out".

```
[Rainloop] [🔴 Down] connect ETIMEDOUT 172.67.163.108:443
```
It's only happening to services behind Cloudflare and it previously did not happen with statping so I'm wondering if theres something that needs to be accommodated for cloudflare users?

**Comment by Panja0** [comment]
I'm using CloudFlare as well. I've put up 7 monitors with CF enabled since 1 hour (6am UTC) and no down notifications yet.
I'll update later today and let you know.

**Comment by louislam** [comment]
I am using Cloudflare too, never seen ETIMEOUT error with 60s interval. 

It could be a connectivity problem between uptime kuma server and Cloudflare.

**Comment by ducky710** [comment]
Hmm that's interesting. I'm going to try setting them all to 120s intervals and report back. It could very well be a security or firewall setting I have set somewhere.

**Comment by Saibamen** [comment]
@ducky710: Any update? I'm not using Cloudflare, but I also have lots of `connect ETIMEDOUT` errors (ping every 60 seconds)

**Comment by ducky710** [comment]
Couldn't figure out why it was happening so for the time being i've got back to statping.

**Comment by Saibamen** [comment]
So please open the issue

**Comment by rezzorix** [comment]
More info is required here.
@Saibamen when / what monitoring are you getting the timeouts exactly?

Were you able to re-produce the issues?

**Comment by Spiritreader** [comment]
I'm running Uptime Kuma on an Azure instance myself, but didn't encounter the issue yet.
I have ~10 https services monitored with a 120s to 180s intervals.

One possible (and apparently frequenc) cause seems to be snat exhaustion on high volume calls with node.js.
Statping uses a go backend, so this might be the reason it doesn't occur there.

I came across this:
https://blog.botframework.com/2018/03/05/fix-snat-exhaustion-node-js-bots/
https://stackoverflow.com/questions/63064393/getting-axios-error-connect-etimedout-when-making-high-volume-of-calls

Apparently setting the keepAlive flag doesn't discard the port.
I don't understand enough about SNAT to know exactly how these parameters should be configured for Uptime Kuma.

Also I'm not sure if that is thre root cause, but it is mentioned frequently in tandem with ETIMEOUT.

**Comment by rezzorix** [comment]
SNAT exhaust with ~10 services monitored every 120s - 180s seconds... 
Cant really call that "High volume of Calls"....

But for sure it is a misconfiguration in outbound rules on the instance where uptime is running.

I am currently testing on different VMs in Oracle Cloud as well as AWS without any issue.
